/* eslint-disable func-style, sort-keys */
import * as stylex from "@stylexjs/stylex";

import { tokens } from "./console-ui-tokens.stylex.js";

/**
 * The public StyleX surface for Console UI. Consumers may compose these named
 * slots with their own StyleX rules. The package's generated CSS is the only
 * public Console UI stylesheet; the Host application may retain a separate
 * document/page contract layer.
 */
export const styles = stylex.create({
  surfaceRoot: {
    minHeight: 0,
    minWidth: 0,
  },
  page: {
    backgroundColor: tokens.canvas,
    color: tokens.foreground,
    display: "block",
    height: "100%",
    minHeight: "100%",
    overflow: "auto",
  },
  pageHeader: {
    alignItems: "flex-start",
    backgroundColor: tokens.canvas,
    borderBottomColor: tokens.line,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    gap: tokens.space3,
    marginInline: "auto",
    maxWidth: tokens.pageMaxWidth,
    minHeight: 96,
    paddingBlockEnd: 7,
    paddingBlockStart: tokens.space8,
    paddingInline: tokens.pageGutter,
    width: "100%",
    "@media (max-width: 720px)": { flexDirection: "column" },
  },
  pageHeading: { minWidth: 0 },
  pageEyebrow: {
    color: tokens.foregroundTertiary,
    fontSize: 9,
    fontWeight: 600,
    letterSpacing: "0.12em",
    lineHeight: 1.4,
    marginBlockEnd: 1,
    marginBlockStart: 0,
    textTransform: "uppercase",
  },
  pageTitle: {
    color: tokens.foreground,
    fontSize: 24,
    fontWeight: 600,
    letterSpacing: "-0.01em",
    lineHeight: "32px",
    margin: 0,
  },
  pageDescription: {
    color: tokens.foregroundTertiary,
    fontSize: 13,
    lineHeight: "20px",
    marginBlockEnd: 0,
    marginBlockStart: 4,
    maxWidth: 760,
  },
  pageActions: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
    marginInlineStart: "auto",
    "@media (max-width: 720px)": { marginInlineStart: 0 },
  },
  pageBody: {
    marginInline: "auto",
    maxWidth: tokens.pageMaxWidth,
    minHeight: 0,
    overflow: "hidden",
    paddingBlockEnd: 48,
    paddingInline: tokens.pageGutter,
    width: "100%",
  },
  pageFilters: {
    alignItems: "center",
    display: "flex",
    gap: tokens.space2,
    height: 48,
  },
  pageNoData: {
    color: tokens.foregroundTertiary,
    fontSize: 12,
    paddingBlock: tokens.space8,
  },
  button: {
    alignItems: "center",
    backgroundColor: tokens.control,
    borderColor: tokens.line,
    borderRadius: tokens.radiusControl,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: tokens.shadowControl,
    color: tokens.foreground,
    display: "inline-flex",
    fontFamily: "inherit",
    fontSize: 12,
    fontWeight: 500,
    gap: tokens.space1_5,
    justifyContent: "center",
    lineHeight: 1,
    minHeight: tokens.controlHeightSm,
    paddingInline: 10,
    transitionDuration: "120ms",
    transitionProperty: "background-color, border-color, color",
    transitionTimingFunction: "ease",
    whiteSpace: "nowrap",
    ":active:not(:disabled)": { backgroundColor: tokens.controlActive },
    ":disabled": { opacity: 0.45 },
    ":focus-visible": {
      outlineColor: tokens.focusRing,
      outlineOffset: 1,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
    ":hover:not(:disabled)": { backgroundColor: tokens.controlHover },
  },
  buttonMd: {
    fontSize: 13,
    minHeight: tokens.controlHeightMd,
    paddingInline: 12,
  },
  buttonPrimary: {
    backgroundColor: tokens.accent,
    borderColor: tokens.accent,
    color: tokens.accentForeground,
    ":hover:not(:disabled)": {
      backgroundColor: tokens.accentHover,
      borderColor: tokens.accentHover,
    },
  },
  buttonGhost: {
    backgroundColor: "transparent",
    borderColor: "transparent",
    boxShadow: "none",
    color: tokens.foregroundSecondary,
    ":hover:not(:disabled)": {
      backgroundColor: tokens.rowHover,
      color: tokens.foreground,
    },
  },
  buttonDanger: {
    backgroundColor: tokens.toneErrorBg,
    borderColor: tokens.toneErrorBorder,
    color: tokens.toneErrorForeground,
  },
  iconButton: {
    minWidth: tokens.controlHeightSm,
    paddingInline: 0,
    width: tokens.controlHeightSm,
  },
  iconButtonMd: {
    minWidth: tokens.controlHeightMd,
    width: tokens.controlHeightMd,
  },
  badge: {
    alignItems: "center",
    backgroundColor: tokens.toneMutedBg,
    borderColor: tokens.toneMutedBorder,
    borderRadius: tokens.radiusControl,
    borderStyle: "solid",
    borderWidth: 1,
    color: tokens.toneMutedForeground,
    display: "inline-flex",
    fontSize: 11,
    fontWeight: 500,
    gap: tokens.space1_5,
    lineHeight: 1.2,
    minHeight: 22,
    paddingBlock: 2,
    paddingInline: 7,
  },
  badgeInfo: {
    backgroundColor: tokens.toneInfoBg,
    borderColor: tokens.toneInfoBorder,
    color: tokens.toneInfoForeground,
  },
  badgeSuccess: {
    backgroundColor: tokens.toneSuccessBg,
    borderColor: tokens.toneSuccessBorder,
    color: tokens.toneSuccessForeground,
  },
  badgeWarning: {
    backgroundColor: tokens.toneWarningBg,
    borderColor: tokens.toneWarningBorder,
    color: tokens.toneWarningForeground,
  },
  badgeDanger: {
    backgroundColor: tokens.toneErrorBg,
    borderColor: tokens.toneErrorBorder,
    color: tokens.toneErrorForeground,
  },
  inlineStatus: {
    alignItems: "center",
    color: tokens.foregroundSecondary,
    columnGap: 7,
    display: "inline-grid",
    fontSize: 11,
    gridTemplateColumns: "6px minmax(0, auto)",
    lineHeight: "16px",
    minHeight: 16,
    whiteSpace: "nowrap",
  },
  inlineStatusTop: { alignItems: "start" },
  inlineStatusDot: {
    backgroundColor: tokens.foregroundTertiary,
    borderRadius: tokens.radiusPill,
    flex: "none",
    height: 6,
    width: 6,
  },
  inlineStatusDotTop: { marginBlockStart: 5 },
  inlineStatusDotInfo: { backgroundColor: tokens.info },
  inlineStatusDotSuccess: { backgroundColor: tokens.success },
  inlineStatusDotWarning: { backgroundColor: tokens.warning },
  inlineStatusDotDanger: { backgroundColor: tokens.error },
  inlineStatusLabel: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  iconSlot: {
    alignItems: "center",
    display: "inline-grid",
    flex: "0 0 16px",
    height: 16,
    justifyContent: "center",
    width: 16,
  },
  iconSlot12: { flexBasis: 12, height: 12, width: 12 },
  iconSlot20: { flexBasis: 20, height: 20, width: 20 },
  filterControl: {
    alignItems: "center",
    backgroundColor: tokens.control,
    borderColor: tokens.lineStrong,
    borderRadius: tokens.radiusControl,
    borderStyle: "solid",
    borderWidth: 1,
    color: tokens.foregroundSecondary,
    display: "inline-flex",
    fontFamily: "inherit",
    fontSize: 11,
    fontWeight: 500,
    gap: tokens.space2,
    height: tokens.controlHeightSm,
    lineHeight: "16px",
    minHeight: tokens.controlHeightSm,
    paddingInline: 10,
    whiteSpace: "nowrap",
    ":hover:not(:disabled)": {
      backgroundColor: tokens.controlHover,
      color: tokens.foreground,
    },
    ":focus-visible": {
      outlineColor: tokens.focusRing,
      outlineOffset: 1,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  filterControlLabel: { overflow: "hidden", textOverflow: "ellipsis" },
  paneHeader: {
    alignItems: "center",
    display: "flex",
    gap: tokens.space2,
    height: tokens.paneHeaderHeight,
    justifyContent: "space-between",
    minHeight: tokens.paneHeaderHeight,
    overflow: "hidden",
    paddingInline: 10,
    whiteSpace: "nowrap",
  },
  paneHeaderTitle: {
    color: tokens.foreground,
    fontSize: 13,
    fontWeight: 500,
    lineHeight: "17px",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  paneHeaderMeta: {
    color: tokens.foregroundTertiary,
    flex: "none",
    fontSize: 10,
    lineHeight: "14px",
  },
  surfaceGroupLabel: {
    alignItems: "center",
    color: tokens.foregroundTertiary,
    display: "flex",
    gap: 6,
    height: 32,
    minHeight: 32,
    overflow: "hidden",
    paddingBlock: 0,
    paddingInlineEnd: 8,
    paddingInlineStart: 10,
  },
  surfaceGroupLabelText: {
    fontSize: 10,
    fontWeight: 600,
    letterSpacing: "0.4px",
    lineHeight: "14px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  tableHeader: {
    alignItems: "center",
    color: tokens.foregroundTertiary,
    display: "grid",
    fontSize: 10,
    fontWeight: 500,
    gridTemplateColumns: "320px 120px 170px 122px",
    height: tokens.tableHeaderHeight,
    lineHeight: "14px",
    minHeight: tokens.tableHeaderHeight,
    minWidth: 732,
    whiteSpace: "nowrap",
  },
  tableHeaderProvider: { gridTemplateColumns: "260px 220px 160px 92px" },
  tableHeaderRuntime: {
    gridTemplateColumns: "250px 110px 140px 120px 86px",
    minWidth: 706,
  },
  tableHeaderCell: {
    minWidth: 0,
    overflow: "hidden",
    paddingInlineStart: 0,
    textOverflow: "ellipsis",
  },
  tableHeaderCellFirst: { paddingInlineStart: 10 },
  dataRow: {
    alignItems: "center",
    color: tokens.foregroundSecondary,
    display: "grid",
    fontSize: 11,
    gridTemplateColumns: "320px 120px 170px 122px",
    height: tokens.tableRowHeight,
    lineHeight: "16px",
    minHeight: tokens.tableRowHeight,
    minWidth: 732,
    overflow: "hidden",
    textAlign: "left",
  },
  dataRowProvider: { gridTemplateColumns: "260px 220px 160px 92px" },
  dataRowRuntime: {
    gridTemplateColumns: "250px 110px 140px 120px 86px",
    minWidth: 706,
  },
  dataRowSelected: { backgroundColor: tokens.rowSelected },
  dataRowInteractive: {
    ":hover": { backgroundColor: tokens.rowHover },
    ":focus-visible": {
      backgroundColor: tokens.rowHover,
      outlineColor: tokens.focusRing,
      outlineOffset: -2,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  dataRowPrimary: {
    display: "flex",
    flexDirection: "column",
    gap: 1,
    justifyContent: "center",
    minHeight: 36,
    minWidth: 0,
    overflow: "hidden",
    paddingInlineStart: 10,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  dataRowPrimaryText: {
    color: tokens.foreground,
    fontSize: 12,
    fontWeight: 500,
    lineHeight: "16px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  dataRowSecondaryText: {
    color: tokens.foregroundTertiary,
    fontFamily: tokens.fontCode,
    fontSize: 10,
    lineHeight: "14px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  dataRowCell: {
    minWidth: 0,
    overflow: "hidden",
    paddingInlineStart: 0,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  dataGrid: {
    backgroundColor: tokens.lineSubtle,
    display: "flex",
    flexDirection: "column",
    gap: 1,
    minWidth: 0,
    overflowX: "auto",
  },
  panel: {
    backgroundColor: tokens.panel,
    borderColor: tokens.line,
    borderRadius: 0,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: tokens.shadowPanel,
    overflow: "hidden",
  },
  panelHeader: {
    alignItems: "center",
    backgroundColor: tokens.panelHeader,
    borderBottomColor: tokens.line,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    gap: tokens.space3,
    justifyContent: "space-between",
    minHeight: 40,
    paddingBlock: 6,
    paddingInline: 10,
  },
  panelTitle: {
    color: tokens.foreground,
    fontSize: 11,
    fontWeight: 600,
    lineHeight: 1.4,
    margin: 0,
  },
  panelDescription: {
    color: tokens.foregroundTertiary,
    fontSize: 12,
    lineHeight: 1.5,
    marginBlockEnd: 0,
    marginBlockStart: 2,
  },
  panelContentSm: { padding: tokens.space3 },
  panelContentMd: { padding: tokens.space4 },
  summary: {
    backgroundColor: tokens.panel,
    borderBottomColor: tokens.line,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gridAutoColumns: "minmax(110px, 1fr)",
    gridAutoFlow: "column",
    overflowX: "auto",
  },
  summaryItem: {
    alignContent: "center",
    borderRightColor: tokens.line,
    borderRightStyle: "solid",
    borderRightWidth: 1,
    display: "grid",
    gap: "2px 8px",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    minHeight: 52,
    paddingBlock: 7,
    paddingInline: 12,
    ":last-child": { borderRightWidth: 0 },
  },
  summaryLabel: {
    color: tokens.foregroundTertiary,
    fontSize: 9,
    letterSpacing: "0.08em",
    overflow: "hidden",
    textOverflow: "ellipsis",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  summaryValue: {
    color: tokens.foreground,
    fontSize: 14,
    fontWeight: 600,
    lineHeight: 1.2,
  },
  summaryValueWarning: { color: tokens.toneWarningForeground },
  summaryValueDanger: { color: tokens.toneErrorForeground },
  summaryValueSuccess: { color: tokens.toneSuccessForeground },
  summaryNote: {
    color: tokens.foregroundTertiary,
    fontSize: 10,
    gridColumn: "1 / -1",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  splitView: {
    display: "grid",
    gridTemplateColumns: `minmax(0, 1fr) ${tokens.inspectorWidth}`,
    minHeight: 0,
    overflow: "hidden",
    "@media (max-width: 720px)": {
      gridTemplateColumns: "1fr",
      gridTemplateRows: "minmax(220px, 1fr) minmax(180px, auto)",
    },
  },
  splitViewPane: {
    backgroundColor: tokens.canvas,
    minHeight: 0,
    minWidth: 0,
    overflow: "auto",
  },
  splitViewMain: { paddingInlineEnd: 28 },
  splitViewInspector: {
    borderInlineStartColor: tokens.lineSubtle,
    borderInlineStartStyle: "solid",
    borderInlineStartWidth: 1,
    paddingBlockStart: 28,
    paddingInlineStart: 28,
    "@media (max-width: 720px)": {
      borderBlockStartColor: tokens.line,
      borderBlockStartStyle: "solid",
      borderBlockStartWidth: 1,
      borderInlineStartStyle: "none",
      borderInlineStartWidth: 0,
    },
  },
  splitViewNone: { padding: 0 },
  inspector: {
    backgroundColor: tokens.canvas,
    minWidth: 0,
    overflow: "hidden",
  },
  inspectorHeader: { minWidth: 0, padding: 28 },
  inspectorHeaderWithAction: {
    alignItems: "flex-start",
    display: "flex",
    gap: tokens.space4,
    justifyContent: "space-between",
  },
  inspectorHeaderContent: { minWidth: 0 },
  inspectorHeaderAction: { flex: "none" },
  inspectorTitle: {
    color: tokens.foreground,
    fontSize: 18,
    fontWeight: 600,
    lineHeight: "26px",
    margin: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  inspectorSubtitle: {
    color: tokens.foregroundTertiary,
    fontFamily: tokens.fontCode,
    fontSize: 10,
    lineHeight: "14px",
    marginBlockEnd: 0,
    marginBlockStart: 2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  inspectorStatus: { marginBlockStart: 16 },
  inspectorSection: {
    borderBlockStartColor: tokens.line,
    borderBlockStartStyle: "solid",
    borderBlockStartWidth: 1,
    minWidth: 0,
    paddingBlock: tokens.space4,
    paddingInline: 28,
  },
  inspectorSectionTitle: {
    color: tokens.foregroundSecondary,
    fontSize: 11,
    fontWeight: 500,
    lineHeight: "16px",
    marginBlockEnd: tokens.space2,
    marginBlockStart: 0,
  },
  inspectorSectionBody: {
    color: tokens.foreground,
    fontSize: 12,
    lineHeight: 1.55,
  },
  inspectorActions: {
    borderBlockStartColor: tokens.line,
    borderBlockStartStyle: "solid",
    borderBlockStartWidth: 1,
    display: "flex",
    flexWrap: "wrap",
    gap: tokens.space2,
    paddingBlock: tokens.space4,
    paddingInline: 28,
  },
  section: {
    backgroundColor: tokens.canvas,
    borderBlockEndColor: tokens.line,
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: 1,
    minWidth: 0,
  },
  sectionHeader: {
    alignItems: "center",
    backgroundColor: tokens.canvas,
    borderBlockEndColor: tokens.line,
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: 1,
    display: "flex",
    gap: tokens.space2,
    minHeight: 50,
    paddingInline: 10,
  },
  sectionTitle: {
    color: tokens.foreground,
    fontSize: 14,
    fontWeight: 600,
    letterSpacing: 0,
    margin: 0,
  },
  sectionMeta: {
    color: tokens.foregroundTertiary,
    fontSize: 10,
    marginInlineStart: "auto",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  sectionBody: { minWidth: 0 },
  keyValuesRow: {
    alignItems: "center",
    borderBlockEndColor: tokens.lineSubtle,
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: 1,
    display: "grid",
    fontSize: 11,
    gap: 10,
    gridTemplateColumns: "112px minmax(0, 1fr)",
    minHeight: 34,
    paddingBlock: 5,
    paddingInline: 10,
    ":last-child": { borderBottomWidth: 0 },
  },
  keyValuesLabel: { color: tokens.foregroundTertiary },
  keyValuesValue: {
    color: tokens.foregroundSecondary,
    margin: 0,
    minWidth: 0,
    overflowWrap: "anywhere",
  },
  state: {
    alignContent: "center",
    color: tokens.foregroundTertiary,
    display: "grid",
    gap: 6,
    justifyItems: "center",
    minHeight: 180,
    padding: tokens.space6,
    textAlign: "center",
  },
  stateIcon: { display: "grid", height: 24, placeItems: "center", width: 24 },
  stateTitle: { color: tokens.foreground, fontSize: 12, fontWeight: 600 },
  stateDescription: {
    fontSize: 11,
    lineHeight: 1.5,
    margin: 0,
    maxWidth: 460,
  },
  stateAction: { marginBlockStart: 4 },
  tabsList: {
    alignItems: "stretch",
    borderBlockEndColor: tokens.line,
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: 1,
    display: "flex",
    gap: 4,
    minWidth: 0,
  },
  tabsListPage: { gap: tokens.space4, height: tokens.tabHeight },
  tabsListInspector: { gap: tokens.space3, height: tokens.tabHeight },
  tabsListInsetSm: { paddingInline: tokens.space2 },
  tabsTab: {
    alignItems: "center",
    backgroundColor: "transparent",
    border: 0,
    color: tokens.foregroundTertiary,
    display: "inline-flex",
    fontFamily: "inherit",
    fontSize: 12,
    fontWeight: 500,
    gap: tokens.space1_5,
    justifyContent: "center",
    minHeight: 32,
    paddingInline: 4,
    position: "relative",
    whiteSpace: "nowrap",
    ":first-child": { paddingInlineStart: 0 },
    ":focus-visible": {
      outlineColor: tokens.focusRing,
      outlineOffset: -3,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
    ":hover": { color: tokens.foreground },
  },
  tabsTabDense: { minHeight: tokens.tabHeight, paddingInline: 0 },
  tabsTabSelected: {
    color: tokens.foreground,
    ":after": {
      backgroundColor: tokens.accent,
      bottom: -1,
      content: '""',
      height: 1,
      position: "absolute",
      left: 4,
      right: 4,
    },
    ":first-child:after": { left: 0 },
  },
  tabsTabSelectedDense: { ":after": { left: 0, right: 0 } },
  tabsTabSelectedLeadingIcon: { ":first-child:after": { left: 4 } },
  tabsPanel: { minWidth: 0 },
  settingsGroup: {
    borderBlockStartColor: tokens.line,
    borderBlockStartStyle: "solid",
    borderBlockStartWidth: 1,
  },
  settingsGroupHeader: {
    paddingBlockEnd: tokens.space2,
    paddingBlockStart: tokens.space4,
    paddingInline: tokens.contentGutter,
  },
  settingsGroupTitle: {
    color: tokens.foreground,
    fontSize: 13,
    fontWeight: 600,
    lineHeight: 1.4,
    margin: 0,
  },
  settingsGroupDescription: {
    color: tokens.foregroundTertiary,
    fontSize: 12,
    lineHeight: 1.5,
    marginBlockEnd: 0,
    marginBlockStart: tokens.space1,
  },
  settingsRow: {
    alignItems: "center",
    borderBlockStartColor: tokens.lineSubtle,
    borderBlockStartStyle: "solid",
    borderBlockStartWidth: 1,
    display: "grid",
    gap: tokens.space6,
    gridTemplateColumns: "minmax(0, 1fr) minmax(180px, 280px)",
    minHeight: 54,
    paddingBlock: tokens.space2,
    paddingInline: tokens.contentGutter,
    "@media (max-width: 720px)": {
      gap: tokens.space2,
      gridTemplateColumns: "1fr",
      paddingBlock: tokens.space3,
    },
  },
  settingsRowCopy: { minWidth: 0 },
  settingsRowLabel: {
    color: tokens.foreground,
    fontSize: 12,
    fontWeight: 500,
    lineHeight: 1.4,
  },
  settingsRowDescription: {
    color: tokens.foregroundTertiary,
    fontSize: 11,
    lineHeight: 1.45,
    marginBlockStart: 2,
  },
  settingsRowControl: { minWidth: 0 },
  field: { display: "grid", gap: "6px" },
  fieldLabel: {
    color: tokens.foregroundSecondary,
    fontSize: 12,
    fontWeight: 500,
    lineHeight: 1.4,
  },
  fieldHint: {
    color: tokens.foregroundTertiary,
    fontSize: 11,
    lineHeight: 1.5,
    margin: 0,
  },
  fieldError: {
    color: tokens.toneErrorForeground,
    fontSize: 11,
    lineHeight: 1.5,
    margin: 0,
  },
  input: {
    backgroundColor: tokens.control,
    borderColor: tokens.line,
    borderRadius: tokens.radiusControl,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: tokens.shadowControl,
    color: tokens.foreground,
    fontFamily: "inherit",
    fontSize: 13,
    minHeight: tokens.controlHeightMd,
    paddingInline: 10,
    width: "100%",
    "::placeholder": { color: tokens.foregroundQuaternary },
    ":focus-visible": {
      borderColor: tokens.lineStrong,
      boxShadow: `inset 0 0 0 1px ${tokens.focusRingMuted}`,
      outline: "none",
    },
  },
  textarea: {
    lineHeight: 1.5,
    minHeight: 88,
    paddingBlock: tokens.space2,
    resize: "vertical",
  },
  emptyState: {
    alignContent: "center",
    color: tokens.foregroundTertiary,
    display: "grid",
    gap: tokens.space2,
    justifyItems: "center",
    minHeight: 180,
    padding: tokens.space8,
    textAlign: "center",
  },
  emptyStateIcon: {
    color: tokens.foregroundTertiary,
    display: "grid",
    height: 32,
    placeItems: "center",
    width: 32,
  },
  emptyStateTitle: {
    color: tokens.foreground,
    fontSize: 14,
    fontWeight: 600,
    margin: 0,
  },
  emptyStateDescription: {
    color: tokens.foregroundTertiary,
    fontSize: 12,
    lineHeight: 1.55,
    margin: 0,
    maxWidth: 440,
  },
  tableWrap: { overflowX: "auto" },
  table: {
    borderCollapse: "collapse",
    color: tokens.foregroundSecondary,
    fontSize: 12,
    textAlign: "left",
    width: "100%",
  },
  tableHead: {
    borderBlockEndColor: tokens.line,
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: 1,
    color: tokens.foregroundTertiary,
  },
  tableRow: {
    borderBlockEndColor: tokens.lineSubtle,
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: 1,
    ":hover": { backgroundColor: tokens.rowHover },
    ":last-child": { borderBottomWidth: 0 },
  },
  dataTableHeaderCell: {
    fontSize: 10,
    fontWeight: 500,
    height: 38,
    paddingInline: 10,
  },
  dataTableCell: { height: 64, paddingInline: 10 },
  /** Host shell styles.  Kept in the public catalog so an alternate shell
   * composition can reuse the same geometry without importing authored CSS. */
  shell: {
    backgroundColor: tokens.canvas,
    color: tokens.foreground,
    display: "grid",
    minHeight: "100vh",
  },
  shellExpanded: {
    gridTemplateColumns: tokens.sidebarTrack,
    "@media (max-width: 1100px)": {
      gridTemplateColumns: tokens.sidebarCollapsedTrack,
    },
  },
  shellCollapsed: {
    gridTemplateColumns: tokens.sidebarCollapsedTrack,
  },
  shellSidebar: {
    backgroundColor: tokens.sidebar,
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    paddingBlockEnd: 16,
    paddingBlockStart: 20,
    paddingInline: 8,
    position: "sticky",
    top: 0,
    zIndex: 30,
  },
  shellBrand: {
    alignItems: "center",
    display: "flex",
    gap: 10,
    height: 32,
    paddingInline: 10,
  },
  shellBrandCollapsed: { justifyContent: "center" },
  shellBrandMark: {
    backgroundColor: tokens.foreground,
    borderRadius: 3,
    flex: "none",
    height: 14,
    width: 14,
  },
  shellBrandName: {
    color: tokens.foreground,
    fontSize: 14,
    fontWeight: 600,
    lineHeight: "20px",
  },
  shellCollapsedOnly: { display: "none" },
  shellExpandedOnly: {
    "@media (max-width: 1100px)": { display: "none" },
  },
  shellProduction: {
    alignItems: "center",
    color: tokens.foregroundTertiary,
    display: "flex",
    fontSize: 10,
    fontWeight: 600,
    height: 32,
    lineHeight: "14px",
    paddingInline: 10,
  },
  shellNav: { display: "grid", gap: 2, marginBlockStart: 2 },
  shellNavGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  shellNavLink: {
    alignItems: "center",
    borderRadius: tokens.radiusControl,
    color: tokens.foregroundSecondary,
    display: "flex",
    fontSize: 12,
    gap: 7,
    height: 32,
    lineHeight: "16px",
    paddingInline: 10,
    textDecoration: "none",
    transitionDuration: "120ms",
    transitionProperty: "background-color, color",
    transitionTimingFunction: "ease",
    ":hover": {
      backgroundColor: tokens.rowHover,
      color: tokens.foreground,
    },
    ":focus-visible": {
      outlineColor: tokens.focusRing,
      outlineOffset: 1,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  shellNavLinkCollapsed: { justifyContent: "center" },
  shellNavLinkActive: {
    backgroundColor: tokens.rowSelected,
    color: tokens.foreground,
    fontWeight: 500,
  },
  shellNavLabel: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  shellShortcut: {
    color: tokens.foregroundTertiary,
    fontSize: 11,
    fontWeight: 400,
    lineHeight: "16px",
    marginInlineStart: "auto",
  },
  shellBottom: { marginBlockStart: "auto" },
  shellProfile: {
    alignItems: "center",
    display: "flex",
    gap: 10,
    height: 40,
    paddingInlineStart: 10,
  },
  shellProfileCollapsed: { justifyContent: "center" },
  shellAvatar: {
    borderColor: tokens.lineStrong,
    borderRadius: tokens.radiusPill,
    borderStyle: "solid",
    borderWidth: 1,
    flex: "none",
    height: 20,
    width: 20,
  },
  shellProfileCopy: { minWidth: 0 },
  shellProfileName: {
    color: tokens.foregroundSecondary,
    display: "block",
    fontSize: 11,
    fontWeight: 500,
    lineHeight: "16px",
  },
  shellProfileRole: {
    color: tokens.foregroundTertiary,
    display: "block",
    fontSize: 10,
    lineHeight: "14px",
  },
  shellMain: { minWidth: 0 },
  shellToolbar: {
    alignItems: "center",
    backgroundColor: tokens.window,
    borderBottomColor: tokens.lineSubtle,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    height: tokens.toolbarHeight,
    paddingInline: 40,
  },
  shellBreadcrumb: {
    color: tokens.foregroundTertiary,
    fontSize: 11,
    lineHeight: "16px",
  },
  shellBreadcrumbSeparator: { paddingInline: 4 },
  shellSearch: {
    alignItems: "center",
    backgroundColor: tokens.control,
    borderColor: tokens.line,
    borderRadius: tokens.radiusControl,
    borderStyle: "solid",
    borderWidth: 1,
    color: tokens.foregroundTertiary,
    display: "flex",
    fontFamily: "inherit",
    fontSize: 11,
    gap: 0,
    height: 28,
    marginInlineStart: "auto",
    paddingInline: 8,
    transitionDuration: "120ms",
    transitionProperty: "background-color, border-color",
    transitionTimingFunction: "ease",
    width: 209,
    ":hover": { backgroundColor: tokens.controlHover },
    ":focus-visible": {
      outlineColor: tokens.focusRing,
      outlineOffset: 1,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  shellSearchLabel: { marginInlineStart: 20 },
  shellSearchShortcut: {
    fontFamily: tokens.fontCode,
    marginInlineStart: "auto",
  },
  shellUpdated: {
    color: tokens.foregroundTertiary,
    fontSize: 11,
    marginInlineStart: 12,
  },
  shellContent: { height: "calc(100vh - 48px)", overflow: "hidden" },
  skipLink: {
    backgroundColor: tokens.overlay,
    borderColor: tokens.lineStrong,
    borderRadius: tokens.radiusControl,
    borderStyle: "solid",
    borderWidth: 1,
    color: tokens.foreground,
    fontSize: 12,
    left: 8,
    paddingBlock: 8,
    paddingInline: 12,
    position: "fixed",
    top: 8,
    transform: "translateY(-160%)",
    transitionDuration: "120ms",
    transitionProperty: "transform",
    transitionTimingFunction: "ease",
    zIndex: 100,
    ":focus-visible": { transform: "translateY(0)" },
  },
  workspaceRoot: { position: "relative" },
  workspaceTrigger: {
    alignItems: "center",
    borderRadius: tokens.radiusControl,
    color: tokens.foregroundSecondary,
    display: "flex",
    fontFamily: "inherit",
    fontSize: 12,
    fontWeight: 500,
    gap: tokens.space2,
    height: 36,
    lineHeight: "16px",
    paddingInline: 10,
    textAlign: "left",
    width: "100%",
    ":hover": { backgroundColor: tokens.rowHover },
    ":focus-visible": {
      outlineColor: tokens.focusRing,
      outlineOffset: 1,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  workspaceTriggerCollapsed: { justifyContent: "center" },
  workspaceTriggerLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  workspaceTriggerChevron: { marginInlineStart: "auto" },
  workspaceMenu: {
    backgroundColor: tokens.overlay,
    borderColor: tokens.lineStrong,
    borderRadius: tokens.radiusPopover,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: tokens.shadowOverlay,
    left: 0,
    opacity: 0,
    padding: 4,
    pointerEvents: "none",
    position: "absolute",
    top: 40,
    transform: "translateY(-4px) scale(0.985)",
    transformOrigin: "top left",
    transitionDuration: "140ms",
    transitionProperty: "opacity, transform",
    transitionTimingFunction: "cubic-bezier(0.16, 1, 0.3, 1)",
    width: 208,
    zIndex: 50,
    "@media (prefers-reduced-motion: reduce)": {
      transform: "none",
      transition: "none",
    },
  },
  workspaceMenuVisible: {
    opacity: 1,
    pointerEvents: "auto",
    transform: "translateY(0) scale(1)",
  },
  workspaceMenuCollapsed: { left: 48 },
  workspaceMenuLabel: {
    alignItems: "center",
    color: tokens.foregroundTertiary,
    display: "flex",
    fontSize: 10,
    height: 24,
    paddingInline: 8,
  },
  workspaceMenuItem: {
    alignItems: "center",
    borderRadius: tokens.radiusControl,
    display: "grid",
    fontFamily: "inherit",
    gap: tokens.space2,
    gridTemplateColumns: "16px minmax(0, 1fr) 16px",
    height: 32,
    paddingInline: 8,
    textAlign: "left",
    width: "100%",
    ":hover": { backgroundColor: tokens.rowHover },
    ":focus-visible": {
      outlineColor: tokens.focusRing,
      outlineOffset: -2,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  workspaceMenuItemActive: { backgroundColor: tokens.rowHover },
  workspaceMenuItemTitle: {
    fontSize: 12,
    fontWeight: 500,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  workspaceMenuItemCount: {
    alignItems: "center",
    display: "grid",
    height: 16,
    justifyItems: "center",
    width: 16,
  },
  workspaceMenuItemCountText: {
    color: tokens.foregroundTertiary,
    fontFamily: tokens.fontCode,
    fontSize: 10,
  },
  workspaceMenuDivider: {
    backgroundColor: tokens.line,
    height: 1,
    marginBlock: 4,
  },
  workspaceMenuModules: {
    alignItems: "center",
    borderRadius: tokens.radiusControl,
    display: "grid",
    gap: tokens.space2,
    gridTemplateColumns: "16px minmax(0, 1fr)",
    height: 40,
    paddingInline: 8,
    textDecoration: "none",
    width: "100%",
    ":hover": { backgroundColor: tokens.rowHover },
  },
  workspaceMenuModulesTitle: {
    display: "block",
    fontSize: 12,
    fontWeight: 500,
  },
  workspaceMenuModulesDescription: {
    color: tokens.foregroundTertiary,
    display: "block",
    fontSize: 10,
  },
  statusScreen: {
    alignItems: "center",
    backgroundColor: tokens.canvas,
    color: tokens.foreground,
    display: "grid",
    justifyItems: "center",
    minHeight: "100vh",
    paddingInline: tokens.space4,
  },
  statusScreenPadded: { padding: tokens.space6 },
  statusScreenMessage: { color: tokens.foregroundSecondary, fontSize: 13 },
  statusCard: {
    backgroundColor: tokens.panel,
    borderColor: tokens.line,
    borderRadius: tokens.radiusPanel,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: tokens.shadowPanel,
    padding: tokens.space5,
    width: "100%",
  },
  statusCardNarrow: { maxWidth: 384 },
  statusCardWide: { maxWidth: 768 },
  statusCardOverlay: {
    borderRadius: tokens.radiusPopover,
    maxWidth: 960,
    overflow: "hidden",
  },
  statusCopy: { display: "grid", gap: tokens.space1 },
  statusEyebrow: {
    color: tokens.foregroundTertiary,
    fontSize: 10,
    fontWeight: 600,
    letterSpacing: "0.18em",
    textTransform: "uppercase",
  },
  statusTitle: { fontSize: 18, fontWeight: 600, marginBlockStart: 4 },
  statusTitleLarge: { fontSize: 24, fontWeight: 600, marginBlockStart: 4 },
  statusDescription: {
    color: tokens.foregroundSecondary,
    fontSize: 13,
    lineHeight: 1.5,
    marginBlockStart: 8,
  },
  statusError: {
    color: tokens.toneErrorForeground,
    fontSize: 12,
    marginBlockStart: 16,
  },
  statusForm: { display: "grid", gap: tokens.space3, marginBlockStart: 20 },
  statusLabel: {
    color: tokens.foregroundSecondary,
    display: "grid",
    fontSize: 12,
    fontWeight: 500,
    gap: 6,
  },
  statusInput: {
    backgroundColor: tokens.control,
    borderColor: tokens.line,
    borderRadius: tokens.radiusControl,
    borderStyle: "solid",
    borderWidth: 1,
    color: tokens.foreground,
    fontFamily: "inherit",
    fontSize: 14,
    height: 36,
    minWidth: 0,
    outline: "none",
    paddingInline: 12,
    transitionDuration: "120ms",
    transitionProperty: "background-color, border-color",
    transitionTimingFunction: "ease",
    width: "100%",
    "::placeholder": { color: tokens.foregroundTertiary },
    ":focus-visible": {
      backgroundColor: tokens.controlHover,
      borderColor: tokens.accent,
      outlineColor: tokens.focusRing,
      outlineOffset: 1,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  statusButtonFull: { width: "100%" },
  statusButtonSpaced: { marginBlockStart: 8, width: "100%" },
  statusPre: {
    backgroundColor: tokens.control,
    borderColor: tokens.line,
    borderRadius: tokens.radiusControl,
    borderStyle: "solid",
    borderWidth: 1,
    color: tokens.foreground,
    fontSize: 12,
    marginBlockStart: 16,
    maxWidth: "100%",
    overflowX: "auto",
    padding: tokens.space3,
  },
  statusFootnote: {
    color: tokens.foregroundTertiary,
    fontSize: 12,
    marginBlockStart: 12,
  },
  recoveryHeader: {
    alignItems: "flex-start",
    borderBottomColor: tokens.line,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    gap: tokens.space3,
    padding: tokens.space5,
  },
  recoveryHeaderIcon: { color: tokens.warning, marginBlockStart: 4 },
  recoveryFooter: {
    borderTopColor: tokens.line,
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "flex",
    justifyContent: "flex-end",
    padding: tokens.space3,
  },
  recoveryIssue: {
    backgroundColor: tokens.canvas,
    borderBottomColor: tokens.lineSubtle,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    paddingBlock: tokens.space4,
    paddingInline: tokens.space5,
  },
  recoveryIssueMeta: {
    alignItems: "center",
    color: tokens.foregroundTertiary,
    display: "flex",
    flexWrap: "wrap",
    fontSize: 12,
    gap: tokens.space2,
  },
  recoveryIssueMessage: { fontSize: 14, fontWeight: 500, marginBlockStart: 8 },
  recoveryIssueDetail: {
    color: tokens.foregroundTertiary,
    fontSize: 12,
    marginBlockStart: 8,
  },
  recoveryIssueAction: {
    color: tokens.foregroundSecondary,
    fontSize: 14,
    marginBlockStart: 12,
  },
  moduleState: {
    backgroundColor: tokens.panel,
    borderColor: tokens.line,
    borderRadius: tokens.radiusPanel,
    borderStyle: "solid",
    borderWidth: 1,
    margin: tokens.space6,
    padding: tokens.space6,
  },
  moduleStateTitle: { fontSize: 16, fontWeight: 600 },
  moduleStateDescription: {
    color: tokens.foregroundSecondary,
    fontSize: 14,
    marginBlockStart: 8,
  },
  settingsToggle: {
    borderRadius: tokens.radiusPill,
    borderStyle: "solid",
    borderWidth: 1,
    height: 16,
    position: "relative",
    transitionDuration: "120ms",
    transitionProperty: "background-color, border-color",
    transitionTimingFunction: "ease",
    width: 28,
    ":focus-visible": {
      outlineColor: tokens.focusRing,
      outlineOffset: 1,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  settingsToggleOn: {
    backgroundColor: tokens.foreground,
    borderColor: tokens.foreground,
  },
  settingsToggleOff: {
    backgroundColor: tokens.control,
    borderColor: tokens.lineStrong,
  },
  settingsToggleKnob: {
    borderRadius: tokens.radiusPill,
    height: 10,
    left: 2,
    position: "absolute",
    top: 2,
    transitionDuration: "120ms",
    transitionProperty: "background-color, transform",
    transitionTimingFunction: "ease",
    width: 10,
  },
  settingsToggleKnobOn: {
    backgroundColor: tokens.canvas,
    transform: "translateX(13px)",
  },
  settingsToggleKnobOff: {
    backgroundColor: tokens.foregroundTertiary,
    transform: "translateX(0.5px)",
  },
});

export type ConsoleStyle = stylex.StyleXStyles;

export function mergeStyleProps(
  style: unknown,
  className: string | undefined,
  ...compiled: unknown[]
) {
  // StyleX's generated namespace members intentionally carry a narrower
  // property-level type than `StyleXStyles`.  The runtime accepts both the
  // generated member and conditional arrays, so keep this adapter's boundary
  // permissive while preserving the public `ConsoleStyle` prop type.
  const props = stylex.props(...(compiled as never[]), style as never);
  return {
    ...props,
    className: [props.className, className].filter(Boolean).join(" "),
  };
}
