packages:
  - .
  - plugins/console/shell
  - packages/console-authoring
  - packages/console

allowBuilds:
  esbuild: true

overrides:
  "@lenso/core": file:.artifacts/framework/lenso-core-0.3.0-93dc3a81226d981a861b8afe51e25d07538aded5.tgz
  "@lenso/engine": file:.artifacts/framework/lenso-engine-0.4.0-93dc3a81226d981a861b8afe51e25d07538aded5.tgz
  "@lenso/manage": file:.artifacts/framework/lenso-manage-0.4.0-93dc3a81226d981a861b8afe51e25d07538aded5.tgz
  "@lenso/auth": file:.artifacts/framework/lenso-auth-0.3.1-93dc3a81226d981a861b8afe51e25d07538aded5.tgz
  "@lenso/web": file:.artifacts/framework/lenso-web-0.3.1-93dc3a81226d981a861b8afe51e25d07538aded5.tgz
  "@lenso/audit": file:.artifacts/framework/lenso-audit-0.2.1-93dc3a81226d981a861b8afe51e25d07538aded5.tgz
  "@lenso/authorization": file:.artifacts/framework/lenso-authorization-0.2.1-93dc3a81226d981a861b8afe51e25d07538aded5.tgz
  "@lenso/tasks": file:.artifacts/framework/lenso-tasks-0.3.1-93dc3a81226d981a861b8afe51e25d07538aded5.tgz
  "@lenso/scheduler": file:.artifacts/framework/lenso-scheduler-0.2.1-93dc3a81226d981a861b8afe51e25d07538aded5.tgz
  "@lenso/api-keys": file:.artifacts/framework/lenso-api-keys-0.1.2-93dc3a81226d981a861b8afe51e25d07538aded5.tgz
  "@lenso/limits": file:.artifacts/framework/lenso-limits-0.2.1-93dc3a81226d981a861b8afe51e25d07538aded5.tgz
  "@lenso/log": file:.artifacts/framework/lenso-log-0.2.1-93dc3a81226d981a861b8afe51e25d07538aded5.tgz
  "@lenso/otel": file:.artifacts/framework/lenso-otel-0.3.0-93dc3a81226d981a861b8afe51e25d07538aded5.tgz
  "@lenso/db": file:.artifacts/framework/lenso-db-0.1.2-93dc3a81226d981a861b8afe51e25d07538aded5.tgz

minimumReleaseAgeExclude:
  - vite@8.2.0
  - "@tanstack/history@1.162.1"
  - "@tanstack/react-router@1.170.21"
  - "@tanstack/react-start-client@1.168.19"
  - "@tanstack/react-start-rsc@0.1.37"
  - "@tanstack/react-start-server@1.167.26"
  - "@tanstack/react-start@1.168.38"
  - "@tanstack/router-core@1.171.18"
  - "@tanstack/router-generator@1.167.24"
  - "@tanstack/router-plugin@1.168.26"
  - "@tanstack/start-client-core@1.170.17"
  - "@tanstack/start-plugin-core@1.171.29"
  - "@tanstack/start-server-core@1.169.21"
  - "@tanstack/start-storage-context@1.167.20"
  - "@lenso/primitives@0.5.0"
  - "@lenso/tokens@0.9.1"
  - "@lenso/ui@0.9.1"
  - "@lenso/contract-runtime@0.3.1"
  - "@lenso/auth@0.2.0 || 0.3.0"
  - "@lenso/core@0.2.0"
  - "@lenso/engine@0.2.0"
  - "@lenso/manage@0.2.0"
  - "@lenso/web@0.2.0 || 0.3.0"
  - "@lenso/api-keys@0.1.1"
  - "@lenso/audit@0.2.0"
  - "@lenso/authorization@0.2.0"
  - "@lenso/limits@0.2.0"
  - "@lenso/log@0.2.1"
  - "@lenso/otel@0.3.0"
  - "@lenso/scheduler@0.2.0"
  - "@lenso/tasks@0.3.0"
