import * as stylex from "@stylexjs/stylex";

const fontFamily =
  '"Inter Variable", "SF Pro Display", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif';

export const agentQuickPanelStyles = stylex.create({
  assistantCopy: { margin: "12px 0 0 8px" },
  assistantTurn: { marginBottom: "12px" },
  attach: {
    borderColor: "transparent",
    borderRadius: "9999px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "none",
    color: "lch(40 1 282)",
    padding: "0 2px",
  },
  body: {
    backgroundColor: "lch(100 0 282)",
    borderRadius: "0 0 15.5px 15.5px",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    overflow: "hidden",
    position: "relative",
  },
  bodyEmpty: {
    backgroundImage: "linear-gradient(lch(96.5 0 282) 0%, lch(100 0 282) 100%)",
    backgroundPosition: "4px 0",
    backgroundRepeat: "no-repeat",
    backgroundSize: "calc(100% - 8px) calc(100% - 84.8px)",
  },
  chatChip: {
    backgroundColor: {
      default: "color-mix(in srgb, black 5%, transparent)",
      ":hover": "color-mix(in srgb, black 8%, transparent)",
    },
    borderRadius: "8px",
    borderWidth: 0,
    boxShadow: "none",
    color: "lch(37.776 1.25 282)",
    fontFamily,
    fontSize: "12px",
    fontWeight: 500,
    height: "28px",
    maxWidth: "160px",
    overflow: "hidden",
    paddingInline: "10px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  chatOptions: {
    borderColor: "transparent",
    borderRadius: "9999px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "none",
    color: "lch(40 1 282)",
    marginInlineStart: "8px",
    padding: "0 2px",
  },
  composer: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    margin: 0,
    minHeight: "72.8px",
    padding: "6px 4px",
    width: "100%",
  },
  composerActions: { gap: "8px" },
  composerDock: {
    marginTop: "auto",
    padding: "0 8px 8px",
    position: "relative",
    zIndex: 1,
  },
  composerFooter: {
    alignItems: "flex-end",
    display: "flex",
    gap: "8px",
    height: "28px",
    minHeight: "28px",
    padding: "0 6px 4px 2px",
    width: "100%",
  },
  composerSurface: {
    backgroundColor: "lch(100 0 282)",
    borderColor: "lch(91.9 0 282)",
    borderRadius: "7px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "0 3px 6px -2px lch(0 0 0 / 2%), 0 1px 1px lch(0 0 0 / 4%)",
    flex: "0 0 auto",
    height: "auto",
    margin: 0,
    padding: 0,
    position: "relative",
    width: "100%",
  },
  conversation: {
    color: "lch(20 1 282)",
    flex: "1 1 auto",
    fontSize: "13px",
    fontWeight: 450,
    lineHeight: "20.8px",
    minHeight: 0,
    overflowY: "auto",
    padding: "12px 8px 16px",
    position: "relative",
    scrollbarWidth: "thin",
    zIndex: 1,
  },
  conversationTime: {
    color: "lch(66 1 282)",
    display: "block",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "14.5px",
    marginBottom: "20px",
    textAlign: "center",
  },
  editingSlot: {
    display: "grid",
    gridTemplateRows: "0fr",
    opacity: 0,
    pointerEvents: "none",
    transition: {
      default:
        "grid-template-rows 160ms cubic-bezier(0.2, 0.8, 0.2, 1), opacity 120ms ease-in-out, visibility 0s linear 160ms",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    visibility: "hidden",
  },
  editingSlotContent: { minHeight: 0, overflow: "hidden" },
  editingSlotOpen: {
    gridTemplateRows: "1fr",
    opacity: 1,
    pointerEvents: "auto",
    transition: {
      default:
        "grid-template-rows 160ms cubic-bezier(0.2, 0.8, 0.2, 1), opacity 120ms ease-in-out, visibility 0s",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    visibility: "visible",
  },
  header: {
    alignItems: "center",
    backgroundColor: {
      default: "lch(100 0 282)",
      "@media (prefers-color-scheme: dark)": "var(--color-surface-panel)",
    },
    borderRadius: "11.5px 11.5px 0 0",
    display: "flex",
    padding: "0 6px 0 18px",
  },
  headerAction: {
    borderColor: "transparent",
    borderRadius: "9999px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "none",
    color: "lch(40 1 282)",
    padding: "0 2px",
  },
  headerActions: {
    alignItems: "center",
    display: "flex",
    gap: "2px",
    marginInlineStart: "auto",
  },
  inputWrapper: {
    borderRadius: "8px",
    margin: "0 -4px -4px",
    padding: "4px",
    position: "relative",
    zIndex: 0,
  },
  inputWrapperEditing: {
    backgroundImage: "linear-gradient(lch(96.5 0 282), lch(100 0 282))",
  },
  messageActions: {
    display: "flex",
    gap: "2px",
    height: "21px",
    marginTop: "5px",
    opacity: 1,
  },
  panel: {
    backgroundColor: {
      default: "lch(94.44 0.5 282)",
      "@media (prefers-color-scheme: dark)": "var(--color-surface-sidebar)",
    },
    borderColor: {
      default: "lch(89.84 0 282)",
      "@media (prefers-color-scheme: dark)": "var(--color-border-secondary)",
    },
    borderRadius: "12px 12px 16px 16px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    bottom: "34px",
    boxShadow:
      "0 6px 18px lch(0 0 0 / 2%), 0 3px 9px lch(0 0 0 / 4%), 0 1px 1px lch(0 0 0 / 4%)",
    display: { default: "grid", "@media (max-width: 760px)": "none" },
    fontFamily,
    gridTemplateRows: "48px minmax(0, 1fr)",
    height: "min(576px, calc(100dvh - 72px))",
    opacity: 1,
    overflow: "visible",
    padding: 0,
    position: "fixed",
    right: "32px",
    transform: "translateY(0) scale(1)",
    transformOrigin: "bottom right",
    transition: {
      default:
        "transform 160ms cubic-bezier(0.2, 0.8, 0.2, 1), opacity 120ms ease",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    width: "400px",
    zIndex: 90,
  },
  portal: { position: "relative", zIndex: 90 },
  quickTurn: { display: "grid" },
  skills: {
    borderColor: "transparent",
    borderRadius: "9999px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "none",
    color: "lch(40 1 282)",
    fontFamily: "inherit",
    fontSize: "12px",
    fontWeight: 500,
    gap: "6px",
    height: "24px",
    lineHeight: "normal",
    paddingInline: "4px 6px",
    width: "74px",
  },
  submit: {
    backgroundColor: {
      default: "lch(100 0 282)",
      ":hover": "var(--color-surface-interactive-hover)",
    },
    borderColor: "transparent",
    borderRadius: "12px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow:
      "0 0 0 0.5px lch(0 0 0 / 8.8%), 0 3px 6px -2px lch(0 0 0 / 2%), 0 1px 1px lch(0 0 0 / 4%)",
    color: "lch(20 1 282)",
    outline: { default: null, ":focus-visible": "0" },
    padding: "0 2px",
  },
  submitActive: {
    backgroundColor: {
      default: "lch(53 52.26 286.91)",
      ":hover": "lch(49 52.26 286.91)",
    },
    boxShadow: "0 3px 6px -2px lch(0 0 0 / 2%), 0 1px 1px lch(0 0 0 / 4%)",
    color: "lch(100 0 282)",
  },
  suggestion: {
    backgroundColor: {
      default: "lch(100 0 282)",
      ":hover": "var(--color-surface-interactive-hover)",
    },
    borderColor: "lch(0 0 0 / 8.8%)",
    borderRadius: "999px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "0 3px 6px -2px lch(0 0 0 / 2%), 0 1px 1px lch(0 0 0 / 4%)",
    color: "lch(10 0 282)",
    fontFamily: "inherit",
    fontSize: "13px",
    fontWeight: 450,
    gap: "6px",
    height: "28.5px",
    lineHeight: "15.5px",
    padding: "6px 10px",
  },
  suggestionLabel: {
    backgroundClip: "text",
    backgroundImage:
      "linear-gradient(to right, lch(20 1 282) 0%, lch(40 1 282) 45%, lch(20 1 282) 55%, lch(40 1 282) 100%)",
    backgroundPosition: "300% 50%",
    backgroundSize: "300% 100%",
    color: "transparent",
  },
  suggestions: {
    alignContent: "flex-start",
    display: "flex",
    flex: "0 0 65px",
    flexWrap: "wrap",
    gap: "8px",
    height: "65px",
    justifyContent: "center",
    margin: "0 16px 32px",
    position: "relative",
    width: "367px",
    zIndex: 1,
  },
  textarea: {
    "::placeholder": { color: "lch(66 1 282)", opacity: 1 },
    backgroundColor: "transparent",
    borderWidth: 0,
    boxSizing: "border-box",
    color: "lch(20 1 282)",
    fontFamily: "inherit",
    fontSize: "13px",
    fontWeight: 450,
    height: "24.796875px",
    lineHeight: "20.796875px",
    maxHeight: "124px",
    minHeight: "24.796875px",
    outlineStyle: "none",
    outlineWidth: 0,
    overflowY: "auto",
    padding: "2px 6px",
    resize: "none",
    scrollbarWidth: "thin",
    width: "375px",
  },
  title: {
    color: "lch(10 0 282)",
    fontFamily: "inherit",
    fontSize: "13px",
    fontWeight: 500,
    lineHeight: "normal",
    margin: 0,
  },
  trigger: {
    backgroundColor: {
      default: "transparent",
      ":hover": "color-mix(in srgb, black 4%, transparent)",
    },
    borderRadius: "8px",
    color: {
      default: "lch(37.776 1.25 282)",
      ":hover": "var(--color-content-primary)",
    },
    fontFamily,
    fontSize: "12px",
    fontWeight: 500,
    gap: "6px",
    paddingInline: "10px 12px",
    width: "77px",
  },
  triggerOpen: {
    backgroundColor: {
      default: "color-mix(in srgb, black 6%, transparent)",
      ":hover": "color-mix(in srgb, black 6%, transparent)",
    },
    color: "var(--color-content-primary)",
  },
  userMessage: {
    backgroundColor: "lch(96.5 0 282)",
    borderRadius: "8px",
    maxWidth: "281px",
    padding: "8px 12px",
    whiteSpace: "pre-wrap",
  },
  userTurn: {
    alignItems: "flex-end",
    display: "flex",
    flexDirection: "column",
    marginBottom: 0,
  },
  welcome: {
    alignItems: "center",
    color: "lch(10 0 282)",
    display: "flex",
    flex: "1 1 auto",
    flexDirection: "column",
    fontFamily: "inherit",
    fontSize: "13px",
    justifyContent: "flex-end",
    lineHeight: "20px",
    minHeight: 0,
    paddingBottom: "16px",
    position: "relative",
    zIndex: 1,
  },
  welcomeIcon: { display: "block", flex: "0 0 auto", marginBottom: "10px" },
  welcomeSubtitle: {
    color: "lch(40 1 282)",
    fontSize: "13px",
    fontWeight: 450,
    whiteSpace: "nowrap",
  },
  welcomeTitle: { fontWeight: 600, marginBottom: "4px" },
});
