import * as stylex from "@stylexjs/stylex";

export const chipGroup = stylex.defineMarker();

const fontFamily =
  '"Inter Variable", "SF Pro Display", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif';

export const agentQuickPanelStyles = stylex.create({
  chipGroup: { position: "relative", display: "flex", minWidth: 0 },
  chipClose: {
    position: "absolute",
    right: "4px",
    top: "4px",
    width: "20px",
    height: "20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
    borderWidth: 0,
    borderRadius: "6px",
    cursor: "pointer",
    color: "var(--color-content-secondary)",
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--color-surface-interactive-hover)",
    },
    opacity: {
      default: 0,
      [stylex.when.ancestor(":hover", chipGroup)]: 1,
      [stylex.when.ancestor(":focus-within", chipGroup)]: 1,
      "@media (hover: none)": 1,
    },
  },
  panelContent: {
    display: "grid",
    gridTemplateRows: "48px minmax(0, 1fr)",
    height: "100%",
    minHeight: 0,
  },
  assistantCopy: { margin: "12px 0 0 8px" },
  assistantTurn: { fontSize: "14px", lineHeight: "22px", marginBottom: "12px" },
  attach: {
    borderColor: "transparent",
    borderRadius: "9999px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "none",
    color: "var(--color-content-secondary)",
    padding: "0 2px",
  },
  body: {
    backgroundColor: "var(--color-surface-panel)",
    borderRadius: "0 0 15.5px 15.5px",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    overflow: "visible",
    position: "relative",
  },
  bodyEmpty: {
    backgroundImage:
      "linear-gradient(var(--color-surface-subtle), var(--color-surface-panel))",
    backgroundPosition: "4px 0",
    backgroundRepeat: "no-repeat",
    backgroundSize: "calc(100% - 8px) calc(100% - 84.8px)",
  },
  chatChip: {
    backgroundColor: {
      default: "var(--color-surface-subtle)",
      ":hover": "var(--color-surface-interactive-hover)",
    },
    borderRadius: "8px",
    borderWidth: 0,
    boxShadow: "none",
    color: "var(--color-content-secondary)",
    fontFamily,
    fontSize: "12px",
    fontWeight: 500,
    height: "28px",
    maxWidth: "160px",
    overflow: "hidden",
    paddingInline: "10px 28px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  chatOptions: {
    borderColor: "transparent",
    borderRadius: "9999px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "none",
    color: "var(--color-content-secondary)",
    marginInlineStart: "8px",
    padding: "0 2px",
  },
  composer: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    margin: 0,
    minHeight: "72.8px",
    padding: "6px 4px",
    width: "100%",
  },
  composerActions: { gap: "8px" },
  composerDock: {
    marginTop: "auto",
    padding: "0 8px 8px",
    position: "relative",
    zIndex: 1,
  },
  composerFooter: {
    alignItems: "flex-end",
    display: "flex",
    gap: "8px",
    height: "28px",
    minHeight: "28px",
    padding: "0 6px 4px 2px",
    width: "100%",
  },
  composerSurface: {
    overflow: "visible",
    backgroundColor: "var(--color-surface-panel)",
    borderColor: "var(--color-border-secondary)",
    borderRadius: "7px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "0 3px 6px -2px lch(0 0 0 / 2%), 0 1px 1px lch(0 0 0 / 4%)",
    flex: "0 0 auto",
    height: "auto",
    margin: 0,
    padding: 0,
    position: "relative",
    width: "100%",
  },
  conversation: {
    color: "var(--color-content-primary)",
    flex: "1 1 auto",
    fontSize: "13px",
    fontWeight: 450,
    lineHeight: "20.8px",
    minHeight: 0,
    overflowY: "auto",
    padding: "12px 8px 16px",
    position: "relative",
    scrollbarWidth: "thin",
    zIndex: 1,
  },
  conversationTime: {
    color: "var(--color-content-tertiary)",
    display: "block",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "14.5px",
    marginBottom: "20px",
    textAlign: "center",
  },
  editingSlot: {
    display: "grid",
    gridTemplateRows: "0fr",
    opacity: 0,
    pointerEvents: "none",
    transition: {
      default:
        "grid-template-rows 160ms cubic-bezier(0.2, 0.8, 0.2, 1), opacity 120ms ease-in-out, visibility 0s linear 160ms",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    visibility: "hidden",
  },
  editingSlotContent: { minHeight: 0, overflow: "hidden" },
  editingSlotOpen: {
    gridTemplateRows: "1fr",
    opacity: 1,
    pointerEvents: "auto",
    transition: {
      default:
        "grid-template-rows 160ms cubic-bezier(0.2, 0.8, 0.2, 1), opacity 120ms ease-in-out, visibility 0s",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    visibility: "visible",
  },
  header: {
    alignItems: "center",
    backgroundColor: "var(--color-surface-panel)",
    borderRadius: "11.5px 11.5px 0 0",
    display: "flex",
    padding: "0 6px 0 18px",
  },
  headerAction: {
    borderColor: "transparent",
    borderRadius: "9999px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "none",
    color: "var(--color-content-secondary)",
    padding: "0 2px",
  },
  headerActions: {
    alignItems: "center",
    display: "flex",
    gap: "2px",
    marginInlineStart: "auto",
  },
  inputWrapper: {
    borderRadius: "8px",
    margin: "0 -4px -4px",
    padding: "4px",
    position: "relative",
    zIndex: 0,
  },
  inputWrapperEditing: {
    backgroundImage:
      "linear-gradient(var(--color-surface-subtle), var(--color-surface-panel))",
  },
  messageActions: {
    display: "flex",
    gap: "2px",
    height: "21px",
    marginTop: "5px",
    opacity: 1,
  },
  panel: {
    backgroundColor: "var(--color-surface-panel)",
    borderColor: "var(--color-border-secondary)",
    borderRadius: "12px 12px 16px 16px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    bottom: "34px",
    boxShadow:
      "0 6px 18px lch(0 0 0 / 2%), 0 3px 9px lch(0 0 0 / 4%), 0 1px 1px lch(0 0 0 / 4%)",
    display: "grid",
    fontFamily,

    height: "min(576px, calc(100dvh - 72px))",
    opacity: 1,
    overflow: "visible",
    padding: 0,
    position: "fixed",
    left: 0,
    right: "auto",
    transform: "translateY(0) scale(1)",
    transformOrigin: "bottom right",
    transitionProperty: "transform, opacity",
    transitionDuration: {
      default: "160ms, 120ms",
      "@media (prefers-reduced-motion: reduce)": "0s",
    },
    transitionTimingFunction: "cubic-bezier(0.2, 0.8, 0.2, 1), ease",
    width: "min(400px, calc(100vw - 24px))",
    zIndex: 90,
  },
  portal: { position: "relative", zIndex: 90 },
  quickTurn: { display: "grid" },
  skills: {
    borderColor: "transparent",
    borderRadius: "9999px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "none",
    color: "var(--color-content-secondary)",
    fontFamily: "inherit",
    fontSize: "12px",
    fontWeight: 500,
    gap: "6px",
    height: "24px",
    lineHeight: "normal",
    paddingInline: "4px 6px",
    width: "74px",
  },
  submit: {
    backgroundColor: {
      default: "var(--color-surface-panel)",
      ":hover": "var(--color-surface-interactive-hover)",
    },
    borderColor: "transparent",
    borderRadius: "12px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow:
      "0 0 0 0.5px lch(0 0 0 / 8.8%), 0 3px 6px -2px lch(0 0 0 / 2%), 0 1px 1px lch(0 0 0 / 4%)",
    color: "var(--color-content-primary)",
    outline: { default: null, ":focus-visible": "0" },
    padding: "0 2px",
  },
  submitActive: {
    backgroundColor: {
      default: "lch(53 52.26 286.91)",
      ":hover": "lch(49 52.26 286.91)",
    },
    boxShadow: "0 3px 6px -2px lch(0 0 0 / 2%), 0 1px 1px lch(0 0 0 / 4%)",
    color: "white",
  },
  suggestion: {
    backgroundColor: {
      default: "var(--color-surface-panel)",
      ":hover": "var(--color-surface-interactive-hover)",
    },
    borderColor: "var(--color-border-secondary)",
    borderRadius: "999px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "0 3px 6px -2px lch(0 0 0 / 2%), 0 1px 1px lch(0 0 0 / 4%)",
    color: "var(--color-content-primary)",
    fontFamily: "inherit",
    fontSize: "13px",
    fontWeight: 450,
    gap: "6px",
    height: "28.5px",
    lineHeight: "15.5px",
    padding: "6px 10px",
  },
  suggestionLabel: { color: "var(--color-content-secondary)" },
  suggestions: {
    alignContent: "flex-start",
    display: "flex",
    flex: "0 0 65px",
    flexWrap: "wrap",
    gap: "8px",
    height: "65px",
    justifyContent: "center",
    margin: "0 16px 32px",
    position: "relative",
    width: "auto",
    zIndex: 1,
  },
  textarea: {
    "::placeholder": { color: "var(--color-content-tertiary)", opacity: 1 },
    backgroundColor: "transparent",
    borderWidth: 0,
    boxSizing: "border-box",
    color: "var(--color-content-primary)",
    fontFamily: "inherit",
    fontSize: "13px",
    fontWeight: 450,
    height: "24.796875px",
    lineHeight: "20.796875px",
    maxHeight: "124px",
    minHeight: "24.796875px",
    outlineStyle: "none",
    outlineWidth: 0,
    overflowY: "auto",
    padding: "2px 6px",
    resize: "none",
    scrollbarWidth: "thin",
    width: "100%",
  },
  title: {
    color: "var(--color-content-primary)",
    fontFamily: "inherit",
    fontSize: "13px",
    fontWeight: 500,
    lineHeight: "normal",
    margin: 0,
  },
  trigger: {
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--color-surface-interactive-hover)",
    },
    borderRadius: "8px",
    color: {
      default: "var(--color-content-secondary)",
      ":hover": "var(--color-content-primary)",
    },
    fontFamily,
    fontSize: "12px",
    fontWeight: 500,
    gap: "6px",
    paddingInline: "10px 12px",
    width: "77px",
  },
  triggerOpen: {
    backgroundColor: {
      default: "var(--color-surface-interactive-hover)",
      ":hover": "var(--color-surface-interactive-hover)",
    },
    color: "var(--color-content-primary)",
  },
  userMessage: {
    backgroundColor: "var(--color-surface-subtle)",
    borderRadius: "8px",
    maxWidth: "281px",
    padding: "8px 12px",
    whiteSpace: "pre-wrap",
  },
  userTurn: {
    alignItems: "flex-end",
    display: "flex",
    flexDirection: "column",
    marginBottom: 0,
  },
  welcome: {
    alignItems: "center",
    color: "var(--color-content-primary)",
    display: "flex",
    flex: "1 1 auto",
    flexDirection: "column",
    fontFamily: "inherit",
    fontSize: "13px",
    justifyContent: "flex-end",
    lineHeight: "20px",
    minHeight: 0,
    paddingBottom: "16px",
    position: "relative",
    zIndex: 1,
  },
  welcomeIcon: { display: "block", flex: "0 0 auto", marginBottom: "10px" },
  welcomeSubtitle: {
    color: "var(--color-content-secondary)",
    fontSize: "13px",
    fontWeight: 450,
    whiteSpace: "nowrap",
  },
  welcomeTitle: { fontWeight: 600, marginBottom: "4px" },
});
