import * as stylex from "@stylexjs/stylex";

export const composerInputStyles = stylex.create({
  root: { position: "relative", minWidth: 0 },
  menu: {
    position: "absolute",
    bottom: "calc(100% + 8px)",
    insetInline: 0,
    zIndex: 30,
    maxHeight: "min(360px, 50vh)",
    overflowY: "auto",
    overscrollBehavior: "contain",
    backgroundColor: "var(--color-surface-panel)",
    border: "1px solid var(--color-border-secondary)",
    borderRadius: "12px",
    boxShadow: "0 8px 28px rgb(0 0 0 / 12%)",
    padding: "6px",
  },
  menuHint: {
    display: "flex",
    justifyContent: "space-between",
    gap: "8px",
    padding: "6px 8px",
    fontSize: "10px",
    color: "var(--color-content-tertiary)",
  },
  group: {
    padding: "10px 8px 4px",
    fontSize: "10px",
    fontWeight: 500,
    color: "var(--color-content-tertiary)",
  },
  entry: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    width: "100%",
    textAlign: "start",
    border: 0,
    borderRadius: "7px",
    backgroundColor: {
      default: "transparent",
      ':is([data-active="true"])': "var(--color-surface-selected)",
    },
    color: "var(--color-content-primary)",
    padding: "7px 8px",
    cursor: "pointer",
    fontSize: "12px",
  },
  icon: { flexShrink: 0 },
  entryText: {
    flex: 1,
    display: "flex",
    alignItems: "baseline",
    gap: "8px",
    overflow: "hidden",
    minWidth: 0,
    overflowWrap: "anywhere",
  },
  entryLabel: { flexShrink: 0 },
  entryDescription: {
    color: "var(--color-content-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: "11px",
  },
  close: {
    display: "grid",
    placeItems: "center",
    border: 0,
    padding: "2px",
    backgroundColor: "transparent",
    color: "inherit",
    cursor: "pointer",
    borderRadius: "4px",
  },
  empty: {
    padding: "12px",
    fontSize: "12px",
    color: "var(--color-content-secondary)",
  },
  references: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
    padding: "8px 12px 0",
  },
  reference: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    borderRadius: "6px",
    padding: "3px 6px",
    backgroundColor: "var(--color-surface-selected)",
    fontSize: "11px",
    maxWidth: "100%",
    overflowWrap: "anywhere",
  },
  notice: {
    display: "flex",
    justifyContent: "space-between",
    gap: "8px",
    margin: "4px 12px",
    fontSize: "11px",
    color: "var(--color-content-secondary)",
  },
});
