import * as stylex from "@stylexjs/stylex";

export const agentSettingsStyles = stylex.create({
  backLink: {
    alignItems: "center",
    color: "var(--color-content-tertiary)",
    display: "inline-flex",
    fontSize: "12px",
    gap: "6px",
    marginBottom: "24px",
  },
  contentColumn: {
    margin: "0 auto",
    padding: {
      default: "64px 0 80px",
      "@media (max-width: 640px)": "56px 0 80px",
    },
    width: {
      default: "min(640px, calc(100% - 48px))",
      "@media (max-width: 900px)": "calc(100% - 32px)",
      "@media (max-width: 640px)": "calc(100% - 24px)",
    },
  },
  editorActions: {
    display: "flex",
    gap: "8px",
    justifyContent: "flex-end",
    marginTop: "16px",
  },
  featureList: {
    borderColor: "var(--color-border-tertiary)",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "none",
  },
  featureRow: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--color-surface-interactive-hover)",
    },
    borderBottomColor: "var(--color-border-tertiary)",
    borderBottomStyle: "solid",
    borderBottomWidth: { default: "0.5px", ":last-child": 0 },
    boxSizing: "border-box",
    color: "inherit",
    display: "grid",
    gap: "10px",
    gridTemplateColumns: {
      default: "auto minmax(0, 1fr) auto auto",
      "@media (max-width: 640px)": "auto minmax(0, 1fr) auto",
    },
    minHeight: "65px",
    padding: "10px 16px",
    width: "100%",
  },
  featureRowDisabled: {
    backgroundColor: { default: "transparent", ":hover": "transparent" },
    opacity: 0.5,
  },
  guidance: {
    backgroundColor: "var(--color-surface-panel)",
    borderColor: "var(--color-border-tertiary)",
    borderRadius: "9px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    color: "var(--color-content-primary)",
    font: "inherit",
    fontSize: "12px",
    lineHeight: "19px",
    minHeight: "150px",
    outline: "none",
    padding: "14px",
    resize: "vertical",
    width: "100%",
  },
  noTools: {
    borderTopColor: "var(--color-border-tertiary)",
    borderTopStyle: "solid",
    borderTopWidth: "0.5px",
    color: "var(--color-content-tertiary)",
    fontSize: "12px",
    lineHeight: "18px",
    margin: 0,
    padding: "10px 16px",
  },
  page: {
    color: "var(--color-content-primary)",
    minHeight: "100%",
    overflowY: "auto",
    width: "100%",
  },
  rowCopy: { display: "block" },
  rowDescription: {
    color: "var(--color-content-tertiary)",
    display: "block",
    fontSize: "12px",
    fontWeight: 400,
    lineHeight: "18px",
  },
  rowStatus: {
    color: "var(--color-content-tertiary)",
    display: { default: "block", "@media (max-width: 640px)": "none" },
    fontSize: "11px",
    fontStyle: "normal",
  },
  rowTitle: {
    display: "block",
    fontSize: "13px",
    fontWeight: 500,
    lineHeight: "19.5px",
  },
  rowWithIcon: {
    alignItems: "center",
    display: "flex",
    gap: "10px",
    minWidth: 0,
  },
  sectionDescription: {
    color: "var(--color-content-tertiary)",
    fontSize: "12px",
    lineHeight: "18px",
    margin: "0 16px",
  },
  sectionHeader: { gap: "2px", marginBottom: "12px" },
  sectionHeading: { marginBottom: "32px" },
  sectionHeadingDescription: {
    color: "var(--color-content-tertiary)",
    fontSize: "12px",
    lineHeight: "18px",
    margin: "2px 16px 0",
  },
  sectionHeadingTitle: {
    fontSize: "24px",
    fontWeight: 500,
    letterSpacing: "-0.02em",
    lineHeight: "32px",
    margin: "0 16px",
  },
  sectionRoot: { gap: 0, marginTop: "32px" },
  sectionRootFollowing: { marginTop: "48px" },
  sectionTitle: {
    fontSize: "15px",
    fontWeight: 520,
    lineHeight: "20px",
    margin: "0 16px",
  },
  singleRow: {
    backgroundColor: {
      default: null,
      ":hover": "var(--color-surface-interactive-hover)",
    },
    borderColor: "var(--color-border-tertiary)",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "none",
    fontSize: "13px",
    minHeight: "65px",
    padding: "10px 16px",
  },
  singleRowInner: {
    alignItems: "center",
    display: "flex",
    gap: "16px",
    justifyContent: "space-between",
    width: "100%",
  },
  skillEditor: { paddingTop: "24px" },
  skillInstructions: {
    backgroundColor: "var(--color-surface-panel)",
    borderColor: "var(--color-border-tertiary)",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    color: "var(--color-content-primary)",
    font: "inherit",
    fontSize: "12px",
    lineHeight: "19px",
    marginTop: "18px",
    minHeight: "272px",
    outline: "none",
    padding: "14px",
    resize: "vertical",
    width: "100%",
  },
  skillName: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "var(--color-content-primary)",
    font: "inherit",
    fontSize: "24px",
    fontWeight: 500,
    letterSpacing: "-0.02em",
    lineHeight: "32px",
    outline: 0,
    padding: "0 16px",
    width: "100%",
  },
  summaryCards: { display: "grid", gap: "8px" },
  toolCode: {
    color: "var(--color-content-primary)",
    display: "block",
    fontFamily: "var(--font-family-mono, monospace)",
    fontSize: "12px",
    lineHeight: "18px",
  },
  toolDescription: {
    color: "var(--color-content-tertiary)",
    display: "block",
    fontSize: "11px",
    fontStyle: "normal",
    lineHeight: "16px",
  },
  toolList: {
    borderTopColor: "var(--color-border-tertiary)",
    borderTopStyle: "solid",
    borderTopWidth: "0.5px",
    boxSizing: "border-box",
    display: "grid",
    gap: 0,
    listStyle: "none",
    margin: 0,
    padding: 0,
    width: "100%",
  },
  toolListRow: {
    alignItems: "center",
    borderBottomColor: "var(--color-border-tertiary)",
    borderBottomStyle: "solid",
    borderBottomWidth: { default: "0.5px", ":last-child": 0 },
    display: "grid",
    gap: "16px",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    padding: "10px 16px",
  },
  toolPolicy: {
    borderColor: "var(--color-border-tertiary)",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "none",
  },
  toolPolicyError: {
    borderTopColor: "var(--color-border-tertiary)",
    borderTopStyle: "solid",
    borderTopWidth: "0.5px",
    color: "var(--color-danger-content, #b42318)",
    fontSize: "12px",
    lineHeight: "18px",
    margin: 0,
    padding: "9px 16px",
  },
  toolPolicySummary: { minHeight: "64px", padding: "12px 16px" },
});
