import * as stylex from "@stylexjs/stylex";

export const agentMarkdownStyles = stylex.create({
  blockquote: {
    borderInlineStartColor: "var(--color-border-secondary)",
    borderInlineStartStyle: "solid",
    borderInlineStartWidth: "2px",
    color: "var(--color-content-secondary)",
    margin: "8px 0 12px",
    padding: "2px 0 2px 12px",
  },
  codeBlock: {
    fontFamily: "var(--font-mono)",
    fontSize: "12px",
    lineHeight: "19px",
    margin: 0,
    maxWidth: "100%",
    overflowX: "auto",
    tabSize: 2,
    whiteSpace: "pre",
  },
  compact: { paddingInlineStart: "10px" },
  content: {
    color: "inherit",
    font: "inherit",
    lineHeight: "inherit",
    minWidth: 0,
    overflowWrap: "anywhere",
  },
  heading: {
    color: "var(--color-content-primary)",
    fontWeight: 600,
    lineHeight: 1.35,
    marginBottom: "8px",
    marginTop: { default: "18px", ":first-child": 0 },
  },
  heading1: {
    fontSize: { default: "20px", "@media (max-width: 720px)": "18px" },
  },
  heading2: { fontSize: "17px" },
  heading3: { fontSize: "15px" },
  headingSmall: { fontSize: "14px" },
  horizontalRule: {
    backgroundColor: "var(--color-border-tertiary)",
    borderWidth: 0,
    height: "1px",
    margin: "16px 0",
  },
  image: {
    borderRadius: "8px",
    display: "block",
    height: "auto",
    margin: "8px 0 14px",
    maxWidth: "100%",
  },
  inlineCode: {
    backgroundColor: "var(--color-surface-subtle)",
    borderColor: "var(--color-border-tertiary)",
    borderRadius: "4px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--color-content-primary)",
    fontFamily: "var(--font-mono)",
    fontSize: "0.88em",
    padding: "1px 4px",
  },
  link: {
    color: "var(--color-content-link, var(--color-action-primary))",
    textDecoration: "underline",
    textDecorationColor: {
      default: "color-mix(in srgb, currentcolor 42%, transparent)",
      ":hover": "currentcolor",
    },
    textUnderlineOffset: "2px",
  },
  list: { margin: "4px 0 12px", paddingInlineStart: "22px" },
  listItem: {
    marginTop: { default: 0, ":not(:first-child)": "4px" },
    paddingInlineStart: "2px",
  },
  orderedList: { listStyle: "decimal" },
  paragraph: {
    marginBottom: { default: "12px", ":last-child": 0 },
    marginTop: 0,
  },
  strong: { color: "var(--color-content-primary)", fontWeight: 600 },
  table: { borderCollapse: "collapse", fontSize: "13px", width: "100%" },
  tableCell: {
    borderBottomColor: "var(--color-border-tertiary)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    borderInlineEndColor: "var(--color-border-tertiary)",
    borderInlineEndStyle: "solid",
    borderInlineEndWidth: { default: "1px", ":last-child": 0 },
    minWidth: "96px",
    padding: "8px 10px",
    textAlign: "left",
    verticalAlign: "top",
  },
  tableHeader: {
    backgroundColor: "var(--color-surface-subtle)",
    color: "var(--color-content-secondary)",
    fontWeight: 550,
  },
  tableWrapper: {
    borderColor: "var(--color-border-tertiary)",
    borderRadius: "8px",
    borderStyle: "solid",
    borderWidth: "1px",
    margin: "8px 0 14px",
    maxWidth: "100%",
    overflowX: "auto",
  },
  taskCheckbox: {
    accentColor: "var(--color-action-primary)",
    margin: "0 7px 0 -1px",
  },
  unorderedList: { listStyle: "disc" },
  linkDialog: {
    display: "grid",
    gap: "12px",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    padding: "16px",
    width: "min(440px, calc(100vw - 32px))",
  },
  linkDialogActions: {
    display: "flex",
    gap: "6px",
    gridColumn: "1 / -1",
    justifyContent: "flex-end",
    marginTop: "2px",
  },
  linkDialogContent: { minWidth: 0 },
  linkDialogDescription: {
    color: "var(--color-content-secondary)",
    fontSize: "12px",
    lineHeight: "18px",
    margin: 0,
  },
  linkDialogIcon: {
    borderColor: "var(--color-border-tertiary)",
    borderRadius: "8px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--color-content-secondary)",
    display: "grid",
    height: "30px",
    placeItems: "center",
    width: "30px",
  },
  linkDialogTitle: {
    color: "var(--color-content-primary)",
    fontSize: "14px",
    fontWeight: 600,
    margin: "1px 0 4px",
  },
  linkDestination: {
    backgroundColor: "var(--color-surface-subtle)",
    borderColor: "var(--color-border-tertiary)",
    borderRadius: "6px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--color-content-secondary)",
    display: "block",
    fontFamily: "var(--font-mono)",
    fontSize: "11px",
    marginTop: "10px",
    overflow: "hidden",
    padding: "7px 9px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
});
