import * as stylex from "@stylexjs/stylex";

export const profilesPageStyles = stylex.create({
  description: {
    margin: 0,
    color: "var(--color-content-tertiary)",
    fontSize: 12,
    lineHeight: "19px",
    overflowWrap: "anywhere",
  },
  toolbar: {
    marginBlockStart: 32,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    marginBlockEnd: 12,
  },
  list: { padding: 0, margin: 0, listStyle: "none", display: "grid" },
  row: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 16,
    paddingBlock: 18,
    borderBottom: "1px solid var(--color-border-tertiary)",
  },
  profileLink: {
    display: "grid",
    gap: 6,
    flex: "1 1 280px",
    minWidth: 0,
    color: "inherit",
    textDecoration: "none",
    borderRadius: 8,
    ":hover": { backgroundColor: "var(--color-surface-interactive-hover)" },
  },
  nameRow: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: 8 },
  name: {
    fontSize: 14,
    lineHeight: "22px",
    fontWeight: 500,
    overflowWrap: "anywhere",
  },
  badge: {
    fontSize: 11,
    lineHeight: "18px",
    color: "var(--color-content-secondary)",
    backgroundColor: "var(--color-surface-subtle)",
    borderRadius: 999,
    padding: "1px 7px",
  },
  actions: { display: "flex", gap: 8, marginInlineStart: "auto" },
  breadcrumb: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    fontSize: 12,
    color: "var(--color-content-tertiary)",
  },
  guard: {
    position: "sticky",
    top: 0,
    zIndex: 5,
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
    backgroundColor: "var(--color-surface-panel)",
    padding: 16,
    borderRadius: 12,
    border: "1px solid var(--color-border-tertiary)",
    marginBlockStart: 16,
    fontSize: 13,
  },
});
