import * as stylex from "@stylexjs/stylex";

export const chipGroup = stylex.defineMarker();

const fontFamily =
  '"Inter Variable", "SF Pro Display", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif';

export const agentQuickPanelStyles = stylex.create({
  chipGroup: { position: "relative", display: "flex", minWidth: 0 },
  chipClose: {
    position: "absolute",
    right: "4px",
    top: "4px",
    width: "20px",
    height: "20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
    borderWidth: 0,
    minWidth: "20px",
    cursor: "pointer",
    color: "var(--muted)",
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--default-hover)",
    },
    opacity: {
      default: 0,
      [stylex.when.ancestor(":hover", chipGroup)]: 1,
      [stylex.when.ancestor(":focus-within", chipGroup)]: 1,
      "@media (hover: none)": 1,
    },
  },
  panelContent: {
    display: "grid",
    gridTemplateRows: "48px minmax(0, 1fr)",
    height: "100%",
    minHeight: 0,
  },
  assistantCopy: { margin: "12px 0 0 8px" },
  assistantTurn: { fontSize: "14px", lineHeight: "22px", marginBottom: "12px" },
  attach: {
    borderColor: "transparent",
    borderRadius: "9999px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "none",
    color: "var(--muted)",
    padding: "0 2px",
  },
  body: {
    backgroundColor: "var(--background)",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    overflow: "visible",
    position: "relative",
  },
  chatChip: {
    backgroundColor: {
      default: "var(--surface-secondary)",
      ":hover": "var(--default-hover)",
    },
    borderRadius: "8px",
    borderWidth: 0,
    boxShadow: "none",
    color: "var(--muted)",
    fontFamily,
    fontSize: "12px",
    fontWeight: 500,
    height: "28px",
    maxWidth: "160px",
    overflow: "hidden",
    paddingInline: "10px 28px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  chatOptions: {
    borderColor: "transparent",
    borderRadius: "9999px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "none",
    color: "var(--muted)",
    marginInlineStart: "8px",
    padding: "0 2px",
  },
  composer: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    margin: 0,
    minHeight: "72.8px",
    padding: "6px 4px",
    width: "100%",
  },
  composerActions: { gap: "8px" },
  composerLeading: {
    alignItems: "center",
    display: "flex",
    flex: "1 1 auto",
    gap: "4px",
    minWidth: 0,
  },
  composerDock: {
    marginTop: "auto",
    padding: "0 8px 8px",
    position: "relative",
    zIndex: 1,
  },
  composerFooter: {
    alignItems: "center",
    display: "flex",
    gap: "8px",
    minHeight: "27px",
    padding: "0 4px 0 2px",
    width: "100%",
  },
  composerSurface: {
    overflow: "visible",
    backgroundColor: "var(--field-background)",
    borderColor: "var(--border)",
    borderRadius: "14px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "none",
    flex: "0 0 auto",
    height: "auto",
    margin: 0,
    padding: 0,
    position: "relative",
    width: "100%",
  },
  conversation: {
    color: "var(--foreground)",
    flex: "1 1 auto",
    fontSize: "13px",
    fontWeight: 450,
    lineHeight: "20.8px",
    minHeight: 0,
    overflowY: "auto",
    padding: "12px 8px 16px",
    position: "relative",
    scrollbarWidth: "thin",
    zIndex: 1,
  },
  conversationTime: {
    color: "var(--muted)",
    display: "block",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "14.5px",
    marginBottom: "20px",
    textAlign: "center",
  },
  editingSlot: {
    display: "grid",
    gridTemplateRows: "0fr",
    opacity: 0,
    pointerEvents: "none",
    transition: {
      default:
        "grid-template-rows 160ms cubic-bezier(0.2, 0.8, 0.2, 1), opacity 120ms ease-in-out, visibility 0s linear 160ms",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    visibility: "hidden",
  },
  editingSlotContent: { minHeight: 0, overflow: "hidden" },
  editingSlotOpen: {
    gridTemplateRows: "1fr",
    opacity: 1,
    pointerEvents: "auto",
    transition: {
      default:
        "grid-template-rows 160ms cubic-bezier(0.2, 0.8, 0.2, 1), opacity 120ms ease-in-out, visibility 0s",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    visibility: "visible",
  },
  header: {
    alignItems: "center",
    backgroundColor: "var(--background)",
    borderBottomColor: "var(--separator)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    padding: "0 6px 0 15px",
  },
  drawerAccent: { color: "var(--console-assistant-accent, #b9b5ff)" },
  headerAction: {
    borderColor: "transparent",
    borderRadius: "9999px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "none",
    color: "var(--muted)",
    padding: "0 2px",
  },
  headerActions: {
    alignItems: "center",
    display: "flex",
    gap: "2px",
    marginInlineStart: "auto",
  },
  inputWrapper: {
    borderRadius: "8px",
    margin: "0 -4px -4px",
    padding: "4px",
    position: "relative",
    zIndex: 0,
  },
  inputWrapperEditing: {
    backgroundColor: "var(--field-background)",
  },
  messageActions: {
    display: "flex",
    gap: "2px",
    height: "21px",
    marginTop: "5px",
    opacity: 1,
  },
  panel: {
    backgroundColor: "var(--background)",
    borderInlineStartColor: "var(--border)",
    borderInlineStartStyle: "solid",
    borderInlineStartWidth: "1px",
    borderRadius: 0,
    boxShadow: "-12px 0 30px rgb(0 0 0 / 22%)",
    display: "grid",
    fontFamily,
    height: "auto",
    opacity: 1,
    overflow: "visible",
    padding: 0,
    position: "fixed",
    bottom: 0,
    right: 0,
    top: { default: "54px", "@media (max-width: 720px)": "90px" },
    transform: "none",
    transition: "none",
    width: "min(340px, 100vw)",
    zIndex: 90,
    "[data-starting-style]": { opacity: 1, transform: "none" },
    "[data-ending-style]": { opacity: 0, transform: "none" },
  },
  panelWithTray: {
    top: { default: "88px", "@media (max-width: 720px)": "124px" },
  },
  portal: { position: "relative", zIndex: 90 },
  quickTurn: { display: "grid" },
  skills: {
    borderColor: "transparent",
    borderRadius: "9999px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "none",
    color: "var(--muted)",
    fontFamily: "inherit",
    fontSize: "12px",
    fontWeight: 500,
    gap: "6px",
    height: "24px",
    lineHeight: "normal",
    paddingInline: "4px 6px",
    width: "74px",
  },
  submit: {
    backgroundColor: {
      default: "var(--surface)",
      ":hover": "var(--default-hover)",
    },
    borderColor: "transparent",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "none",
    color: "var(--foreground)",
    outline: { default: null, ":focus-visible": "0" },
    padding: "0 2px",
  },
  submitActive: {
    backgroundColor: {
      default: "var(--foreground)",
      ":hover": "var(--muted)",
    },
    color: "var(--background)",
  },
  textarea: {
    "::placeholder": { color: "var(--muted)", opacity: 1 },
    backgroundColor: "transparent",
    borderWidth: 0,
    boxSizing: "border-box",
    color: "var(--foreground)",
    fontFamily: "inherit",
    fontSize: "13px",
    fontWeight: 450,
    height: "24.796875px",
    lineHeight: "20.796875px",
    maxHeight: "124px",
    minHeight: "24.796875px",
    outlineStyle: "none",
    outlineWidth: 0,
    overflowY: "auto",
    padding: "2px 6px",
    resize: "none",
    scrollbarWidth: "thin",
    width: "100%",
  },
  title: {
    alignItems: "center",
    color: "var(--foreground)",
    display: "flex",
    fontFamily: "inherit",
    fontSize: "13px",
    fontWeight: 600,
    gap: "8px",
    lineHeight: "normal",
    margin: 0,
  },
  historyTrigger: {
    position: "fixed",
    right: { default: "128px", "@media (max-width: 720px)": "56px" },
    bottom: "16px",
    zIndex: 80,
  },
  trigger: {
    bottom: "16px",
    right: "16px",
    position: "fixed",
    zIndex: 80,
    backgroundColor: {
      default:
        "var(--console-navigation-selected, var(--transparent-selected))",
      ":hover":
        "var(--console-navigation-selected, var(--transparent-selected))",
    },
    boxShadow: "none",
    color: "var(--foreground)",
    fontFamily: "inherit",
    fontSize: "13.5px",
    fontWeight: 400,
    gap: "7px",
    height: "32px",
    paddingInline: "10px",
    width: "auto",
    "@media (max-width: 720px)": {
      height: "32px",
      justifyContent: "center",
      padding: 0,
      width: "32px",
    },
  },
  triggerIcon: { color: "var(--foreground)" },
  triggerLabel: { "@media (max-width: 720px)": { display: "none" } },
  tray: {
    bottom: "60px",
    display: "flex",
    gap: "4px",
    maxWidth: "calc(100vw - 24px)",
    overflowX: "auto",
    padding: "2px",
    position: "fixed",
    right: "12px",
    zIndex: 50,
  },
  trayOpen: {
    backgroundColor: "var(--background)",
    borderInlineStartColor: "var(--border)",
    borderInlineStartStyle: "solid",
    borderInlineStartWidth: "1px",
    bottom: "auto",
    boxSizing: "border-box",
    height: "34px",
    right: 0,
    top: { default: "54px", "@media (max-width: 720px)": "90px" },
    width: "min(340px, 100vw)",
    zIndex: 100,
  },
  userMessage: {
    backgroundColor: "var(--surface-secondary)",
    borderRadius: "8px",
    maxWidth: "281px",
    padding: "8px 12px",
    whiteSpace: "pre-wrap",
  },
  userTurn: {
    alignItems: "flex-end",
    display: "flex",
    flexDirection: "column",
    marginBottom: 0,
  },
  welcome: {
    color: "var(--muted)",
    fontFamily: "inherit",
    fontSize: "13px",
    lineHeight: 1.55,
    margin: "25px 18px",
  },
});
