import * as stylex from "@stylexjs/stylex";

const reveal = stylex.keyframes({
  from: { opacity: 0, transform: "translateY(4px)" },
  to: { opacity: 1, transform: "translateY(0)" },
});

export const agentAskUserStyles = stylex.create({
  actionSecondary: { color: "var(--color-content-tertiary)" },
  card: {
    animationDuration: {
      default: "160ms",
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
    animationName: reveal,
    animationTimingFunction: "cubic-bezier(0.2, 0.8, 0.2, 1)",
    backgroundColor: "var(--color-surface-panel)",
    borderColor: "var(--color-border-secondary)",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "0 3px 6px -2px lch(0 0 0 / 2%), 0 1px 1px lch(0 0 0 / 4%)",
    padding: "14px",
    position: "relative",
    width: "100%",
    zIndex: 1,
  },
  cardCompact: { borderRadius: "8px", boxShadow: "none", padding: "12px" },
  continue: { marginInlineStart: "auto" },
  copy: { display: "grid", gap: "1px", minWidth: 0 },
  copyDescription: {
    color: "var(--color-content-tertiary)",
    fontSize: "11px",
    lineHeight: "16px",
  },
  copyTitle: { fontSize: "12px", fontWeight: 500, lineHeight: "16px" },
  eyebrow: {
    color: "var(--color-content-tertiary)",
    fontSize: "11px",
    fontWeight: 500,
    lineHeight: "16px",
  },
  footer: {
    alignItems: "center",
    borderTopColor: "var(--color-border-tertiary)",
    borderTopStyle: "solid",
    borderTopWidth: "0.5px",
    display: "flex",
    gap: "4px",
    marginTop: "12px",
    paddingTop: "10px",
  },
  header: { alignItems: "flex-start", display: "flex", gap: "12px" },
  headerCopy: { minWidth: 0 },
  indicator: {
    borderColor: "var(--color-border-secondary)",
    borderRadius: "999px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--color-content-inverse)",
    display: "grid",
    flex: "0 0 auto",
    height: "14px",
    marginTop: "1px",
    placeItems: "center",
    width: "14px",
  },
  indicatorMultiple: { borderRadius: "4px" },
  indicatorSelected: {
    backgroundColor: "lch(53 52.26 286.91)",
    borderColor: "lch(53 52.26 286.91)",
  },
  option: {
    alignItems: "flex-start",
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--color-surface-interactive-hover)",
    },
    borderColor: "transparent",
    borderRadius: "7px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    color: "var(--color-content-primary)",
    display: "flex",
    font: "inherit",
    gap: "9px",
    minWidth: 0,
    padding: "8px 9px",
    textAlign: "left",
    transition: "background-color 100ms ease, border-color 100ms ease",
    width: "100%",
  },
  optionSelected: {
    backgroundColor: {
      default: "var(--color-surface-selected)",
      ":hover": "var(--color-surface-selected)",
    },
    borderColor: "var(--color-border-secondary)",
  },
  options: { display: "grid", gap: "4px", marginTop: "12px" },
  optionsCompact: { maxHeight: "190px", overflowY: "auto" },
  other: { alignItems: "center" },
  otherInput: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "var(--color-content-primary)",
    font: "inherit",
    fontSize: "12px",
    lineHeight: "16px",
    minWidth: 0,
    outline: 0,
    width: "100%",
    "::placeholder": { color: "var(--color-content-tertiary)" },
  },
  preview: {
    backgroundColor: "var(--color-surface-canvas)",
    borderColor: "var(--color-border-tertiary)",
    borderRadius: "5px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    color: "var(--color-content-secondary)",
    display: "block",
    fontSize: "10px",
    lineHeight: "15px",
    marginTop: "6px",
    overflow: "hidden",
    padding: "6px 7px",
    textOverflow: "ellipsis",
    whiteSpace: "pre-wrap",
  },
  progress: {
    color: "var(--color-content-tertiary)",
    fontSize: "11px",
    fontVariantNumeric: "tabular-nums",
    fontWeight: 500,
    lineHeight: "16px",
    marginInlineStart: "auto",
  },
  prompt: {
    color: "var(--color-content-primary)",
    fontSize: "13px",
    fontWeight: 500,
    lineHeight: "19px",
    margin: "2px 0 0",
  },
});
