import * as stylex from "@stylexjs/stylex";

export const agentPageStyles = stylex.create({
  agentTarget: {
    alignItems: "center",
    backgroundColor: "var(--color-surface-panel)",
    borderColor: "var(--color-border-secondary)",
    borderRadius: "var(--radius-control)",
    borderStyle: "solid",
    borderWidth: "0.5px",
    color: "var(--color-content-secondary)",
    display: "flex",
    gap: "6px",
    height: "28px",
    marginInlineEnd: "6px",
    minWidth: 0,
    paddingInline: "8px",
  },
  agentTargetSelect: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "var(--color-content-primary)",
    font: "inherit",
    fontSize: "12px",
    minWidth: 0,
    outlineStyle: "none",
    outlineWidth: 0,
  },
  assistantMessage: { fontSize: "14px", lineHeight: "22px", margin: "0 8px" },
  attachButton: {
    borderRadius: "999px",
    height: "24px",
    minWidth: "24px",
    padding: 0,
    width: "24px",
  },
  chatSwitcher: {
    backgroundColor: {
      default: "lch(94.854 0.5 282)",
      ":hover": "var(--color-surface-interactive-hover)",
    },
    borderRadius: "9999px",
    boxShadow: "none",
    color: "lch(9.794 0 282)",
    fontSize: "12px",
    fontWeight: 500,
    gap: "6px",
    height: "28px",
    marginInlineStart: { default: "-8px", "@media (max-width: 760px)": "24px" },
    maxWidth: {
      default: "min(440px, calc(100vw - 420px))",
      "@media (max-width: 760px)": "calc(100vw - 150px)",
    },
    paddingInline: "8px",
  },
  chatSwitcherLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  compactButton: { flex: "0 0 auto", marginInlineStart: "auto" },
  composer: {
    display: "grid",
    gap: "8px",
    minHeight: "104px",
    padding: "12px",
    width: "100%",
  },
  composerActions: { flex: "0 0 auto", gap: "8px", marginInlineStart: "auto" },
  composerDock: {
    borderRadius: "12px",
    gridRow: 3,
    isolation: "isolate",
    margin: {
      default: "0 auto 8px",
      "@media (max-width: 760px)": "0 auto 4px",
    },
    padding: "4px",
    position: "relative",
    width: {
      default: "min(829px, calc(100% - 40px))",
      "@media (max-width: 760px)": "calc(100% - 24px)",
    },
    zIndex: 3,
  },
  composerDockEditing: {
    backgroundImage: "linear-gradient(lch(96.5 0 282), lch(100 0 282))",
  },
  composerDockTrajectory: {
    bottom: { default: "8px", "@media (max-width: 760px)": "4px" },
    gridRow: "auto",
    left: "50%",
    margin: 0,
    position: "absolute",
    transform: "translateX(-50%)",
  },
  composerFooter: {
    alignItems: "center",
    display: "flex",
    gap: "8px",
    height: "24px",
    minWidth: 0,
    overflowX: "auto",
    scrollbarWidth: "none",
  },
  composerSurface: {
    backgroundColor: "var(--color-surface-panel)",
    borderRadius: "10px",
    boxShadow: "0 3px 6px -2px lch(0 0 0 / 2%), 0 1px 1px lch(0 0 0 / 4%)",
    position: "relative",
    width: "100%",
    zIndex: 1,
  },
  contextSuggestion: {
    alignItems: "start",
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--color-surface-interactive-hover)",
      ":focus-visible": "var(--color-surface-interactive-hover)",
    },
    borderRadius: "6px",
    borderWidth: 0,
    color: {
      default: "var(--color-content-secondary)",
      ":hover": "var(--color-content-primary)",
      ":focus-visible": "var(--color-content-primary)",
    },
    display: "grid",
    font: "inherit",
    gap: "6px",
    gridTemplateColumns: "20px minmax(0, 1fr)",
    padding: "7px 8px",
    textAlign: "left",
  },
  contextSuggestionDescription: {
    color: "var(--color-content-tertiary)",
    display: "block",
    fontSize: "11px",
    lineHeight: "15px",
    marginTop: "1px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  contextSuggestionIcon: { marginTop: "2px" },
  contextSuggestionTitle: {
    display: "block",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "17px",
  },
  contextSuggestions: {
    backgroundColor: "var(--color-surface-panel)",
    borderColor: "var(--color-border-secondary)",
    borderRadius: "8px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "0 8px 24px lch(0 0 0 / 10%)",
    display: "grid",
    left: "12px",
    maxHeight: "240px",
    overflowY: "auto",
    padding: "4px",
    position: "absolute",
    right: "12px",
    top: "64px",
    zIndex: 4,
  },
  conversation: {
    gridRow: 2,
    minHeight: 0,
    overflowY: "auto",
    padding: { default: "36px 0", "@media (max-width: 760px)": "24px 0" },
    position: "relative",
    scrollbarWidth: "thin",
    width: "100%",
  },
  conversationContent: {
    marginInline: "auto",
    width: {
      default: "min(820px, calc(100% - 48px))",
      "@media (max-width: 760px)": "calc(100% - 24px)",
    },
  },
  conversationPage: { gridTemplateRows: "44px minmax(0, 1fr) auto" },
  conversationPageTrajectory: { gridTemplateRows: "44px minmax(0, 1fr)" },
  conversationTime: {
    color: "var(--color-content-tertiary)",
    display: { default: "block", "@media (max-width: 760px)": "none" },
    fontSize: "11px",
    marginBottom: "24px",
  },
  copyMessage: { margin: "2px 0 0 8px" },
  editingMessageClip: { height: "26.5px", overflow: "hidden", width: "100%" },
  editingMessageReveal: {
    height: 0,
    opacity: 0,
    overflow: "hidden",
    position: "relative",
    transition: {
      default:
        "height 180ms cubic-bezier(0.2, 0.8, 0.2, 1), opacity 140ms ease, visibility 0s linear 180ms",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    visibility: "hidden",
    width: "100%",
    zIndex: 1,
  },
  editingMessageRevealOpen: {
    height: "26.5px",
    opacity: 1,
    transitionDelay: "0s",
    visibility: "visible",
  },
  emptyCanvas: {
    display: "grid",
    minHeight: 0,
    placeItems: "center",
    position: "relative",
  },
  emptyCenter: {
    position: "relative",
    width: {
      default: "min(712px, calc(100% - 48px))",
      "@media (max-width: 760px)": "calc(100% - 46px)",
    },
    zIndex: 1,
  },
  emptyPage: { gridTemplateRows: "44px minmax(0, 1fr)" },
  header: { position: "relative", zIndex: 4 },
  headerActions: {
    alignItems: "center",
    display: "flex",
    gap: "2px",
    marginInlineStart: "auto",
  },
  jumpToLatest: {
    borderColor: "var(--color-border-secondary)",
    borderRadius: "999px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    bottom: "12px",
    boxShadow: "0 4px 14px lch(0 0 0 / 10%)",
    display: "flex",
    margin: "-18px auto 0",
    position: "sticky",
    zIndex: 2,
  },
  page: {
    backgroundColor: "var(--color-surface-canvas)",
    color: "var(--color-content-primary)",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    height: "100%",
    minHeight: 0,
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  promptQueue: {
    alignItems: "start",
    backgroundColor: "var(--color-surface-panel)",
    borderColor: "var(--color-border-tertiary)",
    borderRadius: "8px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    display: "grid",
    gap: "8px",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    marginBottom: "8px",
    padding: "6px 8px",
  },
  queueItem: {
    alignItems: "center",
    backgroundColor: "var(--color-surface-subtle)",
    borderRadius: "5px",
    color: "var(--color-content-secondary)",
    display: "grid",
    fontSize: "11px",
    gridTemplateColumns: "minmax(0, 1fr) 20px",
    minHeight: "24px",
    paddingInlineStart: "6px",
  },
  queueItemLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  queueItems: { display: "grid", gap: "3px" },
  queueLabel: {
    color: "var(--color-content-tertiary)",
    fontSize: "10px",
    fontWeight: 600,
    letterSpacing: "0.04em",
    paddingTop: "4px",
    textTransform: "uppercase",
  },
  renameForm: {
    alignItems: "center",
    display: "flex",
    gap: "6px",
    minWidth: "min(360px, calc(100vw - 520px))",
  },
  renameInput: {
    backgroundColor: "var(--color-surface-panel)",
    borderColor: {
      default: "var(--color-border-secondary)",
      ":focus": "var(--color-border-control-focus)",
    },
    borderRadius: "var(--radius-control)",
    borderStyle: "solid",
    borderWidth: "0.5px",
    color: "var(--color-content-primary)",
    font: "inherit",
    fontSize: "12px",
    height: "28px",
    outline: "none",
    paddingInline: "9px",
    width: "100%",
  },
  sendButton: {
    backgroundColor: {
      default: null,
      ":hover": "var(--color-surface-interactive-hover)",
    },
    borderRadius: "999px",
    height: "24px",
    marginInlineStart: "auto",
    minWidth: "24px",
    opacity: 0.5,
    padding: 0,
    width: "24px",
  },
  sendButtonActive: {
    backgroundColor: {
      default: "lch(53 52.26 286.91)",
      ":hover": "lch(49 52.26 286.91)",
    },
    color: "lch(100 0 282)",
    opacity: 1,
  },
  skillsButton: {
    color: "var(--color-content-tertiary)",
    flex: "0 0 auto",
    height: "24px",
    paddingInline: "4px 6px",
  },
  stopButton: {
    borderRadius: "999px",
    color: "var(--color-content-secondary)",
    flex: "0 0 auto",
    height: "24px",
    minWidth: "24px",
    padding: 0,
    width: "24px",
  },
  suggestion: {
    alignContent: "space-between",
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--color-surface-interactive-hover)",
    },
    borderColor: {
      default: "var(--color-border-tertiary)",
      ":hover": "var(--color-border-secondary)",
    },
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    color: "var(--color-content-primary)",
    display: "grid",
    font: "inherit",
    gap: "18px",
    minHeight: "136px",
    minWidth: 0,
    padding: "16px",
    textAlign: "left",
    transition: {
      default: "background-color 120ms ease, border-color 120ms ease",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
  },
  suggestionCopy: { display: "block" },
  suggestionDescription: {
    color: "var(--color-content-tertiary)",
    display: "block",
    fontSize: "12px",
    lineHeight: "17px",
    marginTop: "4px",
  },
  suggestionGrid: {
    display: "grid",
    gap: "8px",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
  },
  suggestions: {
    display: { default: "block", "@media (max-width: 760px)": "none" },
    left: 0,
    position: "absolute",
    top: "calc(100% + 16px)",
    width: "100%",
  },
  suggestionsHeader: {
    alignItems: "center",
    color: "var(--color-content-tertiary)",
    display: "flex",
    fontSize: "12px",
    height: "24px",
    marginBottom: "8px",
    paddingInlineStart: "2px",
  },
  suggestionsHeaderAction: { marginInlineStart: "auto" },
  suggestionTitle: {
    display: "block",
    fontSize: "13px",
    fontWeight: 500,
    lineHeight: "18px",
  },
  taskAgent: { color: "var(--color-content-secondary)", fontWeight: 500 },
  taskItem: {
    alignItems: "center",
    color: "var(--color-content-tertiary)",
    display: "grid",
    fontSize: "11px",
    gap: "7px",
    gridTemplateColumns: "7px minmax(72px, auto) minmax(0, 1fr)",
    minHeight: "24px",
  },
  taskProgress: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  taskShelf: {
    backgroundColor: "var(--color-surface-panel)",
    borderColor: "var(--color-border-tertiary)",
    borderRadius: "8px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    display: "grid",
    gap: "3px",
    marginBottom: "8px",
    maxHeight: "112px",
    overflowY: "auto",
    padding: "6px 8px",
  },
  taskStatus: {
    backgroundColor: "var(--color-content-tertiary)",
    borderRadius: "50%",
    height: "6px",
    width: "6px",
  },
  taskStatusRunning: {
    backgroundColor: "lch(58 54 145)",
    boxShadow: "0 0 0 3px lch(58 54 145 / 12%)",
  },
  terminalCode: {
    fontFamily: "var(--font-mono)",
    fontSize: "11px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  terminalOutput: {
    backgroundColor: "var(--color-surface-subtle)",
    borderTopColor: "var(--color-border-tertiary)",
    borderTopStyle: "solid",
    borderTopWidth: "0.5px",
    color: "var(--color-content-secondary)",
    fontFamily: "var(--font-mono)",
    fontSize: "11px",
    lineHeight: "17px",
    margin: 0,
    maxHeight: "112px",
    overflow: "auto",
    padding: "8px 10px",
    whiteSpace: "pre-wrap",
  },
  terminalRun: {
    backgroundColor: "var(--color-surface-panel)",
    borderColor: "var(--color-border-tertiary)",
    borderRadius: "8px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    overflow: "hidden",
  },
  terminalShelf: {
    display: "grid",
    gap: "4px",
    marginBottom: "8px",
    maxHeight: "180px",
    overflowY: "auto",
  },
  terminalStatus: {
    color: "var(--color-content-tertiary)",
    fontSize: "10px",
    textTransform: "capitalize",
  },
  terminalStderr: { color: "var(--color-status-error-content)" },
  terminalSummary: {
    alignItems: "center",
    color: "var(--color-content-secondary)",
    cursor: "pointer",
    display: "grid",
    gap: "5px",
    gridTemplateColumns: "18px minmax(0, 1fr) auto",
    listStyle: "none",
    minHeight: "30px",
    padding: "5px 8px",
  },
  textarea: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "var(--color-content-primary)",
    display: "block",
    font: "inherit",
    fontSize: "14px",
    height: "46px",
    lineHeight: "24px",
    minHeight: "46px",
    outline: "none",
    padding: "0 6px",
    resize: "none",
    width: "100%",
    "::placeholder": { color: "var(--color-content-tertiary)" },
  },
  toolCall: { minWidth: 0 },
  toolCalls: {
    display: "grid",
    gap: "4px",
    margin: "1px 8px 14px",
    width: {
      default: "min(500px, calc(100% - 16px))",
      "@media (max-width: 760px)": "calc(100% - 16px)",
    },
  },
  toolChevron: {
    color: "var(--color-content-tertiary)",
    display: "grid",
    height: "14px",
    marginInlineStart: "-2px",
    width: "14px",
  },
  toolDetailLabel: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  toolDetailRow: {
    alignItems: "center",
    color: "var(--color-content-secondary)",
    display: "flex",
    fontSize: "13px",
    gap: "9px",
    lineHeight: "20px",
    minHeight: "24px",
    minWidth: 0,
  },
  toolDetails: { display: "grid", gap: "2px", minWidth: 0, padding: "0 0 1px" },
  toolName: {
    color: "inherit",
    fontWeight: 400,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  toolSummary: {
    alignItems: "center",
    color: {
      default: "var(--color-content-tertiary)",
      ":hover": "var(--color-content-primary)",
      ":focus-visible": "var(--color-content-primary)",
    },
    cursor: "pointer",
    display: "flex",
    fontSize: "13px",
    gap: "9px",
    lineHeight: "20px",
    listStyle: "none",
    maxWidth: "100%",
    minHeight: "26px",
    outline: "none",
    padding: "2px 0",
    width: "fit-content",
  },
  trajectoryComposerBackdrop: {
    backgroundImage:
      "linear-gradient(to bottom, transparent 0, color-mix(in srgb, var(--color-surface-canvas) 12%, transparent) 34px, color-mix(in srgb, var(--color-surface-canvas) 52%, transparent) 86px, color-mix(in srgb, var(--color-surface-canvas) 88%, transparent) 132px, var(--color-surface-canvas) 166px, var(--color-surface-canvas) 100%)",
    bottom: 0,
    height: "254px",
    left: 0,
    pointerEvents: "none",
    position: "absolute",
    right: 0,
    zIndex: 2,
  },
  turn: { display: "grid", marginBottom: "38px" },
  turnControl: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--color-surface-interactive-hover)",
      ":focus-visible": "var(--color-surface-interactive-hover)",
      "[data-popup-open]": "var(--color-surface-interactive-hover)",
    },
    borderRadius: "6px",
    borderWidth: 0,
    boxShadow: "none",
    color: {
      default: "var(--color-content-tertiary)",
      ":hover": "var(--color-content-secondary)",
      ":focus-visible": "var(--color-content-secondary)",
      "[data-popup-open]": "var(--color-content-secondary)",
    },
    display: "inline-flex",
    flex: "0 0 auto",
    font: "inherit",
    fontSize: "11px",
    gap: "5px",
    height: "24px",
    opacity: { default: 1, ":disabled": 0.5 },
    paddingInline: "5px",
    transition: "background-color 120ms ease-out, color 120ms ease-out",
  },
  userMessage: {
    backgroundColor: "var(--color-surface-selected)",
    borderRadius: "10px",
    fontSize: "13px",
    lineHeight: "20px",
    maxWidth: { default: "76%", "@media (max-width: 760px)": "88%" },
    overflowWrap: "anywhere",
    padding: "9px 12px",
    width: "fit-content",
  },
  userMessageActions: { height: "24px", marginTop: "5px", opacity: 1 },
  userMessageGroup: {
    alignItems: "flex-end",
    display: "flex",
    flexDirection: "column",
    marginBottom: "24px",
    minWidth: 0,
    width: "100%",
  },
  viewTabs: {
    alignSelf: "center",
    marginInlineStart: { default: "12px", "@media (max-width: 760px)": "6px" },
  },
  worked: {
    color: "var(--color-content-tertiary)",
    fontSize: "12px",
    margin: "0 8px 12px",
  },
  workedBody: {
    borderInlineStartColor: "var(--color-border-secondary)",
    borderInlineStartStyle: "solid",
    borderInlineStartWidth: "2px",
    lineHeight: "20px",
    margin: "10px 0 0 10px",
    paddingInlineStart: "12px",
  },
  workedChevron: { display: "inline-flex" },
  workedSummary: {
    alignItems: "center",
    cursor: "pointer",
    display: "flex",
    gap: "5px",
    listStyle: "none",
    width: "fit-content",
  },
});
