import { Button } from "@lenso/ui/button";
import { Dialog } from "@lenso/ui/dialog";
import { cjk } from "@streamdown/cjk";
import { ExternalLink } from "lucide-react";
import { Streamdown, type LinkSafetyModalProps } from "streamdown";

import styles from "./agent-markdown.module.css";

const plugins = { cjk };
const linkSafety = {
  enabled: true,
  renderModal: (props: LinkSafetyModalProps) => (
    <AgentLinkSafetyModal {...props} />
  ),
};

function AgentLinkSafetyModal({
  isOpen,
  onClose,
  onConfirm,
  url,
}: LinkSafetyModalProps) {
  return (
    <Dialog.Root
      onOpenChange={(open) => {
        if (!open) {
          onClose();
        }
      }}
      open={isOpen}
    >
      <Dialog.Portal>
        <Dialog.Backdrop />
        <Dialog.Popup className={styles.linkDialog}>
          <div className={styles.linkDialogIcon}>
            <ExternalLink aria-hidden="true" size={16} strokeWidth={1.7} />
          </div>
          <div className={styles.linkDialogContent}>
            <Dialog.Title className={styles.linkDialogTitle}>
              Open external link?
            </Dialog.Title>
            <Dialog.Description className={styles.linkDialogDescription}>
              This link was generated by the Agent. Check the destination before
              continuing.
            </Dialog.Description>
            <code className={styles.linkDestination}>{url}</code>
          </div>
          <div className={styles.linkDialogActions}>
            <Button onClick={onClose} size="compact" variant="ghost">
              Cancel
            </Button>
            <Button onClick={onConfirm} size="compact" variant="primary">
              Open link
            </Button>
          </div>
        </Dialog.Popup>
      </Dialog.Portal>
    </Dialog.Root>
  );
}

export function AgentMarkdown({
  children,
  compact = false,
  streaming = false,
}: {
  children: string;
  compact?: boolean;
  streaming?: boolean;
}) {
  return (
    <Streamdown
      animated={false}
      className={`${styles.content} ${compact ? styles.compact : ""}`}
      controls={false}
      dir="auto"
      isAnimating={streaming}
      linkSafety={linkSafety}
      mode={streaming ? "streaming" : "static"}
      normalizeHtmlIndentation
      plugins={plugins}
      skipHtml
    >
      {children}
    </Streamdown>
  );
}
