import * as stylex from "@stylexjs/stylex";

export const profileStyles = stylex.create({
  root: { display: "grid", gap: 14, marginBlockStart: 28, minWidth: 0 },
  sectionHeading: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  heading: {
    fontSize: 24,
    lineHeight: "32px",
    fontWeight: 500,
    margin: "0 0 8px",
    overflowWrap: "anywhere",
  },
  muted: {
    fontSize: 13,
    lineHeight: "20px",
    color: "var(--color-content-secondary)",
    margin: 0,
  },
  hint: {
    fontSize: 12,
    lineHeight: "18px",
    color: "var(--color-content-tertiary)",
    margin: 0,
    overflowWrap: "anywhere",
  },
  panel: {
    border: "1px solid var(--color-border-tertiary)",
    backgroundColor: "var(--color-surface-panel)",
    borderRadius: 16,
    overflow: "hidden",
    minWidth: 0,
  },
  profileHeader: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "16px 20px",
    borderBottom: "1px solid var(--color-border-tertiary)",
  },
  profileIdentity: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 10,
    minWidth: 0,
  },
  selector: {
    minWidth: 150,
    maxWidth: "100%",
    justifyContent: "space-between",
    gap: 12,
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    flexShrink: 0,
    fontSize: 11,
    lineHeight: "18px",
    padding: "2px 8px",
    borderRadius: 999,
    backgroundColor: "var(--color-surface-subtle)",
    color: "var(--color-content-secondary)",
  },
  fields: { display: "grid", gap: 18, padding: 20 },
  field: {
    display: "grid",
    gap: 8,
    fontSize: 12,
    fontWeight: 500,
    minWidth: 0,
  },
  fieldTitle: { fontSize: 13, fontWeight: 600, lineHeight: "20px", margin: 0 },
  input: { width: "100%", maxWidth: "none" },
  textarea: {
    boxSizing: "border-box",
    width: "100%",
    minHeight: 112,
    resize: "vertical",
    borderRadius: 10,
    padding: 12,
    border: "1px solid var(--color-border-tertiary)",
    backgroundColor: "var(--color-surface-canvas)",
    color: "var(--color-content-primary)",
    fontFamily: "inherit",
    fontSize: 13,
    fontWeight: 400,
    lineHeight: "20px",
    ":focus-visible": {
      outline: "2px solid var(--color-focus-ring)",
      outlineOffset: 2,
    },
  },
  templateDescription: {
    margin: 0,
    fontSize: 13,
    lineHeight: "21px",
    color: "var(--color-content-secondary)",
  },
  instructionPreview: { display: "grid", gap: 6 },
  previewText: {
    margin: 0,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    fontSize: 12,
    lineHeight: "20px",
    color: "var(--color-content-tertiary)",
    maxHeight: 160,
    overflowY: "auto",
  },
  capabilities: {
    borderTop: "1px solid var(--color-border-tertiary)",
    minWidth: 0,
  },
  capabilityHeading: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    padding: "18px 20px 14px",
  },
  filters: { display: "flex", flexWrap: "wrap", gap: 8, paddingInline: 20 },
  search: { flex: "1 1 180px", width: "100%", maxWidth: "none", minWidth: 0 },
  listToolbar: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    minHeight: 42,
    padding: "4px 20px",
    marginBlockStart: 8,
  },
  bulkActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 2,
    marginInlineEnd: -8,
  },
  list: {
    display: "grid",
    listStyle: "none",
    margin: 0,
    padding: "0 20px",
    maxHeight: 320,
    overflowY: "auto",
    overscrollBehavior: "contain",
    scrollbarWidth: "thin",
  },
  row: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 20,
    paddingBlock: 12,
    borderBottom: "1px solid var(--color-border-tertiary)",
    ":last-child": { borderBottomWidth: 0 },
  },
  rowCopy: { minWidth: 0, display: "grid", gap: 3 },
  rowTitle: {
    fontSize: 12,
    fontWeight: 500,
    lineHeight: "18px",
    overflowWrap: "anywhere",
  },
  providerTitle: {
    fontSize: 13,
    fontWeight: 500,
    lineHeight: "18px",
    textTransform: "capitalize",
    overflowWrap: "anywhere",
  },
  rowDescription: {
    fontSize: 12,
    lineHeight: "18px",
    color: "var(--color-content-tertiary)",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    overflowWrap: "anywhere",
  },
  readOnlyState: {
    fontSize: 11,
    lineHeight: "18px",
    color: "var(--color-content-tertiary)",
    flexShrink: 0,
  },
  enabledState: { color: "var(--color-content-secondary)" },
  permissionNote: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    padding: "12px 20px",
    borderTop: "1px solid var(--color-border-tertiary)",
  },
  empty: { display: "grid", gap: 6, textAlign: "center", padding: "32px 20px" },
  inlineNotice: {
    padding: "12px 20px",
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    margin: 0,
  },
  footer: {
    display: "flex",
    flexWrap: "wrap",
    gap: 12,
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 20px",
    borderTop: "1px solid var(--color-border-tertiary)",
    backgroundColor: "var(--color-surface-subtle)",
  },
  footerActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginInlineStart: "auto",
  },
  status: {
    fontSize: 12,
    lineHeight: "18px",
    color: "var(--color-content-secondary)",
    flex: "1 1 180px",
  },
});
