import * as stylex from "@stylexjs/stylex";

import { lensoUiTokens as tokens } from "../../lenso-ui-token-refs.stylex";

export const agentSettingsStyles = stylex.create({
  sectionHeading: { display: "grid", gap: tokens.space2 },
  inset: { marginInline: 16 },
  agentGroup: { marginBlockStart: 16 },
  sectionBody: { display: "grid", overflow: "hidden" },
  description: {
    color: tokens.colorContentTertiary,
    display: "block",
    fontSize: 12,
    lineHeight: "18px",
    margin: 0,
    overflowWrap: "anywhere",
  },
  agentPicker: {
    justifyContent: "space-between",
    minWidth: 160,
    maxWidth: "100%",
  },
  navigation: {
    display: "flex",
    flexWrap: "wrap",
    gap: tokens.space4,
    margin: "16px 16px 0",
  },
  backLink: {
    color: tokens.colorContentTertiary,
    display: "inline-block",
    fontSize: 12,
    marginBlockEnd: 16,
    marginInline: 16,
    textDecoration: { default: "none", ":hover": "underline" },
  },
  textLink: {
    color: tokens.colorContentSecondary,
    fontSize: 12,
    textDecoration: { default: "none", ":hover": "underline" },
  },
  sectionRoot: { marginBlockStart: 32 },
  sectionHeader: { gap: 4 },
  list: { display: "grid", listStyle: "none", margin: 0, padding: 0 },
  listItem: {
    borderBottomColor: tokens.colorBorderTertiary,
    borderBottomStyle: "solid",
    borderBottomWidth: { default: "0.5px", ":last-child": 0 },
  },
  row: {
    alignItems: "center",
    borderBottomColor: tokens.colorBorderTertiary,
    borderBottomStyle: "solid",
    borderBottomWidth: "0.5px",
    display: "flex",
    gap: tokens.space4,
    justifyContent: "space-between",
    minHeight: 65,
    boxSizing: "border-box",
    padding: "10px 16px",
    ":last-child": { borderBottomWidth: 0 },
  },
  linkRow: {
    alignItems: "center",
    color: "inherit",
    display: "flex",
    gap: tokens.space4,
    justifyContent: "space-between",
    minHeight: 65,
    boxSizing: "border-box",
    paddingBlock: 10,
    paddingInline: 16,
    textDecoration: "none",
    backgroundColor: "transparent",
  },
  rowCopy: { display: "grid", gap: 2, minWidth: 0 },
  rowTitle: {
    display: "block",
    fontSize: 13,
    fontWeight: 500,
    lineHeight: "20px",
    overflowWrap: "anywhere",
  },
  actionLabel: {
    color: tokens.colorContentTertiary,
    flexShrink: 0,
    fontSize: 12,
  },
  notice: {
    color: tokens.colorContentTertiary,
    fontSize: 12,
    lineHeight: "18px",
    margin: 0,
    display: "block",
    padding: 16,
  },
  error: {
    color: "var(--color-status-error-content)",
    fontSize: 12,
    lineHeight: "18px",
    margin: 0,
    padding: 16,
  },
  search: { width: "calc(100% - 32px)", margin: 16 },
  retry: { justifySelf: "start", margin: "0 16px 16px" },
});
