import { Button } from "@lenso/ui/button";
import { Dialog } from "@lenso/ui/dialog";
import { cjk } from "@streamdown/cjk";
import * as stylex from "@stylexjs/stylex";
import { ExternalLink } from "lucide-react";
import { type ComponentPropsWithoutRef, createElement } from "react";
import {
  Streamdown,
  type Components,
  type LinkSafetyModalProps,
} from "streamdown";

import { agentMarkdownStyles as styles } from "./agent-markdown.stylex";

const plugins = { cjk };
const streamdownSlots: Record<string, string> = {
  a: "link",
  blockquote: "blockquote",
  code: "inline-code",
  h1: "heading-1",
  h2: "heading-2",
  h3: "heading-3",
  h4: "heading-4",
  h5: "heading-5",
  h6: "heading-6",
  hr: "horizontal-rule",
  li: "list-item",
  ol: "ordered-list",
  strong: "strong",
  table: "table",
  td: "table-cell",
  th: "table-header-cell",
  ul: "unordered-list",
};
const styledElement = <T extends keyof React.JSX.IntrinsicElements>(
  tag: T,
  ...xstyles: stylex.StyleXStyles[]
) =>
  function StyledMarkdownElement({
    className,
    node: _node,
    ...props
  }: ComponentPropsWithoutRef<T> & { node?: unknown }) {
    return createElement(tag, {
      ...props,
      className: [stylex.props(...xstyles).className, className]
        .filter(Boolean)
        .join(" "),
      ...(streamdownSlots[tag]
        ? { "data-streamdown": streamdownSlots[tag] }
        : {}),
    });
  };

const markdownComponents = {
  a: styledElement("a", styles.link),
  blockquote: styledElement("blockquote", styles.blockquote),
  h1: styledElement("h1", styles.heading, styles.heading1),
  h2: styledElement("h2", styles.heading, styles.heading2),
  h3: styledElement("h3", styles.heading, styles.heading3),
  h4: styledElement("h4", styles.heading, styles.headingSmall),
  h5: styledElement("h5", styles.heading, styles.headingSmall),
  h6: styledElement("h6", styles.heading, styles.headingSmall),
  hr: styledElement("hr", styles.horizontalRule),
  img: styledElement("img", styles.image),
  inlineCode: styledElement("code", styles.inlineCode),
  input: styledElement("input", styles.taskCheckbox),
  li: styledElement("li", styles.listItem),
  ol: styledElement("ol", styles.list, styles.orderedList),
  p: styledElement("p", styles.paragraph),
  pre: styledElement("pre", styles.codeBlock),
  strong: styledElement("strong", styles.strong),
  table: styledElement("table", styles.table),
  td: styledElement("td", styles.tableCell),
  th: styledElement("th", styles.tableCell, styles.tableHeader),
  ul: styledElement("ul", styles.list, styles.unorderedList),
} as unknown as Components;
const linkSafety = {
  enabled: true,
  renderModal: (props: LinkSafetyModalProps) => (
    <AgentLinkSafetyModal {...props} />
  ),
};

function AgentLinkSafetyModal({
  isOpen,
  onClose,
  onConfirm,
  url,
}: LinkSafetyModalProps) {
  return (
    <Dialog.Root
      onOpenChange={(open) => {
        if (!open) {
          onClose();
        }
      }}
      open={isOpen}
    >
      <Dialog.Portal>
        <Dialog.Backdrop />
        <Dialog.Popup xstyle={styles.linkDialog}>
          <div {...stylex.props(styles.linkDialogIcon)}>
            <ExternalLink aria-hidden="true" size={16} strokeWidth={1.7} />
          </div>
          <div {...stylex.props(styles.linkDialogContent)}>
            <Dialog.Title xstyle={styles.linkDialogTitle}>
              Open external link?
            </Dialog.Title>
            <Dialog.Description xstyle={styles.linkDialogDescription}>
              This link was generated by the Agent. Check the destination before
              continuing.
            </Dialog.Description>
            <code {...stylex.props(styles.linkDestination)}>{url}</code>
          </div>
          <div {...stylex.props(styles.linkDialogActions)}>
            <Button onClick={onClose} size="compact" variant="ghost">
              Cancel
            </Button>
            <Button onClick={onConfirm} size="compact" variant="primary">
              Open link
            </Button>
          </div>
        </Dialog.Popup>
      </Dialog.Portal>
    </Dialog.Root>
  );
}

export function AgentMarkdown({
  children,
  compact = false,
  streaming = false,
}: {
  children: string;
  compact?: boolean;
  streaming?: boolean;
}) {
  const markdownClassName = stylex.props(
    styles.content,
    compact && styles.compact
  ).className;

  return (
    <Streamdown
      animated={false}
      {...(markdownClassName ? { className: markdownClassName } : {})}
      components={markdownComponents}
      controls={false}
      dir="auto"
      isAnimating={streaming}
      linkSafety={linkSafety}
      mode={streaming ? "streaming" : "static"}
      normalizeHtmlIndentation
      plugins={plugins}
      skipHtml
    >
      {children}
    </Streamdown>
  );
}
