import * as stylex from "@stylexjs/stylex";

export const settingsPageStyles = stylex.create({
  headerActions: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  description: {
    margin: 0,
    fontSize: 13,
    lineHeight: "20px",
    color: "var(--muted)",
    overflowWrap: "anywhere",
  },
  column: {
    marginInline: { default: "26px", "@media (max-width: 760px)": "auto" },
    paddingBlock: "30px 64px",
    width: {
      default: "min(680px, calc(100% - 52px))",
      "@media (max-width: 760px)": "calc(100% - 32px)",
    },
    minWidth: 0,
    "@media (max-width: 560px)": { paddingBlock: "32px 48px" },
  },
  group: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--separator)",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "none",
  },
  headerInset: { paddingInline: 16 },
  page: {
    backgroundColor: "var(--background)",
    color: "var(--foreground)",
    minHeight: "100%",
    overflowY: "auto",
    width: "100%",
  },
  row: {
    alignItems: {
      default: "center",
      "@media (max-width: 520px)": "flex-start",
    },
    backgroundColor: {
      default: "transparent",
      ":hover": "transparent",
    },
    borderBottomColor: "var(--separator)",
    borderBottomStyle: "solid",
    borderBottomWidth: "0.5px",
    borderInlineWidth: 0,
    borderTopWidth: 0,
    gap: { default: null, "@media (max-width: 520px)": "10px" },
    gridTemplateColumns: {
      default: null,
      "@media (max-width: 760px)": "minmax(0, 1fr) auto",
      "@media (max-width: 520px)": "minmax(0, 1fr)",
    },
    height: "auto",
    minHeight: "65px",
    opacity: 1,
    padding: "10px 16px",
    paddingBlock: { default: "10px", "@media (max-width: 520px)": "12px" },
  },
  rowCopy: {
    alignSelf: "center",
    justifyContent: "center",
    paddingBlock: 0,
  },
  rowDisabled: {
    opacity: 0.4,
  },
  rowDescription: {
    color: "var(--muted)",
    fontSize: "12px",
    lineHeight: "18px",
  },
  rowTitle: {
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: 500,
    lineHeight: "19.5px",
  },
  section: {
    gap: "16px",
    marginTop: "32px",
  },
  sectionFollowing: {
    marginTop: "32px",
  },
  sectionTitle: {
    paddingInline: 16,
    fontSize: "15px",
    fontWeight: 600,
    lineHeight: "20px",
    margin: 0,
  },
  selectTrigger: {
    backgroundColor: {
      default: "var(--field-background)",
      ":hover": "var(--default-hover)",
      "[data-visual-state=hover]": "var(--default-hover)",
    },
    borderColor: {
      default: "var(--field-border)",
      ":disabled": "var(--separator)",
      ":focus-visible": "var(--field-border-focus)",
      ":hover": "transparent",
      "[data-popup-open]": "var(--field-border-focus)",
      "[data-visual-state=hover]": "transparent",
    },
    borderRadius: "8px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    fontSize: "13px",
    height: "32px",
    justifyContent: "space-between",
    minWidth: "86px",
    paddingInline: "11px",
    width: "auto",
  },
});
