// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.management-human@1";
pub const DESCRIPTOR_VERSION: &str = "1.1.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:b872e8c0835588494ebdedaa11f2852b561184229c370e37b0974d8c05112b8b";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const MANAGEMENT_HUMAN_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const MANAGEMENT_HUMAN_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const MANAGEMENT_HUMAN_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const MANAGEMENT_HUMAN_CONTRACT: CapabilityReference<ManagementHumanClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_management_human { () => { "{\"capability_id\":\"lenso.management-human@1\",\"descriptor_version\":\"1.1.0\",\"operations\":[\"decide\",\"read_intent\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_management_human_client {
    () => { "{\"capability_id\":\"lenso.management-human@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.management-human@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_management_human_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.management-human@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_management_human_client {
    () => { "{\"capability_id\":\"lenso.management-human@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.management-human@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"many\"}") };
}

pub const DECIDE_OPERATION: &str = "decide";
pub const READ_INTENT_OPERATION: &str = "read_intent";

pub use lenso_contract_runtime::{RawJson, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DecideRequest {
    #[serde(rename = "decision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub decision: Decision,
    #[serde(rename = "intent_digest")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub intent_digest: String,
    #[serde(rename = "operation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub operation_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum Decision {
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "rejected")]
    Rejected,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DecideResponse {
    #[serde(rename = "audit_pending")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub audit_pending: bool,
    #[serde(rename = "operation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub operation_id: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: IntentStatus,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum IntentStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Clone, Debug, PartialEq)]
pub enum DecideError {
    Conflict,
    NotFound,
    PermissionDenied,
    Unavailable,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadIntentRequest {
    #[serde(rename = "operation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub operation_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadIntentResponse {
    #[serde(rename = "audit_pending")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub audit_pending: bool,
    #[serde(rename = "capability")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub capability: String,
    #[serde(rename = "deployment")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub deployment: String,
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "entry_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub entry_id: String,
    #[serde(rename = "expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expires_at: String,
    #[serde(rename = "intent_digest")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub intent_digest: String,
    #[serde(rename = "operation")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub operation: String,
    #[serde(rename = "operation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub operation_id: String,
    #[serde(rename = "parameters_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub parameters_json: RawJson,
    #[serde(rename = "requester")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requester: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: IntentStatus,
    #[serde(rename = "target_instance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub target_instance: String,
    #[serde(rename = "version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub version: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadIntentError {
    Conflict,
    NotFound,
    PermissionDenied,
    Unavailable,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct ManagementHumanDecide;
impl RequestCapability for ManagementHumanDecide {
    type Request = DecideRequest;
    type Response = DecideResponse;
    type DomainError = DecideError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != DECIDE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ManagementHumanRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).decide(context, request)
    }
}

#[derive(Debug)]
pub struct ManagementHumanReadIntent;
impl RequestCapability for ManagementHumanReadIntent {
    type Request = ReadIntentRequest;
    type Response = ReadIntentResponse;
    type DomainError = ReadIntentError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_INTENT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ManagementHumanRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read_intent(context, request)
    }
}

impl serde::Serialize for DecideError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::Unavailable => serializer.serialize_str("unavailable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for DecideError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "not_found" => Ok(Self::NotFound),
                "permission_denied" => Ok(Self::PermissionDenied),
                "unavailable" => Ok(Self::Unavailable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReadIntentError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::Unavailable => serializer.serialize_str("unavailable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadIntentError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "not_found" => Ok(Self::NotFound),
                "permission_denied" => Ok(Self::PermissionDenied),
                "unavailable" => Ok(Self::Unavailable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_decide_request(value: &DecideRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_decide_request(wire: &str) -> Result<DecideRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_decide_response(value: &DecideResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_decide_response(wire: &str) -> Result<DecideResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_decide_error(value: &DecideError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_decide_error(wire: &str) -> Result<DecideError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_read_intent_request(value: &ReadIntentRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_intent_request(wire: &str) -> Result<ReadIntentRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_intent_response(value: &ReadIntentResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_intent_response(wire: &str) -> Result<ReadIntentResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_intent_error(value: &ReadIntentError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_intent_error(wire: &str) -> Result<ReadIntentError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoManagementHumanDecideResult {
    fn __lenso_into_result(self) -> Result<Result<DecideResponse, DecideError>, RuntimeFailure>;
}
impl __LensoIntoManagementHumanDecideResult for Result<DecideResponse, DecideError> {
    fn __lenso_into_result(self) -> Result<Result<DecideResponse, DecideError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoManagementHumanDecideResult for Result<Result<DecideResponse, DecideError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<DecideResponse, DecideError>, RuntimeFailure> { self }
}
impl __LensoIntoManagementHumanDecideResult for Result<DecideResponse, lenso_plugin_authoring::PluginError<DecideError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<DecideResponse, DecideError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoManagementHumanDecideResult for Result<DecideResponse, ManagementHumanDecideInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<DecideResponse, DecideError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ManagementHumanDecideInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ManagementHumanDecideInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoManagementHumanReadIntentResult {
    fn __lenso_into_result(self) -> Result<Result<ReadIntentResponse, ReadIntentError>, RuntimeFailure>;
}
impl __LensoIntoManagementHumanReadIntentResult for Result<ReadIntentResponse, ReadIntentError> {
    fn __lenso_into_result(self) -> Result<Result<ReadIntentResponse, ReadIntentError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoManagementHumanReadIntentResult for Result<Result<ReadIntentResponse, ReadIntentError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReadIntentResponse, ReadIntentError>, RuntimeFailure> { self }
}
impl __LensoIntoManagementHumanReadIntentResult for Result<ReadIntentResponse, lenso_plugin_authoring::PluginError<ReadIntentError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReadIntentResponse, ReadIntentError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoManagementHumanReadIntentResult for Result<ReadIntentResponse, ManagementHumanReadIntentInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReadIntentResponse, ReadIntentError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ManagementHumanReadIntentInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ManagementHumanReadIntentInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait ManagementHumanProvider: fmt::Debug + 'static {
    fn decide(&self, context: InvocationContext, request: DecideRequest) -> NativeRequestFuture<ManagementHumanDecide>;
    fn read_intent(&self, context: InvocationContext, request: ReadIntentRequest) -> NativeRequestFuture<ManagementHumanReadIntent>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_management_human {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportManagementHuman;
        impl $crate::ManagementHumanProvider for $plugin {
        fn decide(&self, context: __LensoNativeSupportManagementHuman::InvocationContext, request: $crate::DecideRequest) -> __LensoNativeSupportManagementHuman::NativeRequestFuture<$crate::ManagementHumanDecide> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::decide(&plugin, context, request).await;
                $crate::__LensoIntoManagementHumanDecideResult::__lenso_into_result(result)
            })
        }
        fn read_intent(&self, context: __LensoNativeSupportManagementHuman::InvocationContext, request: $crate::ReadIntentRequest) -> __LensoNativeSupportManagementHuman::NativeRequestFuture<$crate::ManagementHumanReadIntent> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::read_intent(&plugin, context, request).await;
                $crate::__LensoIntoManagementHumanReadIntentResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_management_human {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportManagementHuman;
        impl $crate::ManagementHumanProvider for $object {
        fn decide(&self, context: __LensoNativeSupportManagementHuman::InvocationContext, request: $crate::DecideRequest) -> __LensoNativeSupportManagementHuman::NativeRequestFuture<$crate::ManagementHumanDecide> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::decide(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoManagementHumanDecideResult::__lenso_into_result(result)
            })
        }
        fn read_intent(&self, context: __LensoNativeSupportManagementHuman::InvocationContext, request: $crate::ReadIntentRequest) -> __LensoNativeSupportManagementHuman::NativeRequestFuture<$crate::ManagementHumanReadIntent> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::read_intent(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoManagementHumanReadIntentResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_management_human {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportManagementHuman;
        impl $crate::ManagementHumanProvider for $object {
        fn decide(&self, context: __LensoNativeSupportManagementHuman::InvocationContext, request: $crate::DecideRequest) -> __LensoNativeSupportManagementHuman::NativeRequestFuture<$crate::ManagementHumanDecide> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::ManagementHumanProvider>::decide(plugin.as_ref(), context, request).await
            })
        }
        fn read_intent(&self, context: __LensoNativeSupportManagementHuman::InvocationContext, request: $crate::ReadIntentRequest) -> __LensoNativeSupportManagementHuman::NativeRequestFuture<$crate::ManagementHumanReadIntent> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::ManagementHumanProvider>::read_intent(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct ManagementHumanRequestEndpoint { provider: Rc<dyn ManagementHumanProvider> }

#[derive(Debug)]
pub struct ManagementHumanEndpoint<P: ManagementHumanProvider> { provider: Rc<P>, request_endpoint: ManagementHumanRequestEndpoint }
impl<P: ManagementHumanProvider> ManagementHumanEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn ManagementHumanProvider> = provider.clone();
        Self { provider, request_endpoint: ManagementHumanRequestEndpoint { provider: request_provider } }
    }
}

impl<P: ManagementHumanProvider> NativeRequestEndpoint for ManagementHumanEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        DECIDE_OPERATION,
        READ_INTENT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            DECIDE_OPERATION => {
                let Ok(request) = request.downcast::<DecideRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).decide(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            READ_INTENT_OPERATION => {
                let Ok(request) = request.downcast::<ReadIntentRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read_intent(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_management_human {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::ManagementHumanEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_management_human {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_management_human!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct ManagementHumanClient {
    decide: NativeRequestHandle<ManagementHumanDecide>,
    read_intent: NativeRequestHandle<ManagementHumanReadIntent>,
}
impl ManagementHumanClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn decide(&self, request: DecideRequest) -> Result<DecideResponse, ManagementHumanDecideInvocationError> {
        self.decide.invoke(DECIDE_OPERATION, request).await
            .map_err(ManagementHumanDecideInvocationError::Runtime)?
            .map_err(ManagementHumanDecideInvocationError::Domain)
    }

    pub async fn decide_with_context(&self, context: InvocationContext, request: DecideRequest) -> Result<DecideResponse, ManagementHumanDecideInvocationError> {
        self.decide.invoke_with_context(DECIDE_OPERATION, context, request).await
            .map_err(ManagementHumanDecideInvocationError::Runtime)?
            .map_err(ManagementHumanDecideInvocationError::Domain)
    }

    pub async fn read_intent(&self, request: ReadIntentRequest) -> Result<ReadIntentResponse, ManagementHumanReadIntentInvocationError> {
        self.read_intent.invoke(READ_INTENT_OPERATION, request).await
            .map_err(ManagementHumanReadIntentInvocationError::Runtime)?
            .map_err(ManagementHumanReadIntentInvocationError::Domain)
    }

    pub async fn read_intent_with_context(&self, context: InvocationContext, request: ReadIntentRequest) -> Result<ReadIntentResponse, ManagementHumanReadIntentInvocationError> {
        self.read_intent.invoke_with_context(READ_INTENT_OPERATION, context, request).await
            .map_err(ManagementHumanReadIntentInvocationError::Runtime)?
            .map_err(ManagementHumanReadIntentInvocationError::Domain)
    }
}

impl CapabilityClient for ManagementHumanClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            decide: dependencies.one::<ManagementHumanDecide>()?,
            read_intent: dependencies.one::<ManagementHumanReadIntent>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for ManagementHumanClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    decide: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ManagementHumanDecide>()?,
                    read_intent: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ManagementHumanReadIntent>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ManagementHumanDecideInvocationError {
    Domain(DecideError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ManagementHumanReadIntentInvocationError {
    Domain(ReadIntentError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct ManagementHumanGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> ManagementHumanGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[DECIDE_OPERATION, READ_INTENT_OPERATION], &[], &[])
            .map(|capability| Self { capability })
    }

    pub fn decide(&self, request: &DecideRequest) -> Result<DecideResponse, lenso_guest_sdk::GuestError<DecideError>> {
        self.capability.request(DECIDE_OPERATION, request)
    }

    pub fn read_intent(&self, request: &ReadIntentRequest) -> Result<ReadIntentResponse, lenso_guest_sdk::GuestError<ReadIntentError>> {
        self.capability.request(READ_INTENT_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct ManagementHumanJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for ManagementHumanJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn descriptor_digest(&self) -> &'static str { DESCRIPTOR_DIGEST }

    fn request_operations(&self) -> &'static [&'static str] { &[DECIDE_OPERATION, READ_INTENT_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[] }
    fn event_operations(&self) -> &'static [&'static str] { &[] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            DECIDE_OPERATION => {
                let value = request.downcast_ref::<DecideRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            READ_INTENT_OPERATION => {
                let value = request.downcast_ref::<ReadIntentRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            DECIDE_OPERATION => serde_json::from_value::<DecideResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            READ_INTENT_OPERATION => serde_json::from_value::<ReadIntentResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            DECIDE_OPERATION => serde_json::from_value::<DecideError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            READ_INTENT_OPERATION => serde_json::from_value::<ReadIntentError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, _request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_stream_message(&self, operation: &str, _message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_message(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_domain_error(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_event(&self, operation: &str, _event: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::PluginDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            DECIDE_OPERATION => {
                let request = serde_json::from_value::<DecideRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<ManagementHumanDecide>()?;
                    match handle.invoke_with_context(DECIDE_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            READ_INTENT_OPERATION => {
                let request = serde_json::from_value::<ReadIntentRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<ManagementHumanReadIntent>()?;
                    match handle.invoke_with_context(READ_INTENT_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, _dependency: lenso_kernel::PluginStreamDependencyHandle, operation: String, _request: serde_json::Value, _context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }

    fn publish_host_event(&self, _dependency: lenso_kernel::PluginEventDependencyHandle, operation: String, _event: serde_json::Value, _context: InvocationContext) -> futures::future::LocalBoxFuture<'static, Result<(), RuntimeFailure>> {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
