// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.ui.contribution@1";
pub const DESCRIPTOR_VERSION: &str = "1.3.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:819917f08497881aa5db5d86c9e358a45d3f0f88f3b8087142fe5999e50c7c9a";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const CONTRIBUTION_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const CONTRIBUTION_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const CONTRIBUTION_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const CONTRIBUTION_CONTRACT: CapabilityReference<ContributionClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_contribution { () => { "{\"capability_id\":\"lenso.ui.contribution@1\",\"descriptor_version\":\"1.3.0\",\"operations\":[\"describe_contribution\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_contribution_client {
    () => { "{\"capability_id\":\"lenso.ui.contribution@1\",\"descriptor_version\":\"1.3.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.ui.contribution@1\",\"descriptor_version\":\"1.3.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_contribution_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.ui.contribution@1\",\"descriptor_version\":\"1.3.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_contribution_client {
    () => { "{\"capability_id\":\"lenso.ui.contribution@1\",\"descriptor_version\":\"1.3.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.ui.contribution@1\",\"descriptor_version\":\"1.3.0\",\"cardinality\":\"many\"}") };
}

pub const DESCRIBE_CONTRIBUTION_OPERATION: &str = "describe_contribution";

pub use lenso_contract_runtime::{OptionalValue, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeContributionRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeContributionResponse {
    #[serde(rename = "assets")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub assets: Vec<DescribeContributionResponseAssetsItem>,
    #[serde(rename = "module")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub module: String,
    #[serde(rename = "navigation")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub navigation: DescribeContributionResponseNavigation,
    #[serde(rename = "requirements")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requirements: Vec<DescribeContributionResponseRequirementsItem>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "styles")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub styles: Vec<String>,
    #[serde(rename = "subject")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subject: Option<DescribeContributionResponseSubject>,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
    #[serde(rename = "workspace_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub workspace_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeContributionResponseAssetsItem {
    #[serde(rename = "content_base64")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content_base64: String,
    #[serde(rename = "media_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub media_type: DescribeContributionResponseAssetsItemMediaType,
    #[serde(rename = "path")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub path: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum DescribeContributionResponseAssetsItemMediaType {
    #[serde(rename = "text/css; charset=utf-8")]
    TextCssCharsetUtf,
    #[serde(rename = "text/javascript; charset=utf-8")]
    TextJavascriptCharsetUtf,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeContributionResponseNavigation {
    #[serde(rename = "items")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub items: Vec<DescribeContributionResponseNavigationItemsItem>,
    #[serde(rename = "label")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub label: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeContributionResponseNavigationItemsItem {
    #[serde(rename = "label")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub label: String,
    #[serde(rename = "path")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub path: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeContributionResponseRequirementsItem {
    #[serde(rename = "capability_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub capability_id: String,
    #[serde(rename = "descriptor_version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub descriptor_version: String,
    #[serde(rename = "operations")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub operations: Vec<String>,
    #[serde(rename = "required")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub required: bool,
    #[serde(rename = "service_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub service_id: String,
    #[serde(rename = "source")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source: DescribeContributionResponseRequirementsItemSource,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum DescribeContributionResponseRequirementsItemSource {
    #[serde(rename = "owner")]
    Owner,
    #[serde(rename = "subject")]
    Subject,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeContributionResponseSubject {
    #[serde(rename = "app_id")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub app_id: OptionalValue<String>,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: DescribeContributionResponseSubjectKind,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum DescribeContributionResponseSubjectKind {
    #[serde(rename = "console")]
    Console,
    #[serde(rename = "app")]
    App,
}

#[derive(Clone, Debug, PartialEq)]
pub enum DescribeContributionError {
    ContributionUnavailable,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct Contribution;
impl RequestCapability for Contribution {
    type Request = DescribeContributionRequest;
    type Response = DescribeContributionResponse;
    type DomainError = DescribeContributionError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != DESCRIBE_CONTRIBUTION_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ContributionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).describe_contribution(context, request)
    }
}

impl serde::Serialize for DescribeContributionError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ContributionUnavailable => serializer.serialize_str("contribution_unavailable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for DescribeContributionError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "contribution_unavailable" => Ok(Self::ContributionUnavailable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_describe_contribution_request(value: &DescribeContributionRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_describe_contribution_request(wire: &str) -> Result<DescribeContributionRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_describe_contribution_response(value: &DescribeContributionResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_describe_contribution_response(wire: &str) -> Result<DescribeContributionResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_describe_contribution_error(value: &DescribeContributionError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_describe_contribution_error(wire: &str) -> Result<DescribeContributionError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoContributionDescribeContributionResult {
    fn __lenso_into_result(self) -> Result<Result<DescribeContributionResponse, DescribeContributionError>, RuntimeFailure>;
}
impl __LensoIntoContributionDescribeContributionResult for Result<DescribeContributionResponse, DescribeContributionError> {
    fn __lenso_into_result(self) -> Result<Result<DescribeContributionResponse, DescribeContributionError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoContributionDescribeContributionResult for Result<Result<DescribeContributionResponse, DescribeContributionError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<DescribeContributionResponse, DescribeContributionError>, RuntimeFailure> { self }
}
impl __LensoIntoContributionDescribeContributionResult for Result<DescribeContributionResponse, lenso_plugin_authoring::PluginError<DescribeContributionError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<DescribeContributionResponse, DescribeContributionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoContributionDescribeContributionResult for Result<DescribeContributionResponse, ContributionInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<DescribeContributionResponse, DescribeContributionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ContributionInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ContributionInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait ContributionProvider: fmt::Debug + 'static {
    fn describe_contribution(&self, context: InvocationContext, request: DescribeContributionRequest) -> NativeRequestFuture<Contribution>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_contribution {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportContribution;
        impl $crate::ContributionProvider for $plugin {
        fn describe_contribution(&self, context: __LensoNativeSupportContribution::InvocationContext, request: $crate::DescribeContributionRequest) -> __LensoNativeSupportContribution::NativeRequestFuture<$crate::Contribution> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::describe_contribution(&plugin, context, request).await;
                $crate::__LensoIntoContributionDescribeContributionResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_contribution {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportContribution;
        impl $crate::ContributionProvider for $object {
        fn describe_contribution(&self, context: __LensoNativeSupportContribution::InvocationContext, request: $crate::DescribeContributionRequest) -> __LensoNativeSupportContribution::NativeRequestFuture<$crate::Contribution> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::describe_contribution(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoContributionDescribeContributionResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_contribution {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportContribution;
        impl $crate::ContributionProvider for $object {
        fn describe_contribution(&self, context: __LensoNativeSupportContribution::InvocationContext, request: $crate::DescribeContributionRequest) -> __LensoNativeSupportContribution::NativeRequestFuture<$crate::Contribution> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::ContributionProvider>::describe_contribution(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct ContributionRequestEndpoint { provider: Rc<dyn ContributionProvider> }

#[derive(Debug)]
pub struct ContributionEndpoint<P: ContributionProvider> { provider: Rc<P>, request_endpoint: ContributionRequestEndpoint }
impl<P: ContributionProvider> ContributionEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn ContributionProvider> = provider.clone();
        Self { provider, request_endpoint: ContributionRequestEndpoint { provider: request_provider } }
    }
}

impl<P: ContributionProvider> NativeRequestEndpoint for ContributionEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        DESCRIBE_CONTRIBUTION_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            DESCRIBE_CONTRIBUTION_OPERATION => {
                let Ok(request) = request.downcast::<DescribeContributionRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).describe_contribution(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_contribution {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::ContributionEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_contribution {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_contribution!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct ContributionClient {
    describe_contribution: NativeRequestHandle<Contribution>,
}
impl ContributionClient {
    pub fn new(handle: NativeRequestHandle<Contribution>) -> Self {
        Self { describe_contribution: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn describe_contribution(&self, request: DescribeContributionRequest) -> Result<DescribeContributionResponse, ContributionInvocationError> {
        self.describe_contribution.invoke(DESCRIBE_CONTRIBUTION_OPERATION, request).await
            .map_err(ContributionInvocationError::Runtime)?
            .map_err(ContributionInvocationError::Domain)
    }

    pub async fn describe_contribution_with_context(&self, context: InvocationContext, request: DescribeContributionRequest) -> Result<DescribeContributionResponse, ContributionInvocationError> {
        self.describe_contribution.invoke_with_context(DESCRIBE_CONTRIBUTION_OPERATION, context, request).await
            .map_err(ContributionInvocationError::Runtime)?
            .map_err(ContributionInvocationError::Domain)
    }
}

impl CapabilityClient for ContributionClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            describe_contribution: dependencies.one::<Contribution>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for ContributionClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    describe_contribution: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<Contribution>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ContributionInvocationError {
    Domain(DescribeContributionError),
    Runtime(RuntimeFailure),
}
