import * as stylex from "@stylexjs/stylex";

import { lensoUiTokens as tokens } from "../../lenso-ui-token-refs.stylex";

export const pluginInspectorStyles = stylex.create({
  controlCopy: { display: "grid", gap: 2, minWidth: 0 },
  controlDescription: {
    color: tokens.colorContentTertiary,
    fontSize: 12,
    lineHeight: "18px",
    maxWidth: 600,
  },
  controlRow: {
    alignItems: "center",
    display: "grid",
    gap: tokens.space4,
    gridTemplateColumns: "minmax(0, 1fr) auto",
    minHeight: 32,
  },
  controlSwitchSlot: {
    alignItems: "center",
    display: "flex",
    justifyContent: "center",
    width: 30,
  },
  controlTitle: {
    color: tokens.colorContentPrimary,
    fontSize: 13,
    fontWeight: 500,
  },
  detailRoot: {
    minWidth: 0,
    width: {
      default: "calc(100% - 48px)",
      "@media (max-width: 560px)": "calc(100% - 32px)",
    },
    marginInline: "auto",
    paddingBlockStart: {
      default: 48,
      "@media (max-width: 560px)": 32,
    },
    paddingBlockEnd: {
      default: 64,
      "@media (max-width: 560px)": 48,
    },
  },
  configurationLayout: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    justifyContent: "space-between",
    width: "100%",
  },
  configurationMain: {
    minWidth: 0,
  },
  configurationHeading: {
    alignItems: "center",
    display: "flex",
    gap: tokens.space4,
    justifyContent: "space-between",
    minHeight: 30,
  },
  editor: {
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: { default: 11, "@media (max-width: 720px)": 16 },
    lineHeight: { default: "17px", "@media (max-width: 720px)": "22px" },
    minHeight: 200,
    resize: "vertical",
  },
  editorRoot: { width: "100%" },
  editorActions: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: tokens.space2,
    justifyContent: "flex-end",
  },
  feedback: {
    color: tokens.colorContentTertiary,
    fontSize: 11,
    lineHeight: "16px",
    margin: 0,
    overflowWrap: "anywhere",
  },
  feedbackError: { color: "var(--danger-soft-foreground)" },
  feedbackWarning: { color: "var(--warning-soft-foreground)" },
  field: {
    display: "grid",
    gap: { default: tokens.space3, "@media (max-width: 420px)": 2 },
    gridTemplateColumns: {
      default: "112px minmax(0, 1fr)",
      "@media (max-width: 420px)": "minmax(0, 1fr)",
    },
  },
  fields: { display: "grid", gap: tokens.space2, margin: 0 },
  historyAction: { justifySelf: "start" },
  historyIdentity: { display: "grid", gap: 2, minWidth: 0 },
  historyDescription: {
    color: tokens.colorContentTertiary,
    fontSize: 11,
    lineHeight: "16px",
    margin: 0,
  },
  historyHeader: {
    display: "grid",
    gap: 2,
    paddingBlockEnd: tokens.space3,
  },
  historyList: { display: "grid" },
  historyMeta: {
    color: tokens.colorContentTertiary,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: 10,
    lineHeight: "14px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  historySection: {
    borderLeftColor: tokens.colorBorderTertiary,
    borderLeftStyle: "solid",
    borderLeftWidth: 0,
    display: "grid",
    alignContent: "start",
    minWidth: 0,
    paddingBlock: 20,
    paddingInline: 0,
    "@media (max-width: 1100px)": {
      borderLeftWidth: 0,
      borderTopColor: tokens.colorBorderTertiary,
      borderTopStyle: "solid",
      borderTopWidth: 1,
    },
  },
  historyRow: {
    alignItems: "center",
    borderTopColor: tokens.colorBorderTertiary,
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "grid",
    gap: tokens.space2,
    gridTemplateColumns: "minmax(0, 1fr) auto",
    minHeight: 48,
    paddingBlock: tokens.space2,
  },
  historyTitle: {
    color: tokens.colorContentSecondary,
    fontSize: 11,
    lineHeight: "16px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  detailHeader: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: tokens.space4,
    justifyContent: "space-between",
    minHeight: 56,
    paddingBlock: tokens.space2,
    paddingInline: 0,
  },
  detailIdentity: {
    display: "grid",
    flexBasis: 420,
    flexGrow: 1,
    gap: 6,
    minWidth: 0,
  },
  detailTabs: {
    minWidth: 0,
  },
  detailTabsContainer: {
    marginBlockStart: tokens.space4,
    maxWidth: "100%",
    width: "fit-content",
  },
  detailActions: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    flexShrink: 0,
    gap: tokens.space2,
    justifyContent: "flex-start",
  },
  detailTab: {
    flexShrink: 0,
    width: "auto",
  },
  detailTitle: {
    color: tokens.colorContentPrimary,
    fontSize: 24,
    fontWeight: 600,
    letterSpacing: "-0.02em",
    lineHeight: "30px",
    margin: 0,
    overflowWrap: "anywhere",
  },
  mono: {
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
  },
  secondary: {
    color: tokens.colorContentTertiary,
    fontSize: 11,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  section: {
    display: "grid",
    gap: tokens.space2,
    gridTemplateColumns: "minmax(0, 1fr)",
    minWidth: 0,
    paddingBlock: 20,
    paddingInline: 0,
  },
  sectionTitle: {
    color: tokens.colorContentSecondary,
    fontSize: 14,
    fontWeight: 600,
    lineHeight: "20px",
    margin: 0,
  },
  term: { color: tokens.colorContentTertiary, fontSize: 11 },
  tabPanel: {
    minHeight: 320,
    outline: "none",
  },
  tabPanelFocused: {
    maxWidth: 760,
    width: "100%",
  },
  value: {
    color: tokens.colorContentSecondary,
    fontSize: 12,
    margin: 0,
    overflowWrap: "anywhere",
  },
  statusSummary: {
    color: tokens.colorContentSecondary,
    fontSize: 12,
    lineHeight: "18px",
    marginBlockEnd: 0,
    marginBlockStart: tokens.space2,
  },
});
