// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.console.locale-store@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:12e17314bb062965f7dc7e210c8bde6ccc8e2437db90a16d66db4e53f0027ea6";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const LOCALE_STORE_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const LOCALE_STORE_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const LOCALE_STORE_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const LOCALE_STORE_CONTRACT: CapabilityReference<LocaleStoreClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_locale_store { () => { "{\"capability_id\":\"lenso.console.locale-store@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"read_default\",\"read_preference\",\"write_default\",\"write_preference\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_locale_store_client {
    () => { "{\"capability_id\":\"lenso.console.locale-store@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.console.locale-store@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_locale_store_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.console.locale-store@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_locale_store_client {
    () => { "{\"capability_id\":\"lenso.console.locale-store@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.console.locale-store@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const READ_DEFAULT_OPERATION: &str = "read_default";
pub const READ_PREFERENCE_OPERATION: &str = "read_preference";
pub const WRITE_DEFAULT_OPERATION: &str = "write_default";
pub const WRITE_PREFERENCE_OPERATION: &str = "write_preference";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Copy, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadDefaultRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadDefaultResponse {
    #[serde(rename = "locale")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub locale: Option<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadDefaultError {
    Conflict,
    Denied,
    Invalid,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadPreferenceRequest {
    #[serde(rename = "authority")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub authority: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadPreferenceResponse {
    #[serde(rename = "preference")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub preference: ReadPreferenceResponsePreference,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ReadPreferenceResponsePreference {
    #[serde(rename = "global")]
    Global,
    #[serde(rename = "en")]
    En,
    #[serde(rename = "zh-CN")]
    ZhCN,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadPreferenceError {
    Conflict,
    Denied,
    Invalid,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct WriteDefaultRequest {
    #[serde(rename = "locale")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub locale: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct WriteDefaultResponse {
    #[serde(rename = "locale")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub locale: Option<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum WriteDefaultError {
    Conflict,
    Denied,
    Invalid,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct WritePreferenceRequest {
    #[serde(rename = "authority")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub authority: String,
    #[serde(rename = "preference")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub preference: WritePreferenceRequestPreference,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum WritePreferenceRequestPreference {
    #[serde(rename = "global")]
    Global,
    #[serde(rename = "en")]
    En,
    #[serde(rename = "zh-CN")]
    ZhCN,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct WritePreferenceResponse {
    #[serde(rename = "preference")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub preference: WritePreferenceResponsePreference,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum WritePreferenceResponsePreference {
    #[serde(rename = "global")]
    Global,
    #[serde(rename = "en")]
    En,
    #[serde(rename = "zh-CN")]
    ZhCN,
}

#[derive(Clone, Debug, PartialEq)]
pub enum WritePreferenceError {
    Conflict,
    Denied,
    Invalid,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct LocaleStoreReadDefault;
impl RequestCapability for LocaleStoreReadDefault {
    type Request = ReadDefaultRequest;
    type Response = ReadDefaultResponse;
    type DomainError = ReadDefaultError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_DEFAULT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<LocaleStoreRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read_default(context, request)
    }
}

#[derive(Debug)]
pub struct LocaleStoreReadPreference;
impl RequestCapability for LocaleStoreReadPreference {
    type Request = ReadPreferenceRequest;
    type Response = ReadPreferenceResponse;
    type DomainError = ReadPreferenceError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_PREFERENCE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<LocaleStoreRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read_preference(context, request)
    }
}

#[derive(Debug)]
pub struct LocaleStoreWriteDefault;
impl RequestCapability for LocaleStoreWriteDefault {
    type Request = WriteDefaultRequest;
    type Response = WriteDefaultResponse;
    type DomainError = WriteDefaultError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != WRITE_DEFAULT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<LocaleStoreRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).write_default(context, request)
    }
}

#[derive(Debug)]
pub struct LocaleStoreWritePreference;
impl RequestCapability for LocaleStoreWritePreference {
    type Request = WritePreferenceRequest;
    type Response = WritePreferenceResponse;
    type DomainError = WritePreferenceError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != WRITE_PREFERENCE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<LocaleStoreRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).write_preference(context, request)
    }
}

impl serde::Serialize for ReadDefaultError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::Denied => serializer.serialize_str("denied"),
            Self::Invalid => serializer.serialize_str("invalid"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadDefaultError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "denied" => Ok(Self::Denied),
                "invalid" => Ok(Self::Invalid),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReadPreferenceError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::Denied => serializer.serialize_str("denied"),
            Self::Invalid => serializer.serialize_str("invalid"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadPreferenceError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "denied" => Ok(Self::Denied),
                "invalid" => Ok(Self::Invalid),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for WriteDefaultError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::Denied => serializer.serialize_str("denied"),
            Self::Invalid => serializer.serialize_str("invalid"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for WriteDefaultError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "denied" => Ok(Self::Denied),
                "invalid" => Ok(Self::Invalid),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for WritePreferenceError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::Denied => serializer.serialize_str("denied"),
            Self::Invalid => serializer.serialize_str("invalid"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for WritePreferenceError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "denied" => Ok(Self::Denied),
                "invalid" => Ok(Self::Invalid),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_read_default_request(value: &ReadDefaultRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_default_request(wire: &str) -> Result<ReadDefaultRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_default_response(value: &ReadDefaultResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_default_response(wire: &str) -> Result<ReadDefaultResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_default_error(value: &ReadDefaultError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_default_error(wire: &str) -> Result<ReadDefaultError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_read_preference_request(value: &ReadPreferenceRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_preference_request(wire: &str) -> Result<ReadPreferenceRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_preference_response(value: &ReadPreferenceResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_preference_response(wire: &str) -> Result<ReadPreferenceResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_preference_error(value: &ReadPreferenceError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_preference_error(wire: &str) -> Result<ReadPreferenceError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_write_default_request(value: &WriteDefaultRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_write_default_request(wire: &str) -> Result<WriteDefaultRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_write_default_response(value: &WriteDefaultResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_write_default_response(wire: &str) -> Result<WriteDefaultResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_write_default_error(value: &WriteDefaultError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_write_default_error(wire: &str) -> Result<WriteDefaultError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_write_preference_request(value: &WritePreferenceRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_write_preference_request(wire: &str) -> Result<WritePreferenceRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_write_preference_response(value: &WritePreferenceResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_write_preference_response(wire: &str) -> Result<WritePreferenceResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_write_preference_error(value: &WritePreferenceError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_write_preference_error(wire: &str) -> Result<WritePreferenceError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoLocaleStoreReadDefaultResult {
    fn __lenso_into_result(self) -> Result<Result<ReadDefaultResponse, ReadDefaultError>, RuntimeFailure>;
}
impl __LensoIntoLocaleStoreReadDefaultResult for Result<ReadDefaultResponse, ReadDefaultError> {
    fn __lenso_into_result(self) -> Result<Result<ReadDefaultResponse, ReadDefaultError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoLocaleStoreReadDefaultResult for Result<Result<ReadDefaultResponse, ReadDefaultError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReadDefaultResponse, ReadDefaultError>, RuntimeFailure> { self }
}
impl __LensoIntoLocaleStoreReadDefaultResult for Result<ReadDefaultResponse, lenso_plugin_authoring::PluginError<ReadDefaultError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReadDefaultResponse, ReadDefaultError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoLocaleStoreReadDefaultResult for Result<ReadDefaultResponse, LocaleStoreReadDefaultInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReadDefaultResponse, ReadDefaultError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(LocaleStoreReadDefaultInvocationError::Domain(error)) => Ok(Err(error)),
            Err(LocaleStoreReadDefaultInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoLocaleStoreReadPreferenceResult {
    fn __lenso_into_result(self) -> Result<Result<ReadPreferenceResponse, ReadPreferenceError>, RuntimeFailure>;
}
impl __LensoIntoLocaleStoreReadPreferenceResult for Result<ReadPreferenceResponse, ReadPreferenceError> {
    fn __lenso_into_result(self) -> Result<Result<ReadPreferenceResponse, ReadPreferenceError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoLocaleStoreReadPreferenceResult for Result<Result<ReadPreferenceResponse, ReadPreferenceError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReadPreferenceResponse, ReadPreferenceError>, RuntimeFailure> { self }
}
impl __LensoIntoLocaleStoreReadPreferenceResult for Result<ReadPreferenceResponse, lenso_plugin_authoring::PluginError<ReadPreferenceError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReadPreferenceResponse, ReadPreferenceError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoLocaleStoreReadPreferenceResult for Result<ReadPreferenceResponse, LocaleStoreReadPreferenceInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReadPreferenceResponse, ReadPreferenceError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(LocaleStoreReadPreferenceInvocationError::Domain(error)) => Ok(Err(error)),
            Err(LocaleStoreReadPreferenceInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoLocaleStoreWriteDefaultResult {
    fn __lenso_into_result(self) -> Result<Result<WriteDefaultResponse, WriteDefaultError>, RuntimeFailure>;
}
impl __LensoIntoLocaleStoreWriteDefaultResult for Result<WriteDefaultResponse, WriteDefaultError> {
    fn __lenso_into_result(self) -> Result<Result<WriteDefaultResponse, WriteDefaultError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoLocaleStoreWriteDefaultResult for Result<Result<WriteDefaultResponse, WriteDefaultError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<WriteDefaultResponse, WriteDefaultError>, RuntimeFailure> { self }
}
impl __LensoIntoLocaleStoreWriteDefaultResult for Result<WriteDefaultResponse, lenso_plugin_authoring::PluginError<WriteDefaultError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<WriteDefaultResponse, WriteDefaultError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoLocaleStoreWriteDefaultResult for Result<WriteDefaultResponse, LocaleStoreWriteDefaultInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<WriteDefaultResponse, WriteDefaultError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(LocaleStoreWriteDefaultInvocationError::Domain(error)) => Ok(Err(error)),
            Err(LocaleStoreWriteDefaultInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoLocaleStoreWritePreferenceResult {
    fn __lenso_into_result(self) -> Result<Result<WritePreferenceResponse, WritePreferenceError>, RuntimeFailure>;
}
impl __LensoIntoLocaleStoreWritePreferenceResult for Result<WritePreferenceResponse, WritePreferenceError> {
    fn __lenso_into_result(self) -> Result<Result<WritePreferenceResponse, WritePreferenceError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoLocaleStoreWritePreferenceResult for Result<Result<WritePreferenceResponse, WritePreferenceError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<WritePreferenceResponse, WritePreferenceError>, RuntimeFailure> { self }
}
impl __LensoIntoLocaleStoreWritePreferenceResult for Result<WritePreferenceResponse, lenso_plugin_authoring::PluginError<WritePreferenceError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<WritePreferenceResponse, WritePreferenceError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoLocaleStoreWritePreferenceResult for Result<WritePreferenceResponse, LocaleStoreWritePreferenceInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<WritePreferenceResponse, WritePreferenceError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(LocaleStoreWritePreferenceInvocationError::Domain(error)) => Ok(Err(error)),
            Err(LocaleStoreWritePreferenceInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait LocaleStoreProvider: fmt::Debug + 'static {
    fn read_default(&self, context: InvocationContext, request: ReadDefaultRequest) -> NativeRequestFuture<LocaleStoreReadDefault>;
    fn read_preference(&self, context: InvocationContext, request: ReadPreferenceRequest) -> NativeRequestFuture<LocaleStoreReadPreference>;
    fn write_default(&self, context: InvocationContext, request: WriteDefaultRequest) -> NativeRequestFuture<LocaleStoreWriteDefault>;
    fn write_preference(&self, context: InvocationContext, request: WritePreferenceRequest) -> NativeRequestFuture<LocaleStoreWritePreference>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_locale_store {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportLocaleStore;
        impl $crate::LocaleStoreProvider for $plugin {
        fn read_default(&self, context: __LensoNativeSupportLocaleStore::InvocationContext, request: $crate::ReadDefaultRequest) -> __LensoNativeSupportLocaleStore::NativeRequestFuture<$crate::LocaleStoreReadDefault> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::read_default(&plugin, context, request).await;
                $crate::__LensoIntoLocaleStoreReadDefaultResult::__lenso_into_result(result)
            })
        }
        fn read_preference(&self, context: __LensoNativeSupportLocaleStore::InvocationContext, request: $crate::ReadPreferenceRequest) -> __LensoNativeSupportLocaleStore::NativeRequestFuture<$crate::LocaleStoreReadPreference> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::read_preference(&plugin, context, request).await;
                $crate::__LensoIntoLocaleStoreReadPreferenceResult::__lenso_into_result(result)
            })
        }
        fn write_default(&self, context: __LensoNativeSupportLocaleStore::InvocationContext, request: $crate::WriteDefaultRequest) -> __LensoNativeSupportLocaleStore::NativeRequestFuture<$crate::LocaleStoreWriteDefault> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::write_default(&plugin, context, request).await;
                $crate::__LensoIntoLocaleStoreWriteDefaultResult::__lenso_into_result(result)
            })
        }
        fn write_preference(&self, context: __LensoNativeSupportLocaleStore::InvocationContext, request: $crate::WritePreferenceRequest) -> __LensoNativeSupportLocaleStore::NativeRequestFuture<$crate::LocaleStoreWritePreference> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::write_preference(&plugin, context, request).await;
                $crate::__LensoIntoLocaleStoreWritePreferenceResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_locale_store {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportLocaleStore;
        impl $crate::LocaleStoreProvider for $object {
        fn read_default(&self, context: __LensoNativeSupportLocaleStore::InvocationContext, request: $crate::ReadDefaultRequest) -> __LensoNativeSupportLocaleStore::NativeRequestFuture<$crate::LocaleStoreReadDefault> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::read_default(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoLocaleStoreReadDefaultResult::__lenso_into_result(result)
            })
        }
        fn read_preference(&self, context: __LensoNativeSupportLocaleStore::InvocationContext, request: $crate::ReadPreferenceRequest) -> __LensoNativeSupportLocaleStore::NativeRequestFuture<$crate::LocaleStoreReadPreference> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::read_preference(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoLocaleStoreReadPreferenceResult::__lenso_into_result(result)
            })
        }
        fn write_default(&self, context: __LensoNativeSupportLocaleStore::InvocationContext, request: $crate::WriteDefaultRequest) -> __LensoNativeSupportLocaleStore::NativeRequestFuture<$crate::LocaleStoreWriteDefault> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::write_default(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoLocaleStoreWriteDefaultResult::__lenso_into_result(result)
            })
        }
        fn write_preference(&self, context: __LensoNativeSupportLocaleStore::InvocationContext, request: $crate::WritePreferenceRequest) -> __LensoNativeSupportLocaleStore::NativeRequestFuture<$crate::LocaleStoreWritePreference> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::write_preference(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoLocaleStoreWritePreferenceResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_locale_store {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportLocaleStore;
        impl $crate::LocaleStoreProvider for $object {
        fn read_default(&self, context: __LensoNativeSupportLocaleStore::InvocationContext, request: $crate::ReadDefaultRequest) -> __LensoNativeSupportLocaleStore::NativeRequestFuture<$crate::LocaleStoreReadDefault> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::LocaleStoreProvider>::read_default(plugin.as_ref(), context, request).await
            })
        }
        fn read_preference(&self, context: __LensoNativeSupportLocaleStore::InvocationContext, request: $crate::ReadPreferenceRequest) -> __LensoNativeSupportLocaleStore::NativeRequestFuture<$crate::LocaleStoreReadPreference> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::LocaleStoreProvider>::read_preference(plugin.as_ref(), context, request).await
            })
        }
        fn write_default(&self, context: __LensoNativeSupportLocaleStore::InvocationContext, request: $crate::WriteDefaultRequest) -> __LensoNativeSupportLocaleStore::NativeRequestFuture<$crate::LocaleStoreWriteDefault> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::LocaleStoreProvider>::write_default(plugin.as_ref(), context, request).await
            })
        }
        fn write_preference(&self, context: __LensoNativeSupportLocaleStore::InvocationContext, request: $crate::WritePreferenceRequest) -> __LensoNativeSupportLocaleStore::NativeRequestFuture<$crate::LocaleStoreWritePreference> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::LocaleStoreProvider>::write_preference(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct LocaleStoreRequestEndpoint { provider: Rc<dyn LocaleStoreProvider> }

#[derive(Debug)]
pub struct LocaleStoreEndpoint<P: LocaleStoreProvider> { provider: Rc<P>, request_endpoint: LocaleStoreRequestEndpoint }
impl<P: LocaleStoreProvider> LocaleStoreEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn LocaleStoreProvider> = provider.clone();
        Self { provider, request_endpoint: LocaleStoreRequestEndpoint { provider: request_provider } }
    }
}

impl<P: LocaleStoreProvider> NativeRequestEndpoint for LocaleStoreEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        READ_DEFAULT_OPERATION,
        READ_PREFERENCE_OPERATION,
        WRITE_DEFAULT_OPERATION,
        WRITE_PREFERENCE_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            READ_DEFAULT_OPERATION => {
                let Ok(request) = request.downcast::<ReadDefaultRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read_default(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            READ_PREFERENCE_OPERATION => {
                let Ok(request) = request.downcast::<ReadPreferenceRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read_preference(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            WRITE_DEFAULT_OPERATION => {
                let Ok(request) = request.downcast::<WriteDefaultRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).write_default(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            WRITE_PREFERENCE_OPERATION => {
                let Ok(request) = request.downcast::<WritePreferenceRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).write_preference(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_locale_store {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::LocaleStoreEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_locale_store {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_locale_store!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct LocaleStoreClient {
    read_default: NativeRequestHandle<LocaleStoreReadDefault>,
    read_preference: NativeRequestHandle<LocaleStoreReadPreference>,
    write_default: NativeRequestHandle<LocaleStoreWriteDefault>,
    write_preference: NativeRequestHandle<LocaleStoreWritePreference>,
}
impl LocaleStoreClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn read_default(&self, request: ReadDefaultRequest) -> Result<ReadDefaultResponse, LocaleStoreReadDefaultInvocationError> {
        self.read_default.invoke(READ_DEFAULT_OPERATION, request).await
            .map_err(LocaleStoreReadDefaultInvocationError::Runtime)?
            .map_err(LocaleStoreReadDefaultInvocationError::Domain)
    }

    pub async fn read_default_with_context(&self, context: InvocationContext, request: ReadDefaultRequest) -> Result<ReadDefaultResponse, LocaleStoreReadDefaultInvocationError> {
        self.read_default.invoke_with_context(READ_DEFAULT_OPERATION, context, request).await
            .map_err(LocaleStoreReadDefaultInvocationError::Runtime)?
            .map_err(LocaleStoreReadDefaultInvocationError::Domain)
    }

    pub async fn read_preference(&self, request: ReadPreferenceRequest) -> Result<ReadPreferenceResponse, LocaleStoreReadPreferenceInvocationError> {
        self.read_preference.invoke(READ_PREFERENCE_OPERATION, request).await
            .map_err(LocaleStoreReadPreferenceInvocationError::Runtime)?
            .map_err(LocaleStoreReadPreferenceInvocationError::Domain)
    }

    pub async fn read_preference_with_context(&self, context: InvocationContext, request: ReadPreferenceRequest) -> Result<ReadPreferenceResponse, LocaleStoreReadPreferenceInvocationError> {
        self.read_preference.invoke_with_context(READ_PREFERENCE_OPERATION, context, request).await
            .map_err(LocaleStoreReadPreferenceInvocationError::Runtime)?
            .map_err(LocaleStoreReadPreferenceInvocationError::Domain)
    }

    pub async fn write_default(&self, request: WriteDefaultRequest) -> Result<WriteDefaultResponse, LocaleStoreWriteDefaultInvocationError> {
        self.write_default.invoke(WRITE_DEFAULT_OPERATION, request).await
            .map_err(LocaleStoreWriteDefaultInvocationError::Runtime)?
            .map_err(LocaleStoreWriteDefaultInvocationError::Domain)
    }

    pub async fn write_default_with_context(&self, context: InvocationContext, request: WriteDefaultRequest) -> Result<WriteDefaultResponse, LocaleStoreWriteDefaultInvocationError> {
        self.write_default.invoke_with_context(WRITE_DEFAULT_OPERATION, context, request).await
            .map_err(LocaleStoreWriteDefaultInvocationError::Runtime)?
            .map_err(LocaleStoreWriteDefaultInvocationError::Domain)
    }

    pub async fn write_preference(&self, request: WritePreferenceRequest) -> Result<WritePreferenceResponse, LocaleStoreWritePreferenceInvocationError> {
        self.write_preference.invoke(WRITE_PREFERENCE_OPERATION, request).await
            .map_err(LocaleStoreWritePreferenceInvocationError::Runtime)?
            .map_err(LocaleStoreWritePreferenceInvocationError::Domain)
    }

    pub async fn write_preference_with_context(&self, context: InvocationContext, request: WritePreferenceRequest) -> Result<WritePreferenceResponse, LocaleStoreWritePreferenceInvocationError> {
        self.write_preference.invoke_with_context(WRITE_PREFERENCE_OPERATION, context, request).await
            .map_err(LocaleStoreWritePreferenceInvocationError::Runtime)?
            .map_err(LocaleStoreWritePreferenceInvocationError::Domain)
    }
}

impl CapabilityClient for LocaleStoreClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            read_default: dependencies.one::<LocaleStoreReadDefault>()?,
            read_preference: dependencies.one::<LocaleStoreReadPreference>()?,
            write_default: dependencies.one::<LocaleStoreWriteDefault>()?,
            write_preference: dependencies.one::<LocaleStoreWritePreference>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for LocaleStoreClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    read_default: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<LocaleStoreReadDefault>()?,
                    read_preference: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<LocaleStoreReadPreference>()?,
                    write_default: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<LocaleStoreWriteDefault>()?,
                    write_preference: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<LocaleStoreWritePreference>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum LocaleStoreReadDefaultInvocationError {
    Domain(ReadDefaultError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum LocaleStoreReadPreferenceInvocationError {
    Domain(ReadPreferenceError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum LocaleStoreWriteDefaultInvocationError {
    Domain(WriteDefaultError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum LocaleStoreWritePreferenceInvocationError {
    Domain(WritePreferenceError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct LocaleStoreGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> LocaleStoreGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[READ_DEFAULT_OPERATION, READ_PREFERENCE_OPERATION, WRITE_DEFAULT_OPERATION, WRITE_PREFERENCE_OPERATION], &[], &[])
            .map(|capability| Self { capability })
    }

    pub fn read_default(&self, request: &ReadDefaultRequest) -> Result<ReadDefaultResponse, lenso_guest_sdk::GuestError<ReadDefaultError>> {
        self.capability.request(READ_DEFAULT_OPERATION, request)
    }

    pub fn read_preference(&self, request: &ReadPreferenceRequest) -> Result<ReadPreferenceResponse, lenso_guest_sdk::GuestError<ReadPreferenceError>> {
        self.capability.request(READ_PREFERENCE_OPERATION, request)
    }

    pub fn write_default(&self, request: &WriteDefaultRequest) -> Result<WriteDefaultResponse, lenso_guest_sdk::GuestError<WriteDefaultError>> {
        self.capability.request(WRITE_DEFAULT_OPERATION, request)
    }

    pub fn write_preference(&self, request: &WritePreferenceRequest) -> Result<WritePreferenceResponse, lenso_guest_sdk::GuestError<WritePreferenceError>> {
        self.capability.request(WRITE_PREFERENCE_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct LocaleStoreJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for LocaleStoreJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn descriptor_digest(&self) -> &'static str { DESCRIPTOR_DIGEST }

    fn request_operations(&self) -> &'static [&'static str] { &[READ_DEFAULT_OPERATION, READ_PREFERENCE_OPERATION, WRITE_DEFAULT_OPERATION, WRITE_PREFERENCE_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[] }
    fn event_operations(&self) -> &'static [&'static str] { &[] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            READ_DEFAULT_OPERATION => {
                let value = request.downcast_ref::<ReadDefaultRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            READ_PREFERENCE_OPERATION => {
                let value = request.downcast_ref::<ReadPreferenceRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            WRITE_DEFAULT_OPERATION => {
                let value = request.downcast_ref::<WriteDefaultRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            WRITE_PREFERENCE_OPERATION => {
                let value = request.downcast_ref::<WritePreferenceRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            READ_DEFAULT_OPERATION => serde_json::from_value::<ReadDefaultResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            READ_PREFERENCE_OPERATION => serde_json::from_value::<ReadPreferenceResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            WRITE_DEFAULT_OPERATION => serde_json::from_value::<WriteDefaultResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            WRITE_PREFERENCE_OPERATION => serde_json::from_value::<WritePreferenceResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            READ_DEFAULT_OPERATION => serde_json::from_value::<ReadDefaultError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            READ_PREFERENCE_OPERATION => serde_json::from_value::<ReadPreferenceError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            WRITE_DEFAULT_OPERATION => serde_json::from_value::<WriteDefaultError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            WRITE_PREFERENCE_OPERATION => serde_json::from_value::<WritePreferenceError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, _request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_stream_message(&self, operation: &str, _message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_message(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_domain_error(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_event(&self, operation: &str, _event: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::PluginDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            READ_DEFAULT_OPERATION => {
                let request = serde_json::from_value::<ReadDefaultRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<LocaleStoreReadDefault>()?;
                    match handle.invoke_with_context(READ_DEFAULT_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            READ_PREFERENCE_OPERATION => {
                let request = serde_json::from_value::<ReadPreferenceRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<LocaleStoreReadPreference>()?;
                    match handle.invoke_with_context(READ_PREFERENCE_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            WRITE_DEFAULT_OPERATION => {
                let request = serde_json::from_value::<WriteDefaultRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<LocaleStoreWriteDefault>()?;
                    match handle.invoke_with_context(WRITE_DEFAULT_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            WRITE_PREFERENCE_OPERATION => {
                let request = serde_json::from_value::<WritePreferenceRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<LocaleStoreWritePreference>()?;
                    match handle.invoke_with_context(WRITE_PREFERENCE_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, _dependency: lenso_kernel::PluginStreamDependencyHandle, operation: String, _request: serde_json::Value, _context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }

    fn publish_host_event(&self, _dependency: lenso_kernel::PluginEventDependencyHandle, operation: String, _event: serde_json::Value, _context: InvocationContext) -> futures::future::LocalBoxFuture<'static, Result<(), RuntimeFailure>> {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
