import * as stylex from "@stylexjs/stylex";

export const profilesPageStyles = stylex.create({
  page: {
    minHeight: "100%",
    width: "100%",
    backgroundColor: "var(--background)",
    color: "var(--foreground)",
  },
  activeContext: {
    display: "flex",
    flexWrap: "wrap",
    gap: "4px 12px",
    margin: "0 0 20px",
    fontSize: 12,
    lineHeight: "18px",
    color: "var(--muted)",
  },
  metadata: {
    fontSize: 11,
    lineHeight: "18px",
    color: "var(--muted)",
    overflowWrap: "anywhere",
    minWidth: 0,
  },
  description: {
    margin: 0,
    color: "var(--muted)",
    fontSize: 12,
    lineHeight: "19px",
    overflowWrap: "anywhere",
  },
  createButton: { textDecoration: "none" },
  toolbar: {
    marginBlockStart: 24,
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    marginBlockEnd: 8,
  },
  list: {
    padding: 12,
    marginInline: -12,
    overflow: "visible",
    borderRadius: "calc(var(--radius) * 2)",
  },
  rows: {
    padding: 0,
    marginBlock: 0,
    marginInline: -12,
    listStyle: "none",
    display: "grid",
  },
  row: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 12,
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--default-hover)",
    },
    paddingInline: 12,
    paddingBlock: 12,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "var(--separator)",
    ":last-child": { borderBottomWidth: 0 },
  },
  profileLink: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    gap: 2,
    flex: "1 1 180px",
    minWidth: 0,
    color: "inherit",
    textDecorationLine: { default: "none", ":hover": "none" },
  },
  search: {
    minWidth: 0,
    maxWidth: "100%",
    flex: "0 1 320px",
    "@media (max-width: 560px)": { flex: "1 1 100%" },
  },
  empty: {
    display: "grid",
    justifyItems: "start",
    gap: 8,
    padding: 24,
    border: "1px solid var(--separator)",
    borderRadius: 8,
    color: "var(--muted)",
    fontSize: 13,
    lineHeight: "20px",
  },
  rowIcon: {
    width: 30,
    height: 30,
    flexShrink: 0,
    display: "grid",
    placeItems: "center",
    borderRadius: 7,
    backgroundColor: "var(--surface-secondary)",
    color: "var(--muted)",
  },
  nameRow: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: 8 },
  name: {
    fontSize: 13,
    lineHeight: "20px",
    fontWeight: 500,
    overflowWrap: "anywhere",
  },
  badge: {
    fontSize: 11,
    lineHeight: "18px",
    color: "var(--muted)",
    backgroundColor: "var(--surface-secondary)",
    borderRadius: 999,
    padding: "1px 7px",
  },
  actions: {
    display: "flex",
    gap: 4,
    marginInlineStart: "auto",
    alignItems: "center",
  },
  resultCount: {
    fontSize: 12,
    color: "var(--muted)",
    margin: "0 0 10px",
  },
  breadcrumb: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    fontSize: 12,
    color: "var(--muted)",
  },
  guard: {
    position: "sticky",
    top: 0,
    zIndex: 5,
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
    backgroundColor: "var(--surface)",
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--separator)",
    marginBlockStart: 16,
    fontSize: 13,
  },
});
