import * as stylex from "@stylexjs/stylex";

export const sessionStyles = stylex.create({
  root: {
    alignItems: "center",
    backgroundColor: "var(--color-surface-primary)",
    color: "var(--color-content-primary)",
    display: "flex",
    justifyContent: "center",
    minHeight: "100dvh",
    boxSizing: "border-box",
    paddingBlock: "48px",
    paddingInline: "24px",
  },
  panel: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
    width: "304px",
    maxWidth: "100%",
    minWidth: 0,
  },
  header: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: "10px",
    textAlign: "start",
  },
  brand: {
    alignItems: "center",
    display: "flex",
    gap: "8px",
    marginBottom: 0,
    fontSize: "15px",
    fontWeight: 600,
    letterSpacing: "-0.02em",
  },
  logo: { width: "28px", height: "28px", borderRadius: "6px" },
  title: {
    fontSize: "20px",
    fontWeight: 500,
    lineHeight: 1.3,
    letterSpacing: "-0.035em",
    margin: 0,
  },
  muted: {
    color: "var(--color-content-secondary)",
    fontSize: "13px",
    lineHeight: 1.6,
    margin: 0,
  },
  methods: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    minWidth: 0,
  },
  field: { display: "flex", flexDirection: "column", gap: "6px", minWidth: 0 },
  label: {
    color: "var(--color-content-secondary)",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "16px",
  },
  input: { maxWidth: "100%", width: "100%" },
  action: { width: "100%" },
  submit: { marginTop: "4px" },
  divider: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    color: "var(--color-content-secondary)",
    fontSize: "12px",
    marginBlock: "4px",
    "::before": {
      content: '""',
      height: "1px",
      backgroundColor: "var(--color-border-primary)",
      flexGrow: 1,
    },
    "::after": {
      content: '""',
      height: "1px",
      backgroundColor: "var(--color-border-primary)",
      flexGrow: 1,
    },
  },
  error: {
    color: "var(--color-content-primary)",
    fontSize: "13px",
    lineHeight: 1.5,
    margin: 0,
    padding: "12px",
    backgroundColor: "var(--color-surface-secondary)",
    borderRadius: "8px",
  },
});
