import { tokens } from "@lenso/console-tokens/tokens.stylex";
/* eslint-disable func-style, sort-keys */
import * as stylex from "@stylexjs/stylex";

export const statusStyles = stylex.create({
  statusScreen: {
    alignItems: "center",
    backgroundColor: tokens.canvas,
    color: tokens.foreground,
    display: "grid",
    justifyItems: "center",
    minHeight: "100vh",
    paddingInline: tokens.space4,
  },
  statusScreenPadded: { padding: tokens.space6 },
  statusScreenMessage: { color: tokens.foregroundSecondary, fontSize: 13 },
  loginScreen: {
    alignItems: "stretch",
    gridTemplateColumns: "432px minmax(0, 1fr)",
    justifyItems: "stretch",
    paddingInline: 0,
    "@media (max-width: 800px)": { gridTemplateColumns: "minmax(0, 1fr)" },
  },
  loginContext: {
    backgroundColor: tokens.sidebar,
    borderRightColor: tokens.lineSubtle,
    borderRightStyle: "solid",
    borderRightWidth: 1,
    padding: 40,
    "@media (max-width: 800px)": { display: "none" },
  },
  loginBrand: {
    alignItems: "center",
    display: "flex",
    fontSize: 12,
    fontWeight: 500,
    gap: 12,
    lineHeight: "16px",
  },
  loginBrandMark: {
    backgroundColor: tokens.foreground,
    borderRadius: 4,
    height: 16,
    width: 16,
  },
  loginIdentity: { marginBlockStart: 32 },
  loginIdentityName: { fontSize: 16, fontWeight: 600, lineHeight: "24px" },
  loginIdentityEnvironment: {
    color: tokens.foregroundSecondary,
    fontSize: 12,
    lineHeight: "20px",
    marginBlockStart: 12,
  },
  loginAccessDetails: {
    borderTopColor: tokens.lineSubtle,
    borderTopStyle: "solid",
    borderTopWidth: 1,
    marginBlockStart: 32,
  },
  loginAccessRow: {
    alignItems: "center",
    borderBottomColor: tokens.lineSubtle,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    fontSize: 11,
    height: 48,
    justifyContent: "space-between",
  },
  loginAccessLabel: { color: tokens.foregroundTertiary },
  loginAccessValue: {
    color: tokens.foregroundSecondary,
    fontFamily: tokens.fontCode,
    fontSize: 10,
  },
  loginPane: {
    alignItems: "center",
    display: "flex",
    justifyContent: "center",
    minWidth: 0,
    padding: 32,
  },
  loginCard: { width: "100%", maxWidth: 384 },
  loginTitle: { fontSize: 20, fontWeight: 600, lineHeight: "28px" },
  loginDescription: {
    color: tokens.foregroundSecondary,
    fontSize: 12,
    lineHeight: "20px",
    marginBlockStart: 8,
  },
  loginForm: { display: "grid", gap: 16, marginBlockStart: 32 },
  loginLabel: {
    color: tokens.foregroundSecondary,
    display: "grid",
    fontSize: 11,
    gap: 8,
    lineHeight: "16px",
  },
  loginPasswordControl: { position: "relative" },
  loginPasswordInput: { paddingInlineEnd: 54 },
  loginPasswordToggle: {
    color: tokens.foregroundSecondary,
    fontFamily: "inherit",
    fontSize: 10,
    height: "100%",
    paddingInline: 10,
    position: "absolute",
    right: 0,
    top: 0,
    ":focus-visible": {
      outlineColor: tokens.focusRing,
      outlineOffset: -2,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  loginAlternative: {
    borderTopColor: tokens.lineSubtle,
    borderTopStyle: "solid",
    borderTopWidth: 1,
    marginBlockStart: 32,
    paddingBlockStart: 12,
  },
  statusCard: {
    backgroundColor: tokens.panel,
    borderColor: tokens.line,
    borderRadius: tokens.radiusPanel,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: tokens.shadowPanel,
    padding: tokens.space5,
    width: "100%",
  },
  statusCardNarrow: { maxWidth: 384 },
  statusCardWide: { maxWidth: 768 },
  statusCardOverlay: {
    borderRadius: tokens.radiusPopover,
    maxWidth: 960,
    overflow: "hidden",
  },
  statusCopy: { display: "grid", gap: tokens.space1 },
  statusEyebrow: {
    color: tokens.foregroundTertiary,
    fontSize: 10,
    fontWeight: 600,
    letterSpacing: "0.18em",
    textTransform: "uppercase",
  },
  statusTitle: { fontSize: 18, fontWeight: 600, marginBlockStart: 4 },
  statusTitleLarge: { fontSize: 24, fontWeight: 600, marginBlockStart: 4 },
  statusDescription: {
    color: tokens.foregroundSecondary,
    fontSize: 13,
    lineHeight: 1.5,
    marginBlockStart: 8,
  },
  statusError: {
    color: tokens.toneErrorForeground,
    fontSize: 12,
    marginBlockStart: 16,
  },
  statusForm: { display: "grid", gap: tokens.space3, marginBlockStart: 20 },
  statusLabel: {
    color: tokens.foregroundSecondary,
    display: "grid",
    fontSize: 12,
    fontWeight: 500,
    gap: 6,
  },
  statusInput: {
    backgroundColor: tokens.control,
    borderColor: tokens.line,
    borderRadius: tokens.radiusControl,
    borderStyle: "solid",
    borderWidth: 1,
    color: tokens.foreground,
    fontFamily: "inherit",
    fontSize: 14,
    height: 36,
    minWidth: 0,
    outline: "none",
    paddingInline: 12,
    transitionDuration: "120ms",
    transitionProperty: "background-color, border-color",
    transitionTimingFunction: "ease",
    width: "100%",
    "::placeholder": { color: tokens.foregroundTertiary },
    ":focus-visible": {
      backgroundColor: tokens.controlHover,
      borderColor: tokens.accent,
      outlineColor: tokens.focusRing,
      outlineOffset: 1,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  statusButtonFull: { width: "100%" },
  statusButtonSpaced: { marginBlockStart: 8, width: "100%" },
  statusPre: {
    backgroundColor: tokens.control,
    borderColor: tokens.line,
    borderRadius: tokens.radiusControl,
    borderStyle: "solid",
    borderWidth: 1,
    color: tokens.foreground,
    fontSize: 12,
    marginBlockStart: 16,
    maxWidth: "100%",
    overflowX: "auto",
    padding: tokens.space3,
  },
  statusFootnote: {
    color: tokens.foregroundTertiary,
    fontSize: 12,
    marginBlockStart: 12,
  },
  recoveryHeader: {
    alignItems: "flex-start",
    borderBottomColor: tokens.line,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    gap: tokens.space3,
    padding: tokens.space5,
  },
  recoveryHeaderIcon: { color: tokens.warning, marginBlockStart: 4 },
  recoveryFooter: {
    borderTopColor: tokens.line,
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "flex",
    justifyContent: "flex-end",
    padding: tokens.space3,
  },
  recoveryIssue: {
    backgroundColor: tokens.canvas,
    borderBottomColor: tokens.lineSubtle,
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    paddingBlock: tokens.space4,
    paddingInline: tokens.space5,
  },
  recoveryIssueMeta: {
    alignItems: "center",
    color: tokens.foregroundTertiary,
    display: "flex",
    flexWrap: "wrap",
    fontSize: 12,
    gap: tokens.space2,
  },
  recoveryIssueMessage: { fontSize: 14, fontWeight: 500, marginBlockStart: 8 },
  recoveryIssueDetail: {
    color: tokens.foregroundTertiary,
    fontSize: 12,
    marginBlockStart: 8,
  },
  recoveryIssueAction: {
    color: tokens.foregroundSecondary,
    fontSize: 14,
    marginBlockStart: 12,
  },
  moduleState: {
    backgroundColor: tokens.panel,
    borderColor: tokens.line,
    borderRadius: tokens.radiusPanel,
    borderStyle: "solid",
    borderWidth: 1,
    margin: tokens.space6,
    padding: tokens.space6,
  },
  moduleStateTitle: { fontSize: 16, fontWeight: 600 },
  moduleStateDescription: {
    color: tokens.foregroundSecondary,
    fontSize: 14,
    marginBlockStart: 8,
  },
});
