import * as stylex from "@stylexjs/stylex";

export const shellStyles = stylex.create({
  theme: {
    backgroundColor: "var(--background)",
    color: "var(--foreground)",
    fontFamily: "var(--font-sans)",
    minHeight: "100dvh",
  },
  shell: {
    backgroundColor: "var(--background)",
    display: "grid",
    gridTemplateColumns: {
      default: "304px minmax(0, 1fr)",
      "@media (max-width: 720px)": "minmax(0, 1fr)",
    },
    gridTemplateRows: {
      default: "56px minmax(0, 1fr)",
      "@media (max-width: 767px)": "52px minmax(0, 1fr)",
    },
    height: "100dvh",
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  shellCollapsed: {
    gridTemplateColumns: {
      default: "56px minmax(0, 1fr)",
      "@media (max-width: 720px)": "minmax(0, 1fr)",
    },
  },
  navigationRegion: {
    display: "flex",
    gridColumn: "1",
    gridRow: "2",
    minHeight: 0,
    minWidth: 0,
    position: { default: "relative", "@media (max-width: 720px)": "absolute" },
    inset: { default: null, "@media (max-width: 720px)": 0 },
    pointerEvents: { default: "auto", "@media (max-width: 720px)": "none" },
    visibility: { default: "visible", "@media (max-width: 720px)": "hidden" },
    width: {
      default: "100%",
      "@media (max-width: 720px)": "min(304px, calc(100vw - 32px))",
    },
    zIndex: { default: null, "@media (max-width: 720px)": 20 },
  },
  navigationRegionOpen: {
    pointerEvents: { default: null, "@media (max-width: 720px)": "auto" },
    visibility: { default: null, "@media (max-width: 720px)": "visible" },
  },
  header: {
    alignItems: "center",
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(0, 1fr) minmax(0, 400px) minmax(0, 1fr)",
      "@media (max-width: 767px)": "minmax(0, 1fr) auto auto",
    },
    gridColumn: "1 / -1",
    gridRow: "1",
    backgroundColor: "var(--background)",
    borderBottom: "1px solid var(--separator)",
    columnGap: "8px",
    minWidth: 0,
    paddingInline: { default: "24px", "@media (max-width: 767px)": "16px" },
    position: "relative",
    zIndex: 30,
  },
  mobileNavTrigger: { flexShrink: 0 },
  toolbarNavigationAction: {
    width: { default: "32px", "@media (max-width: 767px)": "36px" },
    minWidth: { default: "32px", "@media (max-width: 767px)": "36px" },
    height: { default: "32px", "@media (max-width: 767px)": "36px" },
    backgroundColor: {
      default: "var(--default)",
      ":hover": "var(--default-hover)",
    },
    color: { default: "var(--muted)", ":hover": "var(--foreground)" },
  },
  toolbarLeading: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    minWidth: 0,
  },
  toolbarBrand: {
    color: "var(--foreground)",
    fontSize: "26px",
    fontWeight: 700,
    letterSpacing: "-0.04em",
    lineHeight: 1,
  },
  toolbarCenter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 0,
  },
  toolbarActions: {
    alignItems: "center",
    display: "flex",
    gap: "4px",
    justifyContent: "flex-end",
    minWidth: 0,
  },
  rail: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    flex: "0 0 56px",
    gap: "8px",
    paddingBlock: "16px",
    backgroundColor: "var(--background)",
  },
  railBottom: {
    flexShrink: 0,
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    marginBlockStart: "auto",
  },
  railItem: {
    color: "var(--muted)",
    width: "40px",
    height: "40px",
  },
  railTop: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    minHeight: 0,
    overflowY: "auto",
    paddingBlock: "4px",
    width: "100%",
  },
  railItemSelected: {
    backgroundColor: "var(--default)",
    color: "var(--foreground)",
  },
  railDivider: {
    backgroundColor: "var(--separator)",
    height: "1px",
    width: "24px",
    marginBlock: "6px",
  },
  contextSidebarRoot: {
    "--console-sidebar-width": "248px",
    boxSizing: "border-box",
    paddingBlockEnd: "16px",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    flex: "1 1 248px",
    width: "248px",
    overflow: "hidden",
  },
  contextSidebarCollapsed: {
    display: { default: "none", "@media (max-width: 720px)": "block" },
  },
  contextSidebarPanel: {
    backgroundColor: "var(--surface)",
    borderRadius: "calc(var(--radius) * 3)",
    height: "100%",
    width: "100%",
    overflow: "hidden",
  },
  sidebarHeader: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: "12px",
    height: "80px",
    paddingInline: "20px 12px",
  },
  sidebarIdentity: { minWidth: 0, flex: 1 },
  sidebarHeaderActions: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    flexShrink: 0,
  },
  sidebarHeaderActionDivider: {
    backgroundColor: "var(--separator)",
    height: "16px",
    width: "1px",
    display: { default: "block", "@media (max-width: 720px)": "none" },
  },
  workspaceSearchShortcut: {
    display: { default: "inline-flex", "@media (max-width: 720px)": "none" },
  },
  sidebarTitle: {
    color: "var(--foreground)",
    display: "block",
    fontSize: "16px",
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  sidebarSubtitle: {
    color: "var(--muted)",
    display: "block",
    fontSize: "12px",
    marginBlockStart: "4px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  sidebarMark: {
    alignItems: "center",
    backgroundColor: "var(--accent-soft)",
    borderRadius: "calc(var(--radius) * 1.5)",
    color: "var(--accent-soft-foreground)",
    display: "flex",
    flex: "0 0 36px",
    height: "36px",
    justifyContent: "center",
  },
  main: {
    gridColumn: { default: "2", "@media (max-width: 720px)": "1" },
    gridRow: "2",
    minHeight: 0,
    minWidth: 0,
    overflow: "auto",
  },
  mobileBackdrop: {
    backgroundColor: "var(--backdrop)",
    borderWidth: 0,
    display: { default: "none", "@media (max-width: 720px)": "block" },
    gridColumn: "1",
    gridRow: "2",
    inset: 0,
    padding: 0,
    position: "absolute",
    width: "100%",
    zIndex: 10,
  },
  mobileOnly: {
    display: { default: "none", "@media (max-width: 720px)": "flex" },
  },
  settingsSearchEmpty: {
    color: "var(--muted)",
    fontSize: "12px",
    lineHeight: "18px",
    margin: "12px 12px",
  },
});
