import * as stylex from "@stylexjs/stylex";

export const shellStyles = stylex.create({
  theme: {
    backgroundColor: "var(--background)",
    color: "var(--foreground)",
    fontFamily: "var(--font-sans)",
    minHeight: "100dvh",
  },
  shell: {
    backgroundColor: "var(--background)",
    display: "grid",
    gridTemplateColumns: {
      default: "304px minmax(0, 1fr)",
      "@media (max-width: 720px)": "minmax(0, 1fr)",
    },
    gridTemplateRows: "48px minmax(0, 1fr)",
    height: "100dvh",
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  shellCollapsed: {
    gridTemplateColumns: {
      default: "56px minmax(0, 1fr)",
      "@media (max-width: 720px)": "minmax(0, 1fr)",
    },
  },
  navigationRegion: {
    display: "flex",
    gridColumn: "1",
    gridRow: "2",
    minHeight: 0,
    minWidth: 0,
    position: { default: "relative", "@media (max-width: 720px)": "absolute" },
    inset: { default: null, "@media (max-width: 720px)": 0 },
    pointerEvents: { default: "auto", "@media (max-width: 720px)": "none" },
    visibility: { default: "visible", "@media (max-width: 720px)": "hidden" },
    width: {
      default: "100%",
      "@media (max-width: 720px)": "min(304px, calc(100vw - 32px))",
    },
    zIndex: { default: null, "@media (max-width: 720px)": 20 },
  },
  navigationRegionOpen: {
    pointerEvents: { default: null, "@media (max-width: 720px)": "auto" },
    visibility: { default: null, "@media (max-width: 720px)": "visible" },
  },
  header: {
    alignItems: "center",
    display: "grid",
    gridTemplateColumns: {
      default: "360px minmax(0, 1fr) 360px",
      "@media (max-width: 1050px)": "auto minmax(0, 1fr) auto",
    },
    gridColumn: "1 / -1",
    gridRow: "1",
    minWidth: 0,
    paddingInline: 0,
    position: "relative",
    zIndex: 30,
  },
  mobileNavTrigger: { flexShrink: 0 },
  toolbarNavigationAction: { width: "40px", minWidth: "40px", height: "40px" },
  toolbarLeading: {
    display: "flex",
    alignItems: "center",
    gap: "20px",
    paddingInlineStart: { default: "16px", "@media (max-width: 720px)": "8px" },
  },
  toolbarNavigation: { display: "flex", alignItems: "center", gap: "4px" },
  toolbarMark: {
    display: { default: "flex", "@media (max-width: 720px)": "none" },
    alignItems: "center",
    justifyContent: "center",
    width: "20px",
    height: "20px",
    flexShrink: 0,
    borderRadius: "6px",
    backgroundColor: "var(--accent-soft)",
    color: "var(--accent-soft-foreground)",
  },
  toolbarCenter: {
    display: "flex",
    alignItems: "center",
    justifyContent: {
      default: "center",
      "@media (max-width: 1050px)": "flex-end",
    },
    minWidth: 0,
  },
  toolbarAddress: {
    display: "flex",
    alignItems: "center",
    width: { default: "336px", "@media (max-width: 1050px)": "32px" },
    maxWidth: "100%",
    minWidth: 0,
  },
  addressMark: {
    display: { default: "flex", "@media (max-width: 1050px)": "none" },
  },
  addressPageIcon: {
    color: "var(--muted)",
    flexShrink: 0,
    marginInline: "16px 12px",
    display: { default: "block", "@media (max-width: 1050px)": "none" },
  },
  toolbarActions: {
    alignItems: "center",
    display: "flex",
    gap: "4px",
    justifyContent: "center",
    paddingInline: { default: "16px", "@media (max-width: 720px)": "8px" },
    minWidth: 0,
  },
  rail: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    flex: "0 0 56px",
    gap: "8px",
    paddingBlock: "16px",
    backgroundColor: "var(--background)",
  },
  railBottom: {
    flexShrink: 0,
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    marginBlockStart: "auto",
  },
  railItem: {
    color: "var(--muted)",
    width: "40px",
    height: "40px",
  },
  railTop: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    minHeight: 0,
    overflowY: "auto",
    paddingBlock: "4px",
    width: "100%",
  },
  railItemSelected: {
    backgroundColor: "var(--default)",
    color: "var(--foreground)",
  },
  railDivider: {
    backgroundColor: "var(--separator)",
    height: "1px",
    width: "24px",
    marginBlock: "6px",
  },
  contextSidebarRoot: {
    "--console-sidebar-width": "248px",
    boxSizing: "border-box",
    paddingBlockEnd: "16px",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    flex: "1 1 248px",
    width: "248px",
    overflow: "hidden",
  },
  contextSidebarCollapsed: {
    display: { default: "none", "@media (max-width: 720px)": "block" },
  },
  contextSidebarPanel: {
    backgroundColor: "var(--surface)",
    borderRadius: "calc(var(--radius) * 3)",
    height: "100%",
    width: "100%",
    overflow: "hidden",
  },
  sidebarHeader: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: "12px",
    height: "80px",
    paddingInline: "20px 12px",
  },
  sidebarIdentity: { minWidth: 0, flex: 1 },
  sidebarHeaderActions: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    flexShrink: 0,
  },
  sidebarHeaderActionDivider: {
    backgroundColor: "var(--separator)",
    height: "16px",
    width: "1px",
    display: { default: "block", "@media (max-width: 720px)": "none" },
  },
  workspaceSearchShortcut: {
    display: { default: "inline-flex", "@media (max-width: 720px)": "none" },
  },
  sidebarTitle: {
    color: "var(--foreground)",
    display: "block",
    fontSize: "16px",
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  sidebarSubtitle: {
    color: "var(--muted)",
    display: "block",
    fontSize: "12px",
    marginBlockStart: "4px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  sidebarMark: {
    alignItems: "center",
    backgroundColor: "var(--accent-soft)",
    borderRadius: "calc(var(--radius) * 1.5)",
    color: "var(--accent-soft-foreground)",
    display: "flex",
    flex: "0 0 36px",
    height: "36px",
    justifyContent: "center",
  },
  main: {
    gridColumn: { default: "2", "@media (max-width: 720px)": "1" },
    gridRow: "2",
    minHeight: 0,
    minWidth: 0,
    overflow: "auto",
  },
  mobileBackdrop: {
    backgroundColor: "var(--backdrop)",
    borderWidth: 0,
    display: { default: "none", "@media (max-width: 720px)": "block" },
    gridColumn: "1",
    gridRow: "2",
    inset: 0,
    padding: 0,
    position: "absolute",
    width: "100%",
    zIndex: 10,
  },
  mobileOnly: {
    display: { default: "none", "@media (max-width: 720px)": "flex" },
  },
  settingsSearchEmpty: {
    color: "var(--muted)",
    fontSize: "12px",
    lineHeight: "18px",
    margin: "12px 12px",
  },
});
