import * as stylex from "@stylexjs/stylex";

export const searchStyles = stylex.create({
  trigger: {
    alignItems: "center",
    backgroundColor: {
      default: "var(--console-raised, var(--field-background))",
      ":hover": "var(--default-hover)",
    },
    borderColor: "var(--console-shell-line, var(--separator))",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--muted)",
    cursor: "pointer",
    display: "flex",
    gap: "9px",
    height: "32px",
    paddingInline: { default: "11px", "@media (max-width: 1050px)": 0 },
    minWidth: 0,
    width: { default: "272px", "@media (max-width: 1050px)": "32px" },
    "@media (max-width: 1050px)": { justifyContent: "center" },
    "@media (max-width: 720px)": {
      backgroundColor: "transparent",
      borderWidth: 0,
    },
  },
  expandedTrigger: { borderRadius: "var(--radius)", fontSize: "12px" },
  triggerLabel: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    textAlign: "start",
    whiteSpace: "nowrap",
    "@media (max-width: 1050px)": { display: "none" },
  },
  shortcut: {
    color: "var(--console-muted, var(--muted))",
    fontFamily: "inherit",
    fontSize: "10px",
    "@media (max-width: 1050px)": { display: "none" },
  },
  portal: { position: "relative", zIndex: 100 },
  backdrop: { backgroundColor: "rgb(0 0 0 / 60%)" },
  viewport: {
    alignItems: "flex-start",
    display: "flex",
    justifyContent: "center",
    paddingBlockStart: "70px",
    paddingInline: "14px",
  },
  popup: {
    backgroundColor: "var(--background)",
    borderRadius: "11px",
    boxShadow: "var(--shadow-overlay)",
    maxWidth: "calc(100vw - 28px)",
    overflow: "hidden",
    padding: "7px",
    width: "min(450px, calc(100vw - 28px))",
  },
  commandPanel: {
    backgroundColor: "transparent",
    borderRadius: 0,
    boxShadow: "none",
    maxHeight: "min(450px, calc(100dvh - 100px))",
    width: "100%",
  },
  visuallyHiddenTitle: {
    clipPath: "inset(50%)",
    height: "1px",
    margin: 0,
    overflow: "hidden",
    position: "absolute",
    whiteSpace: "nowrap",
    width: "1px",
  },
  searchField: {
    display: "flex",
    width: "100%",
    borderBottomColor: "var(--console-shell-line, var(--separator))",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    color: "var(--muted)",
    gap: "10px",
    height: "41px",
    marginInline: 0,
    padding: "0 9px 6px",
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    width: "100%",
    color: "var(--foreground)",
    fontSize: "13px",
    height: "34px",
  },
  results: {
    maxHeight: "min(50dvh, 270px)",
    overflowY: "auto",
    padding: "5px 0 0",
  },
  result: {
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--default-hover)",
      "[data-highlighted]": "var(--accent-soft)",
    },
    borderRadius: "7px",
    minHeight: "36px",
    paddingInline: "10px",
  },
  group: {
    color: "var(--muted)",
    fontSize: "11px",
    marginInlineStart: "auto",
  },
});
