import * as stylex from "@stylexjs/stylex";

export const searchStyles = stylex.create({
  trigger: {
    alignItems: "center",
    backgroundColor: {
      default: "var(--field-background)",
      ":hover": "var(--default-hover)",
      ":is([data-theme='dark'] *)":
        "color-mix(in oklab, var(--field-background) 80%, transparent)",
      "@media (max-width: 767px)": "var(--default)",
    },
    backdropFilter: {
      default: "none",
      ":is([data-theme='dark'] *)": {
        default: "blur(12px)",
        "@media (max-width: 767px)": "none",
      },
    },
    boxShadow: {
      default: "var(--field-shadow)",
      "@media (max-width: 767px)": "none",
    },
    outlineColor: { default: null, ":focus-visible": "var(--focus)" },
    outlineStyle: { default: null, ":focus-visible": "solid" },
    outlineWidth: { default: null, ":focus-visible": "2px" },
    outlineOffset: { default: null, ":focus-visible": "2px" },
    color: "var(--muted)",
    cursor: "pointer",
    display: "flex",
    gap: "8px",
    height: { default: "32px", "@media (max-width: 767px)": "36px" },
    justifyContent: { default: null, "@media (max-width: 767px)": "center" },
    paddingInline: { default: "8px 6px", "@media (max-width: 767px)": 0 },
    minWidth: 0,
    width: { default: "100%", "@media (max-width: 767px)": "36px" },
  },
  expandedTrigger: {
    borderRadius: "var(--field-radius)",
    fontSize: "14px",
    lineHeight: "20px",
  },
  triggerLabel: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    textAlign: "start",
    whiteSpace: "nowrap",
    display: { default: null, "@media (max-width: 767px)": "none" },
  },
  shortcut: {
    display: { default: "flex", "@media (max-width: 767px)": "none" },
    gap: "2px",
    flexShrink: 0,
  },
  shortcutKey: {
    backgroundColor: {
      default: "var(--default)",
      ":is([data-theme='dark'] *)": "var(--surface)",
    },
    borderRadius: "4px",
    color: "var(--muted)",
    fontFamily: "inherit",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "20px",
    paddingInline: "4px",
  },
  portal: { position: "relative", zIndex: 100 },
  backdrop: {
    backgroundColor: {
      default: "rgb(255 255 255 / 40%)",
      ":is([data-theme='dark'] *)": "rgb(0 0 0 / 40%)",
    },
    backdropFilter: "blur(8px) saturate(180%)",
  },
  viewport: {
    alignItems: "flex-start",
    display: "flex",
    justifyContent: "center",
    paddingBlockStart: {
      default: "max(16px, calc(50dvh - 250px))",
      "@media (max-width: 767px)": "16px",
    },
    paddingBlockEnd: "16px",
    paddingInline: "8px",
  },
  popup: {
    backgroundColor: "var(--surface)",
    color: "var(--foreground)",
    borderRadius: "12px",
    borderWidth: 0,
    boxShadow: "0 25px 50px -12px rgb(0 0 0 / 50%)",
    maxWidth: "640px",
    overflow: "hidden",
    padding: 0,
    width: "100%",
  },
  commandPanel: {
    backgroundColor: "transparent",
    borderRadius: 0,
    boxShadow: "none",
    maxHeight: "calc(100dvh - 32px)",
    width: "100%",
  },
  visuallyHiddenTitle: {
    clipPath: "inset(50%)",
    height: "1px",
    margin: 0,
    overflow: "hidden",
    position: "absolute",
    whiteSpace: "nowrap",
    width: "1px",
  },
  searchField: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: 0,
    boxShadow: "none",
    display: "flex",
    width: "100%",
    borderBottomColor: "var(--separator)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    color: "var(--muted)",
    gap: "8px",
    height: "auto",
    marginInline: 0,
    padding: "12px",
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    width: "100%",
    color: "var(--foreground)",
    fontSize: "14px",
    height: "32px",
  },
  results: {
    maxHeight: "min(460px, calc(100dvh - 100px))",
    overflowY: "auto",
    padding: "8px",
  },
  result: {
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--default-hover)",
      "[data-highlighted]": "var(--default)",
    },
    borderRadius: "8px",
    fontSize: "14px",
    gap: "8px",
    lineHeight: "20px",
    minHeight: "36px",
    padding: "8px 10px",
  },
  resultLabel: {
    minWidth: 0,
    overflowWrap: "anywhere",
  },
  group: {
    color: "var(--muted)",
    fontSize: "12px",
    marginInlineStart: "auto",
    maxWidth: "40%",
    overflowWrap: "anywhere",
  },
});
