// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, NativeStream, NativeStreamEndpoint, NativeStreamHandle, NativeStreamSession, PluginDependencies, RequestCapability, RuntimeFailure, StreamCapability, StreamEvent};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.ui.workspace-service@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:d6cbcee860d41b45c51741fd0a8b92aaa1b0ea16a1306179941e0dc4a942f9c3";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const WORKSPACE_SERVICE_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const WORKSPACE_SERVICE_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const WORKSPACE_SERVICE_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const WORKSPACE_SERVICE_CONTRACT: CapabilityReference<WorkspaceServiceClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_workspace_service { () => { "{\"capability_id\":\"lenso.ui.workspace-service@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"describe_exports\",\"invoke\",\"subscribe\"],\"operation_kinds\":{\"subscribe\":\"stream\"},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_workspace_service_client {
    () => { "{\"capability_id\":\"lenso.ui.workspace-service@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.ui.workspace-service@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_workspace_service_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.ui.workspace-service@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_workspace_service_client {
    () => { "{\"capability_id\":\"lenso.ui.workspace-service@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.ui.workspace-service@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const DESCRIBE_EXPORTS_OPERATION: &str = "describe_exports";
pub const INVOKE_OPERATION: &str = "invoke";
pub const SUBSCRIBE_OPERATION: &str = "subscribe";

pub use lenso_contract_runtime::{UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeExportsRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeExportsResponse {
    #[serde(rename = "adapter_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub adapter_revision: String,
    #[serde(rename = "services")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub services: Vec<DescribeExportsResponseServicesItem>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeExportsResponseServicesItem {
    #[serde(rename = "capability_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub capability_id: String,
    #[serde(rename = "descriptor_version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub descriptor_version: String,
    #[serde(rename = "operations")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub operations: Vec<DescribeExportsResponseServicesItemOperationsItem>,
    #[serde(rename = "service_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub service_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeExportsResponseServicesItemOperationsItem {
    #[serde(rename = "interaction")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub interaction: DescribeExportsResponseServicesItemOperationsItemInteraction,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum DescribeExportsResponseServicesItemOperationsItemInteraction {
    #[serde(rename = "request")]
    Request,
    #[serde(rename = "stream")]
    Stream,
}

#[derive(Clone, Debug, PartialEq)]
pub enum DescribeExportsError {
    CodecMismatch,
    Denied,
    RequestTooLarge,
    ResourceExhausted,
    ResponseTooLarge,
    UnknownOperation,
    UnknownService,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InvokeRequest {
    #[serde(rename = "body_base64")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub body_base64: String,
    #[serde(rename = "media_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub media_type: InvokeRequestMediaType,
    #[serde(rename = "operation")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub operation: String,
    #[serde(rename = "service_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub service_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum InvokeRequestMediaType {
    #[serde(rename = "application/json")]
    ApplicationJson,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InvokeResponse {
    #[serde(rename = "body_base64")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub body_base64: String,
    #[serde(rename = "outcome")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub outcome: InvokeResponseOutcome,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum InvokeResponseOutcome {
    #[serde(rename = "success")]
    Success,
    #[serde(rename = "domain_error")]
    DomainError,
}

#[derive(Clone, Debug, PartialEq)]
pub enum InvokeError {
    CodecMismatch,
    Denied,
    RequestTooLarge,
    ResourceExhausted,
    ResponseTooLarge,
    UnknownOperation,
    UnknownService,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SubscribeRequest {
    #[serde(rename = "body_base64")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub body_base64: String,
    #[serde(rename = "media_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub media_type: SubscribeRequestMediaType,
    #[serde(rename = "operation")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub operation: String,
    #[serde(rename = "service_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub service_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum SubscribeRequestMediaType {
    #[serde(rename = "application/json")]
    ApplicationJson,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SubscribeResponse {
    #[serde(rename = "body_base64")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub body_base64: String,
    #[serde(rename = "outcome")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub outcome: SubscribeResponseOutcome,
    #[serde(rename = "sequence")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub sequence: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum SubscribeResponseOutcome {
    #[serde(rename = "item")]
    Item,
    #[serde(rename = "domain_error")]
    DomainError,
}

#[derive(Clone, Debug, PartialEq)]
pub enum SubscribeError {
    CodecMismatch,
    Denied,
    RequestTooLarge,
    ResourceExhausted,
    ResponseTooLarge,
    UnknownOperation,
    UnknownService,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct WorkspaceServiceDescribeExports;
impl RequestCapability for WorkspaceServiceDescribeExports {
    type Request = DescribeExportsRequest;
    type Response = DescribeExportsResponse;
    type DomainError = DescribeExportsError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != DESCRIBE_EXPORTS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<WorkspaceServiceRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).describe_exports(context, request)
    }
}

#[derive(Debug)]
pub struct WorkspaceServiceInvoke;
impl RequestCapability for WorkspaceServiceInvoke {
    type Request = InvokeRequest;
    type Response = InvokeResponse;
    type DomainError = InvokeError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != INVOKE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<WorkspaceServiceRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).invoke(context, request)
    }
}

#[derive(Debug)]
pub struct WorkspaceServiceSubscribe;
pub type WorkspaceServiceSubscribeEvent = StreamEvent<SubscribeResponse, SubscribeError>;
impl StreamCapability for WorkspaceServiceSubscribe {
    type OpenRequest = SubscribeRequest;
    type Message = SubscribeResponse;
    type DomainError = SubscribeError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;
}

impl serde::Serialize for DescribeExportsError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::CodecMismatch => serializer.serialize_str("codec_mismatch"),
            Self::Denied => serializer.serialize_str("denied"),
            Self::RequestTooLarge => serializer.serialize_str("request_too_large"),
            Self::ResourceExhausted => serializer.serialize_str("resource_exhausted"),
            Self::ResponseTooLarge => serializer.serialize_str("response_too_large"),
            Self::UnknownOperation => serializer.serialize_str("unknown_operation"),
            Self::UnknownService => serializer.serialize_str("unknown_service"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for DescribeExportsError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "codec_mismatch" => Ok(Self::CodecMismatch),
                "denied" => Ok(Self::Denied),
                "request_too_large" => Ok(Self::RequestTooLarge),
                "resource_exhausted" => Ok(Self::ResourceExhausted),
                "response_too_large" => Ok(Self::ResponseTooLarge),
                "unknown_operation" => Ok(Self::UnknownOperation),
                "unknown_service" => Ok(Self::UnknownService),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for InvokeError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::CodecMismatch => serializer.serialize_str("codec_mismatch"),
            Self::Denied => serializer.serialize_str("denied"),
            Self::RequestTooLarge => serializer.serialize_str("request_too_large"),
            Self::ResourceExhausted => serializer.serialize_str("resource_exhausted"),
            Self::ResponseTooLarge => serializer.serialize_str("response_too_large"),
            Self::UnknownOperation => serializer.serialize_str("unknown_operation"),
            Self::UnknownService => serializer.serialize_str("unknown_service"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for InvokeError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "codec_mismatch" => Ok(Self::CodecMismatch),
                "denied" => Ok(Self::Denied),
                "request_too_large" => Ok(Self::RequestTooLarge),
                "resource_exhausted" => Ok(Self::ResourceExhausted),
                "response_too_large" => Ok(Self::ResponseTooLarge),
                "unknown_operation" => Ok(Self::UnknownOperation),
                "unknown_service" => Ok(Self::UnknownService),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for SubscribeError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::CodecMismatch => serializer.serialize_str("codec_mismatch"),
            Self::Denied => serializer.serialize_str("denied"),
            Self::RequestTooLarge => serializer.serialize_str("request_too_large"),
            Self::ResourceExhausted => serializer.serialize_str("resource_exhausted"),
            Self::ResponseTooLarge => serializer.serialize_str("response_too_large"),
            Self::UnknownOperation => serializer.serialize_str("unknown_operation"),
            Self::UnknownService => serializer.serialize_str("unknown_service"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for SubscribeError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "codec_mismatch" => Ok(Self::CodecMismatch),
                "denied" => Ok(Self::Denied),
                "request_too_large" => Ok(Self::RequestTooLarge),
                "resource_exhausted" => Ok(Self::ResourceExhausted),
                "response_too_large" => Ok(Self::ResponseTooLarge),
                "unknown_operation" => Ok(Self::UnknownOperation),
                "unknown_service" => Ok(Self::UnknownService),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_describe_exports_request(value: &DescribeExportsRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_describe_exports_request(wire: &str) -> Result<DescribeExportsRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_describe_exports_response(value: &DescribeExportsResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_describe_exports_response(wire: &str) -> Result<DescribeExportsResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_describe_exports_error(value: &DescribeExportsError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_describe_exports_error(wire: &str) -> Result<DescribeExportsError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_invoke_request(value: &InvokeRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_invoke_request(wire: &str) -> Result<InvokeRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_invoke_response(value: &InvokeResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_invoke_response(wire: &str) -> Result<InvokeResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_invoke_error(value: &InvokeError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_invoke_error(wire: &str) -> Result<InvokeError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_subscribe_request(value: &SubscribeRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_subscribe_request(wire: &str) -> Result<SubscribeRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_subscribe_response(value: &SubscribeResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_subscribe_response(wire: &str) -> Result<SubscribeResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_subscribe_error(value: &SubscribeError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_subscribe_error(wire: &str) -> Result<SubscribeError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoWorkspaceServiceDescribeExportsResult {
    fn __lenso_into_result(self) -> Result<Result<DescribeExportsResponse, DescribeExportsError>, RuntimeFailure>;
}
impl __LensoIntoWorkspaceServiceDescribeExportsResult for Result<DescribeExportsResponse, DescribeExportsError> {
    fn __lenso_into_result(self) -> Result<Result<DescribeExportsResponse, DescribeExportsError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoWorkspaceServiceDescribeExportsResult for Result<Result<DescribeExportsResponse, DescribeExportsError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<DescribeExportsResponse, DescribeExportsError>, RuntimeFailure> { self }
}
impl __LensoIntoWorkspaceServiceDescribeExportsResult for Result<DescribeExportsResponse, lenso_plugin_authoring::PluginError<DescribeExportsError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<DescribeExportsResponse, DescribeExportsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoWorkspaceServiceDescribeExportsResult for Result<DescribeExportsResponse, WorkspaceServiceDescribeExportsInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<DescribeExportsResponse, DescribeExportsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(WorkspaceServiceDescribeExportsInvocationError::Domain(error)) => Ok(Err(error)),
            Err(WorkspaceServiceDescribeExportsInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoWorkspaceServiceInvokeResult {
    fn __lenso_into_result(self) -> Result<Result<InvokeResponse, InvokeError>, RuntimeFailure>;
}
impl __LensoIntoWorkspaceServiceInvokeResult for Result<InvokeResponse, InvokeError> {
    fn __lenso_into_result(self) -> Result<Result<InvokeResponse, InvokeError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoWorkspaceServiceInvokeResult for Result<Result<InvokeResponse, InvokeError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<InvokeResponse, InvokeError>, RuntimeFailure> { self }
}
impl __LensoIntoWorkspaceServiceInvokeResult for Result<InvokeResponse, lenso_plugin_authoring::PluginError<InvokeError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<InvokeResponse, InvokeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoWorkspaceServiceInvokeResult for Result<InvokeResponse, WorkspaceServiceInvokeInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<InvokeResponse, InvokeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(WorkspaceServiceInvokeInvocationError::Domain(error)) => Ok(Err(error)),
            Err(WorkspaceServiceInvokeInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoWorkspaceServiceSubscribeStreamResult {
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, WorkspaceServiceSubscribeInvocationError>;
}
impl<S> __LensoIntoWorkspaceServiceSubscribeStreamResult for Result<S, SubscribeError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, WorkspaceServiceSubscribeInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
            .map_err(WorkspaceServiceSubscribeInvocationError::Domain)
    }
}
impl<S> __LensoIntoWorkspaceServiceSubscribeStreamResult for Result<S, lenso_plugin_authoring::PluginError<SubscribeError, RuntimeFailure>>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, WorkspaceServiceSubscribeInvocationError> {
        match self {
            Ok(stream) => Ok(Box::new(stream) as Box<dyn NativeStreamSession>),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Err(WorkspaceServiceSubscribeInvocationError::Domain(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(WorkspaceServiceSubscribeInvocationError::Runtime(error)),
        }
    }
}
impl<S> __LensoIntoWorkspaceServiceSubscribeStreamResult for Result<S, WorkspaceServiceSubscribeInvocationError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, WorkspaceServiceSubscribeInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
    }
}

pub trait WorkspaceServiceProvider: fmt::Debug + 'static {
    fn describe_exports(&self, context: InvocationContext, request: DescribeExportsRequest) -> NativeRequestFuture<WorkspaceServiceDescribeExports>;
    fn invoke(&self, context: InvocationContext, request: InvokeRequest) -> NativeRequestFuture<WorkspaceServiceInvoke>;
    fn subscribe(&self, context: InvocationContext, request: SubscribeRequest) -> LocalBoxFuture<'static, Result<Box<dyn NativeStreamSession>, WorkspaceServiceSubscribeInvocationError>>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_workspace_service {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportWorkspaceService;
        impl $crate::WorkspaceServiceProvider for $plugin {
        fn describe_exports(&self, context: __LensoNativeSupportWorkspaceService::InvocationContext, request: $crate::DescribeExportsRequest) -> __LensoNativeSupportWorkspaceService::NativeRequestFuture<$crate::WorkspaceServiceDescribeExports> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::describe_exports(&plugin, context, request).await;
                $crate::__LensoIntoWorkspaceServiceDescribeExportsResult::__lenso_into_result(result)
            })
        }
        fn invoke(&self, context: __LensoNativeSupportWorkspaceService::InvocationContext, request: $crate::InvokeRequest) -> __LensoNativeSupportWorkspaceService::NativeRequestFuture<$crate::WorkspaceServiceInvoke> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::invoke(&plugin, context, request).await;
                $crate::__LensoIntoWorkspaceServiceInvokeResult::__lenso_into_result(result)
            })
        }
        fn subscribe(&self, context: __LensoNativeSupportWorkspaceService::InvocationContext, request: $crate::SubscribeRequest) -> __LensoNativeSupportWorkspaceService::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportWorkspaceService::NativeStreamSession>, $crate::WorkspaceServiceSubscribeInvocationError>> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::subscribe(&plugin, context, request).await;
                $crate::__LensoIntoWorkspaceServiceSubscribeStreamResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_workspace_service {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportWorkspaceService;
        impl $crate::WorkspaceServiceProvider for $object {
        fn describe_exports(&self, context: __LensoNativeSupportWorkspaceService::InvocationContext, request: $crate::DescribeExportsRequest) -> __LensoNativeSupportWorkspaceService::NativeRequestFuture<$crate::WorkspaceServiceDescribeExports> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::describe_exports(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoWorkspaceServiceDescribeExportsResult::__lenso_into_result(result)
            })
        }
        fn invoke(&self, context: __LensoNativeSupportWorkspaceService::InvocationContext, request: $crate::InvokeRequest) -> __LensoNativeSupportWorkspaceService::NativeRequestFuture<$crate::WorkspaceServiceInvoke> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::invoke(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoWorkspaceServiceInvokeResult::__lenso_into_result(result)
            })
        }
        fn subscribe(&self, context: __LensoNativeSupportWorkspaceService::InvocationContext, request: $crate::SubscribeRequest) -> __LensoNativeSupportWorkspaceService::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportWorkspaceService::NativeStreamSession>, $crate::WorkspaceServiceSubscribeInvocationError>> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get().map_err($crate::WorkspaceServiceSubscribeInvocationError::Runtime)?;
                let result = <$plugin>::subscribe(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoWorkspaceServiceSubscribeStreamResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_workspace_service {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportWorkspaceService;
        impl $crate::WorkspaceServiceProvider for $object {
        fn describe_exports(&self, context: __LensoNativeSupportWorkspaceService::InvocationContext, request: $crate::DescribeExportsRequest) -> __LensoNativeSupportWorkspaceService::NativeRequestFuture<$crate::WorkspaceServiceDescribeExports> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::WorkspaceServiceProvider>::describe_exports(plugin.as_ref(), context, request).await
            })
        }
        fn invoke(&self, context: __LensoNativeSupportWorkspaceService::InvocationContext, request: $crate::InvokeRequest) -> __LensoNativeSupportWorkspaceService::NativeRequestFuture<$crate::WorkspaceServiceInvoke> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::WorkspaceServiceProvider>::invoke(plugin.as_ref(), context, request).await
            })
        }
        fn subscribe(&self, context: __LensoNativeSupportWorkspaceService::InvocationContext, request: $crate::SubscribeRequest) -> __LensoNativeSupportWorkspaceService::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportWorkspaceService::NativeStreamSession>, $crate::WorkspaceServiceSubscribeInvocationError>> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get().map_err($crate::WorkspaceServiceSubscribeInvocationError::Runtime)?;
                <$plugin as $crate::WorkspaceServiceProvider>::subscribe(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct WorkspaceServiceRequestEndpoint { provider: Rc<dyn WorkspaceServiceProvider> }

#[derive(Debug)]
pub struct WorkspaceServiceEndpoint<P: WorkspaceServiceProvider> { provider: Rc<P>, request_endpoint: WorkspaceServiceRequestEndpoint }
impl<P: WorkspaceServiceProvider> WorkspaceServiceEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn WorkspaceServiceProvider> = provider.clone();
        Self { provider, request_endpoint: WorkspaceServiceRequestEndpoint { provider: request_provider } }
    }
}

impl<P: WorkspaceServiceProvider> NativeRequestEndpoint for WorkspaceServiceEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        DESCRIBE_EXPORTS_OPERATION,
        INVOKE_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            DESCRIBE_EXPORTS_OPERATION => {
                let Ok(request) = request.downcast::<DescribeExportsRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).describe_exports(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            INVOKE_OPERATION => {
                let Ok(request) = request.downcast::<InvokeRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).invoke(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

impl<P: WorkspaceServiceProvider> NativeStreamEndpoint for WorkspaceServiceEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        SUBSCRIBE_OPERATION,
    ] }
    fn open(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn NativeStreamSession>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            SUBSCRIBE_OPERATION => {
                let Ok(request) = request.downcast::<SubscribeRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let provider = Rc::clone(&self.provider);
                Box::pin(async move {
                    match provider.subscribe(context, *request).await {
                        Ok(value) => Ok(Ok(value as Box<dyn NativeStreamSession>)),
                        Err(WorkspaceServiceSubscribeInvocationError::Domain(error)) => Ok(Err(Box::new(error) as Box<dyn std::any::Any>)),
                        Err(WorkspaceServiceSubscribeInvocationError::Runtime(error)) => Err(error),
                    }
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_workspace_service {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::WorkspaceServiceEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeStreamEndpoint>],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_workspace_service {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_workspace_service!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct WorkspaceServiceClient {
    describe_exports: NativeRequestHandle<WorkspaceServiceDescribeExports>,
    invoke: NativeRequestHandle<WorkspaceServiceInvoke>,
    subscribe: NativeStreamHandle<WorkspaceServiceSubscribe>,
}
impl WorkspaceServiceClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn describe_exports(&self, request: DescribeExportsRequest) -> Result<DescribeExportsResponse, WorkspaceServiceDescribeExportsInvocationError> {
        self.describe_exports.invoke(DESCRIBE_EXPORTS_OPERATION, request).await
            .map_err(WorkspaceServiceDescribeExportsInvocationError::Runtime)?
            .map_err(WorkspaceServiceDescribeExportsInvocationError::Domain)
    }

    pub async fn describe_exports_with_context(&self, context: InvocationContext, request: DescribeExportsRequest) -> Result<DescribeExportsResponse, WorkspaceServiceDescribeExportsInvocationError> {
        self.describe_exports.invoke_with_context(DESCRIBE_EXPORTS_OPERATION, context, request).await
            .map_err(WorkspaceServiceDescribeExportsInvocationError::Runtime)?
            .map_err(WorkspaceServiceDescribeExportsInvocationError::Domain)
    }

    pub async fn invoke(&self, request: InvokeRequest) -> Result<InvokeResponse, WorkspaceServiceInvokeInvocationError> {
        self.invoke.invoke(INVOKE_OPERATION, request).await
            .map_err(WorkspaceServiceInvokeInvocationError::Runtime)?
            .map_err(WorkspaceServiceInvokeInvocationError::Domain)
    }

    pub async fn invoke_with_context(&self, context: InvocationContext, request: InvokeRequest) -> Result<InvokeResponse, WorkspaceServiceInvokeInvocationError> {
        self.invoke.invoke_with_context(INVOKE_OPERATION, context, request).await
            .map_err(WorkspaceServiceInvokeInvocationError::Runtime)?
            .map_err(WorkspaceServiceInvokeInvocationError::Domain)
    }

    pub async fn subscribe(&self, request: SubscribeRequest) -> Result<NativeStream<WorkspaceServiceSubscribe>, WorkspaceServiceSubscribeInvocationError> {
        self.subscribe.open(SUBSCRIBE_OPERATION, request).await
            .map_err(WorkspaceServiceSubscribeInvocationError::Runtime)?
            .map_err(WorkspaceServiceSubscribeInvocationError::Domain)
    }

    pub async fn subscribe_with_context(&self, context: InvocationContext, request: SubscribeRequest) -> Result<NativeStream<WorkspaceServiceSubscribe>, WorkspaceServiceSubscribeInvocationError> {
        self.subscribe.open_with_context(SUBSCRIBE_OPERATION, context, request).await
            .map_err(WorkspaceServiceSubscribeInvocationError::Runtime)?
            .map_err(WorkspaceServiceSubscribeInvocationError::Domain)
    }
}

impl CapabilityClient for WorkspaceServiceClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            describe_exports: dependencies.one::<WorkspaceServiceDescribeExports>()?,
            invoke: dependencies.one::<WorkspaceServiceInvoke>()?,
            subscribe: dependencies.one_stream::<WorkspaceServiceSubscribe>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for WorkspaceServiceClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    describe_exports: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<WorkspaceServiceDescribeExports>()?,
                    invoke: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<WorkspaceServiceInvoke>()?,
                    subscribe: binding.stream_handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<WorkspaceServiceSubscribe>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum WorkspaceServiceDescribeExportsInvocationError {
    Domain(DescribeExportsError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum WorkspaceServiceInvokeInvocationError {
    Domain(InvokeError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum WorkspaceServiceSubscribeInvocationError {
    Domain(SubscribeError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct WorkspaceServiceGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> WorkspaceServiceGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[DESCRIBE_EXPORTS_OPERATION, INVOKE_OPERATION], &[SUBSCRIBE_OPERATION], &[])
            .map(|capability| Self { capability })
    }

    pub fn describe_exports(&self, request: &DescribeExportsRequest) -> Result<DescribeExportsResponse, lenso_guest_sdk::GuestError<DescribeExportsError>> {
        self.capability.request(DESCRIBE_EXPORTS_OPERATION, request)
    }

    pub fn invoke(&self, request: &InvokeRequest) -> Result<InvokeResponse, lenso_guest_sdk::GuestError<InvokeError>> {
        self.capability.request(INVOKE_OPERATION, request)
    }

    pub fn subscribe(&self, request: &SubscribeRequest) -> Result<lenso_guest_sdk::GuestStream<H, SubscribeResponse, SubscribeError>, lenso_guest_sdk::GuestError<SubscribeError>> {
        self.capability.open_stream(SUBSCRIBE_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct WorkspaceServiceJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for WorkspaceServiceJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn descriptor_digest(&self) -> &'static str { DESCRIPTOR_DIGEST }

    fn request_operations(&self) -> &'static [&'static str] { &[DESCRIBE_EXPORTS_OPERATION, INVOKE_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[SUBSCRIBE_OPERATION] }
    fn event_operations(&self) -> &'static [&'static str] { &[] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            DESCRIBE_EXPORTS_OPERATION => {
                let value = request.downcast_ref::<DescribeExportsRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            INVOKE_OPERATION => {
                let value = request.downcast_ref::<InvokeRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            DESCRIBE_EXPORTS_OPERATION => serde_json::from_value::<DescribeExportsResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            INVOKE_OPERATION => serde_json::from_value::<InvokeResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            DESCRIBE_EXPORTS_OPERATION => serde_json::from_value::<DescribeExportsError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            INVOKE_OPERATION => serde_json::from_value::<InvokeError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            SUBSCRIBE_OPERATION => {
                let value = request.downcast_ref::<SubscribeRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_message(&self, operation: &str, message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            SUBSCRIBE_OPERATION => {
                let value = message.downcast_ref::<SubscribeResponse>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_stream_message(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            SUBSCRIBE_OPERATION => serde_json::from_value::<SubscribeResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_stream_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            SUBSCRIBE_OPERATION => serde_json::from_value::<SubscribeError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_event(&self, operation: &str, _event: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::PluginDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            DESCRIBE_EXPORTS_OPERATION => {
                let request = serde_json::from_value::<DescribeExportsRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<WorkspaceServiceDescribeExports>()?;
                    match handle.invoke_with_context(DESCRIBE_EXPORTS_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            INVOKE_OPERATION => {
                let request = serde_json::from_value::<InvokeRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<WorkspaceServiceInvoke>()?;
                    match handle.invoke_with_context(INVOKE_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, dependency: lenso_kernel::PluginStreamDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        match operation.as_str() {
            SUBSCRIBE_OPERATION => {
                let request = serde_json::from_value::<SubscribeRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<WorkspaceServiceSubscribe>()?;
                    match handle.open_with_context(SUBSCRIBE_OPERATION, context, request).await? {
                        Ok(stream) => Ok(Ok(lenso_runtime_codec::json_host_stream::<WorkspaceServiceSubscribe>(
                            stream,
                            |value| serde_json::from_value::<SubscribeResponse>(value).map_err(|_| runtime_codec_protocol_failure()),
                            |message| serde_json::to_value(message).map_err(|_| runtime_codec_protocol_failure()),
                            |error| serde_json::to_value(error).map_err(|_| runtime_codec_protocol_failure()),
                        ))),
                        Err(error) => serde_json::to_value(error)
                            .map(Err)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn publish_host_event(&self, _dependency: lenso_kernel::PluginEventDependencyHandle, operation: String, _event: serde_json::Value, _context: InvocationContext) -> futures::future::LocalBoxFuture<'static, Result<(), RuntimeFailure>> {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
