// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.ui.global-contribution@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:07fe517309b7407f49060f5560482bb9ef982c86b1a873e7b3191cf71800c73b";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const GLOBAL_CONTRIBUTION_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const GLOBAL_CONTRIBUTION_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const GLOBAL_CONTRIBUTION_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const GLOBAL_CONTRIBUTION_CONTRACT: CapabilityReference<GlobalContributionClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_global_contribution { () => { "{\"capability_id\":\"lenso.ui.global-contribution@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"describe_contribution\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_global_contribution_client {
    () => { "{\"capability_id\":\"lenso.ui.global-contribution@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.ui.global-contribution@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_global_contribution_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.ui.global-contribution@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_global_contribution_client {
    () => { "{\"capability_id\":\"lenso.ui.global-contribution@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.ui.global-contribution@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const DESCRIBE_CONTRIBUTION_OPERATION: &str = "describe_contribution";

pub use lenso_contract_runtime::{OptionalValue, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Copy, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeContributionRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeContributionResponse {
    #[serde(rename = "assets")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub assets: Vec<DescribeContributionResponseAssetsItem>,
    #[serde(rename = "module")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub module: String,
    #[serde(rename = "navigation")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub navigation: DescribeContributionResponseNavigation,
    #[serde(rename = "requirements")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requirements: Vec<DescribeContributionResponseRequirementsItem>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "styles")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub styles: Vec<String>,
    #[serde(rename = "subject")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subject: Option<DescribeContributionResponseSubject>,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
    #[serde(rename = "workspace_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub workspace_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeContributionResponseAssetsItem {
    #[serde(rename = "content_base64")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub content_base64: String,
    #[serde(rename = "media_type")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub media_type: DescribeContributionResponseAssetsItemMediaType,
    #[serde(rename = "path")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub path: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum DescribeContributionResponseAssetsItemMediaType {
    #[serde(rename = "text/css; charset=utf-8")]
    TextCssCharsetUtf,
    #[serde(rename = "text/javascript; charset=utf-8")]
    TextJavascriptCharsetUtf,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeContributionResponseNavigation {
    #[serde(rename = "items")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub items: Vec<DescribeContributionResponseNavigationItemsItem>,
    #[serde(rename = "label")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub label: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeContributionResponseNavigationItemsItem {
    #[serde(rename = "label")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub label: String,
    #[serde(rename = "path")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub path: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeContributionResponseRequirementsItem {
    #[serde(rename = "capability_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub capability_id: String,
    #[serde(rename = "descriptor_version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub descriptor_version: String,
    #[serde(rename = "operations")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub operations: Vec<String>,
    #[serde(rename = "required")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub required: bool,
    #[serde(rename = "service_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub service_id: String,
    #[serde(rename = "source")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source: DescribeContributionResponseRequirementsItemSource,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum DescribeContributionResponseRequirementsItemSource {
    #[serde(rename = "owner")]
    Owner,
    #[serde(rename = "subject")]
    Subject,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct DescribeContributionResponseSubject {
    #[serde(rename = "app_id")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub app_id: OptionalValue<String>,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: DescribeContributionResponseSubjectKind,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum DescribeContributionResponseSubjectKind {
    #[serde(rename = "console")]
    Console,
    #[serde(rename = "app")]
    App,
}

#[derive(Clone, Debug, PartialEq)]
pub enum DescribeContributionError {
    ContributionUnavailable,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct GlobalContribution;
impl RequestCapability for GlobalContribution {
    type Request = DescribeContributionRequest;
    type Response = DescribeContributionResponse;
    type DomainError = DescribeContributionError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != DESCRIBE_CONTRIBUTION_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<GlobalContributionRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).describe_contribution(context, request)
    }
}

impl serde::Serialize for DescribeContributionError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ContributionUnavailable => serializer.serialize_str("contribution_unavailable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for DescribeContributionError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "contribution_unavailable" => Ok(Self::ContributionUnavailable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_describe_contribution_request(value: &DescribeContributionRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_describe_contribution_request(wire: &str) -> Result<DescribeContributionRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_describe_contribution_response(value: &DescribeContributionResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_describe_contribution_response(wire: &str) -> Result<DescribeContributionResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_describe_contribution_error(value: &DescribeContributionError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_describe_contribution_error(wire: &str) -> Result<DescribeContributionError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoGlobalContributionDescribeContributionResult {
    fn __lenso_into_result(self) -> Result<Result<DescribeContributionResponse, DescribeContributionError>, RuntimeFailure>;
}
impl __LensoIntoGlobalContributionDescribeContributionResult for Result<DescribeContributionResponse, DescribeContributionError> {
    fn __lenso_into_result(self) -> Result<Result<DescribeContributionResponse, DescribeContributionError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoGlobalContributionDescribeContributionResult for Result<Result<DescribeContributionResponse, DescribeContributionError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<DescribeContributionResponse, DescribeContributionError>, RuntimeFailure> { self }
}
impl __LensoIntoGlobalContributionDescribeContributionResult for Result<DescribeContributionResponse, lenso_plugin_authoring::PluginError<DescribeContributionError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<DescribeContributionResponse, DescribeContributionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoGlobalContributionDescribeContributionResult for Result<DescribeContributionResponse, GlobalContributionInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<DescribeContributionResponse, DescribeContributionError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(GlobalContributionInvocationError::Domain(error)) => Ok(Err(error)),
            Err(GlobalContributionInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait GlobalContributionProvider: fmt::Debug + 'static {
    fn describe_contribution(&self, context: InvocationContext, request: DescribeContributionRequest) -> NativeRequestFuture<GlobalContribution>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_global_contribution {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportGlobalContribution;
        impl $crate::GlobalContributionProvider for $plugin {
        fn describe_contribution(&self, context: __LensoNativeSupportGlobalContribution::InvocationContext, request: $crate::DescribeContributionRequest) -> __LensoNativeSupportGlobalContribution::NativeRequestFuture<$crate::GlobalContribution> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::describe_contribution(&plugin, context, request).await;
                $crate::__LensoIntoGlobalContributionDescribeContributionResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_global_contribution {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportGlobalContribution;
        impl $crate::GlobalContributionProvider for $object {
        fn describe_contribution(&self, context: __LensoNativeSupportGlobalContribution::InvocationContext, request: $crate::DescribeContributionRequest) -> __LensoNativeSupportGlobalContribution::NativeRequestFuture<$crate::GlobalContribution> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::describe_contribution(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoGlobalContributionDescribeContributionResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_global_contribution {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportGlobalContribution;
        impl $crate::GlobalContributionProvider for $object {
        fn describe_contribution(&self, context: __LensoNativeSupportGlobalContribution::InvocationContext, request: $crate::DescribeContributionRequest) -> __LensoNativeSupportGlobalContribution::NativeRequestFuture<$crate::GlobalContribution> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::GlobalContributionProvider>::describe_contribution(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct GlobalContributionRequestEndpoint { provider: Rc<dyn GlobalContributionProvider> }

#[derive(Debug)]
pub struct GlobalContributionEndpoint<P: GlobalContributionProvider> { provider: Rc<P>, request_endpoint: GlobalContributionRequestEndpoint }
impl<P: GlobalContributionProvider> GlobalContributionEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn GlobalContributionProvider> = provider.clone();
        Self { provider, request_endpoint: GlobalContributionRequestEndpoint { provider: request_provider } }
    }
}

impl<P: GlobalContributionProvider> NativeRequestEndpoint for GlobalContributionEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        DESCRIBE_CONTRIBUTION_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            DESCRIBE_CONTRIBUTION_OPERATION => {
                let Ok(request) = request.downcast::<DescribeContributionRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).describe_contribution(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_global_contribution {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::GlobalContributionEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_global_contribution {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_global_contribution!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct GlobalContributionClient {
    describe_contribution: NativeRequestHandle<GlobalContribution>,
}
impl GlobalContributionClient {
    pub fn new(handle: NativeRequestHandle<GlobalContribution>) -> Self {
        Self { describe_contribution: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn describe_contribution(&self, request: DescribeContributionRequest) -> Result<DescribeContributionResponse, GlobalContributionInvocationError> {
        self.describe_contribution.invoke(DESCRIBE_CONTRIBUTION_OPERATION, request).await
            .map_err(GlobalContributionInvocationError::Runtime)?
            .map_err(GlobalContributionInvocationError::Domain)
    }

    pub async fn describe_contribution_with_context(&self, context: InvocationContext, request: DescribeContributionRequest) -> Result<DescribeContributionResponse, GlobalContributionInvocationError> {
        self.describe_contribution.invoke_with_context(DESCRIBE_CONTRIBUTION_OPERATION, context, request).await
            .map_err(GlobalContributionInvocationError::Runtime)?
            .map_err(GlobalContributionInvocationError::Domain)
    }
}

impl CapabilityClient for GlobalContributionClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            describe_contribution: dependencies.one::<GlobalContribution>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for GlobalContributionClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    describe_contribution: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<GlobalContribution>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum GlobalContributionInvocationError {
    Domain(DescribeContributionError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct GlobalContributionGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> GlobalContributionGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[DESCRIBE_CONTRIBUTION_OPERATION], &[], &[])
            .map(|capability| Self { capability })
    }

    pub fn describe_contribution(&self, request: &DescribeContributionRequest) -> Result<DescribeContributionResponse, lenso_guest_sdk::GuestError<DescribeContributionError>> {
        self.capability.request(DESCRIBE_CONTRIBUTION_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct GlobalContributionJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for GlobalContributionJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn descriptor_digest(&self) -> &'static str { DESCRIPTOR_DIGEST }

    fn request_operations(&self) -> &'static [&'static str] { &[DESCRIBE_CONTRIBUTION_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[] }
    fn event_operations(&self) -> &'static [&'static str] { &[] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            DESCRIBE_CONTRIBUTION_OPERATION => {
                let value = request.downcast_ref::<DescribeContributionRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            DESCRIBE_CONTRIBUTION_OPERATION => serde_json::from_value::<DescribeContributionResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            DESCRIBE_CONTRIBUTION_OPERATION => serde_json::from_value::<DescribeContributionError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, _request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_stream_message(&self, operation: &str, _message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_message(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_domain_error(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_event(&self, operation: &str, _event: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::PluginDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            DESCRIBE_CONTRIBUTION_OPERATION => {
                let request = serde_json::from_value::<DescribeContributionRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<GlobalContribution>()?;
                    match handle.invoke_with_context(DESCRIBE_CONTRIBUTION_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, _dependency: lenso_kernel::PluginStreamDependencyHandle, operation: String, _request: serde_json::Value, _context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }

    fn publish_host_event(&self, _dependency: lenso_kernel::PluginEventDependencyHandle, operation: String, _event: serde_json::Value, _context: InvocationContext) -> futures::future::LocalBoxFuture<'static, Result<(), RuntimeFailure>> {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
