/* eslint-disable sort-keys */

import * as stylex from "@stylexjs/stylex";

/**
 * The public, typed semantic token surface. Values are compiled by StyleX and
 * remain replaceable by a Host Theme at runtime.
 */
export const tokens = stylex.defineVars({
  canvas: "var(--lenso-token-canvas, #000000)",
  window: "var(--lenso-token-window, #000000)",
  surface: "var(--lenso-token-surface, #000000)",
  surfaceRaised: "var(--lenso-token-surfaceRaised, #0a0a0a)",
  surfaceMuted: "var(--lenso-token-surfaceMuted, #0a0a0a)",
  panel: "var(--lenso-token-panel, #000000)",
  panelMuted: "var(--lenso-token-panelMuted, #050505)",
  panelHeader: "var(--lenso-token-panelHeader, #0a0a0a)",
  rowHover: "var(--lenso-token-rowHover, #111111)",
  rowSelected: "var(--lenso-token-rowSelected, #1f1f1f)",
  control: "var(--lenso-token-control, #000000)",
  controlHover: "var(--lenso-token-controlHover, #111111)",
  controlActive: "var(--lenso-token-controlActive, #1a1a1a)",
  overlay: "var(--lenso-token-overlay, #000000)",
  sidebar: "var(--lenso-token-sidebar, #0a0a0a)",
  foreground: "var(--lenso-token-foreground, #ffffff)",
  foregroundSecondary: "var(--lenso-token-foregroundSecondary, #d4d4d4)",
  foregroundTertiary: "var(--lenso-token-foregroundTertiary, #737373)",
  foregroundQuaternary: "var(--lenso-token-foregroundQuaternary, #525252)",
  foregroundOnAccent: "var(--lenso-token-foregroundOnAccent, #000000)",
  foregroundInverse: "var(--lenso-token-foregroundInverse, #000000)",
  line: "var(--lenso-token-line, #333333)",
  lineSubtle: "var(--lenso-token-lineSubtle, #1f1f1f)",
  lineStrong: "var(--lenso-token-lineStrong, #444444)",
  accent: "var(--lenso-token-accent, #ffffff)",
  accentHover: "var(--lenso-token-accentHover, #ffffff)",
  accentMuted: "var(--lenso-token-accentMuted, rgba(255, 255, 255, 0.08))",
  accentForeground: "var(--lenso-token-accentForeground, #000000)",
  success: "var(--lenso-token-success, #00a63e)",
  warning: "var(--lenso-token-warning, #f5a524)",
  error: "var(--lenso-token-error, #e5484d)",
  info: "var(--lenso-token-info, #0070f3)",
  toneMutedBg: "var(--lenso-token-toneMutedBg, rgba(255, 255, 255, 0.06))",
  toneMutedBorder:
    "var(--lenso-token-toneMutedBorder, rgba(255, 255, 255, 0.14))",
  toneMutedForeground: "var(--lenso-token-toneMutedForeground, #d4d4d4)",
  toneInfoBg: "var(--lenso-token-toneInfoBg, rgba(0, 112, 243, 0.12))",
  toneInfoBorder: "var(--lenso-token-toneInfoBorder, rgba(0, 112, 243, 0.3))",
  toneInfoForeground: "var(--lenso-token-toneInfoForeground, #d4d4d4)",
  toneSuccessBg: "var(--lenso-token-toneSuccessBg, rgba(0, 166, 62, 0.12))",
  toneSuccessBorder:
    "var(--lenso-token-toneSuccessBorder, rgba(0, 166, 62, 0.28))",
  toneSuccessForeground: "var(--lenso-token-toneSuccessForeground, #00a63e)",
  toneWarningBg: "var(--lenso-token-toneWarningBg, rgba(245, 165, 36, 0.12))",
  toneWarningBorder:
    "var(--lenso-token-toneWarningBorder, rgba(245, 165, 36, 0.3))",
  toneWarningForeground: "var(--lenso-token-toneWarningForeground, #f5a524)",
  toneErrorBg: "var(--lenso-token-toneErrorBg, rgba(229, 72, 77, 0.13))",
  toneErrorBorder:
    "var(--lenso-token-toneErrorBorder, rgba(229, 72, 77, 0.32))",
  toneErrorForeground: "var(--lenso-token-toneErrorForeground, #ff8589)",
  focusRing: "var(--lenso-token-focusRing, rgba(255, 255, 255, 0.72))",
  focusRingMuted:
    "var(--lenso-token-focusRingMuted, rgba(255, 255, 255, 0.22))",
  radiusControl: "var(--lenso-token-radiusControl, 6px)",
  radiusPanel: "var(--lenso-token-radiusPanel, 6px)",
  radiusPopover: "var(--lenso-token-radiusPopover, 8px)",
  radiusPill: "var(--lenso-token-radiusPill, 999px)",
  controlHeightSm: "var(--lenso-token-controlHeightSm, 28px)",
  controlHeightMd: "var(--lenso-token-controlHeightMd, 32px)",
  controlHeightLg: "var(--lenso-token-controlHeightLg, 36px)",
  space1: "var(--lenso-token-space1, 4px)",
  space1_5: "var(--lenso-token-space1_5, 6px)",
  space2: "var(--lenso-token-space2, 8px)",
  space3: "var(--lenso-token-space3, 12px)",
  space4: "var(--lenso-token-space4, 16px)",
  space5: "var(--lenso-token-space5, 20px)",
  space6: "var(--lenso-token-space6, 24px)",
  space8: "var(--lenso-token-space8, 32px)",
  fontUi: 'var(--lenso-token-fontUi, "IBM Plex Sans", sans-serif)',
  fontCode: 'var(--lenso-token-fontCode, "Roboto Mono", monospace)',
  contentGutter: "var(--lenso-token-contentGutter, 20px)",
  contentMaxWidth: "var(--lenso-token-contentMaxWidth, 1480px)",
  pageGutter: "var(--lenso-token-pageGutter, 32px)",
  pageMaxWidth: "var(--lenso-token-pageMaxWidth, 1216px)",
  sidebarWidth: "var(--lenso-token-sidebarWidth, 224px)",
  sidebarCollapsedWidth: "var(--lenso-token-sidebarCollapsedWidth, 64px)",
  toolbarHeight: "var(--lenso-token-toolbarHeight, 48px)",
  inspectorWidth: "var(--lenso-token-inspectorWidth, 376px)",
  tableRowHeight: "var(--lenso-token-tableRowHeight, 64px)",
  tableHeaderHeight: "var(--lenso-token-tableHeaderHeight, 38px)",
  paneHeaderHeight: "var(--lenso-token-paneHeaderHeight, 50px)",
  tabHeight: "var(--lenso-token-tabHeight, 33px)",
  shadowControl: "var(--lenso-token-shadowControl, none)",
  shadowPanel: "var(--lenso-token-shadowPanel, none)",
  shadowRaised:
    "var(--lenso-token-shadowRaised, 0 1px 0 rgba(255, 255, 255, 0.035))",
  shadowOverlay:
    "var(--lenso-token-shadowOverlay, 0 24px 70px -42px rgba(0, 0, 0, 0.88), 0 1px 0 rgba(255, 255, 255, 0.05))",
});

export const lightTheme = stylex.createTheme(tokens, {
  canvas: "#ffffff",
  window: "#ffffff",
  surface: "#ffffff",
  surfaceRaised: "#fafafa",
  surfaceMuted: "#fafafa",
  panel: "#ffffff",
  panelMuted: "#fafafa",
  panelHeader: "#fafafa",
  rowHover: "#f5f5f5",
  rowSelected: "#f5f5f5",
  control: "#ffffff",
  controlHover: "#f5f5f5",
  controlActive: "#eeeeee",
  overlay: "#ffffff",
  sidebar: "#fafafa",
  foreground: "#000000",
  foregroundSecondary: "#444444",
  foregroundTertiary: "#666666",
  foregroundQuaternary: "#999999",
  foregroundOnAccent: "#ffffff",
  foregroundInverse: "#ffffff",
  line: "#d4d4d4",
  lineSubtle: "#f2f2f2",
  lineStrong: "#d4d4d4",
  accent: "#000000",
  accentHover: "#333333",
  accentMuted: "#f5f5f5",
  accentForeground: "#ffffff",
  success: "#007a3d",
  warning: "#b45309",
  error: "#dc2626",
  toneMutedBg: "#fafafa",
  toneMutedBorder: "#eaeaea",
  toneMutedForeground: "#444444",
  toneInfoBg: "#f0f7ff",
  toneInfoBorder: "#bbe0ff",
  toneInfoForeground: "#0068d6",
  toneSuccessBg: "#f0fff4",
  toneSuccessBorder: "#b7ebc6",
  toneSuccessForeground: "#007a3d",
  toneWarningBg: "#fffbeb",
  toneWarningBorder: "#f5d590",
  toneWarningForeground: "#8a5a00",
  toneErrorBg: "rgba(220, 38, 38, 0.08)",
  toneErrorBorder: "rgba(220, 38, 38, 0.24)",
  toneErrorForeground: "#dc2626",
  focusRing: "rgba(0, 0, 0, 0.5)",
  focusRingMuted: "rgba(0, 0, 0, 0.14)",
  shadowOverlay:
    "0 24px 70px -44px rgba(0, 0, 0, 0.32), 0 1px 1px rgba(0, 0, 0, 0.08)",
});

export const darkTheme = stylex.createTheme(tokens, {});

export const tokenNames = {
  canvas: "canvas",
  window: "window",
  surface: "surface",
  surfaceRaised: "surfaceRaised",
  surfaceMuted: "surfaceMuted",
  panel: "panel",
  panelMuted: "panelMuted",
  panelHeader: "panelHeader",
  rowHover: "rowHover",
  rowSelected: "rowSelected",
  control: "control",
  controlHover: "controlHover",
  controlActive: "controlActive",
  overlay: "overlay",
  sidebar: "sidebar",
  foreground: "foreground",
  foregroundSecondary: "foregroundSecondary",
  foregroundTertiary: "foregroundTertiary",
  foregroundQuaternary: "foregroundQuaternary",
  foregroundOnAccent: "foregroundOnAccent",
  foregroundInverse: "foregroundInverse",
  line: "line",
  lineSubtle: "lineSubtle",
  lineStrong: "lineStrong",
  accent: "accent",
  accentHover: "accentHover",
  accentMuted: "accentMuted",
  accentForeground: "accentForeground",
  success: "success",
  warning: "warning",
  error: "error",
  info: "info",
  toneMutedBg: "toneMutedBg",
  toneMutedBorder: "toneMutedBorder",
  toneMutedForeground: "toneMutedForeground",
  toneInfoBg: "toneInfoBg",
  toneInfoBorder: "toneInfoBorder",
  toneInfoForeground: "toneInfoForeground",
  toneSuccessBg: "toneSuccessBg",
  toneSuccessBorder: "toneSuccessBorder",
  toneSuccessForeground: "toneSuccessForeground",
  toneWarningBg: "toneWarningBg",
  toneWarningBorder: "toneWarningBorder",
  toneWarningForeground: "toneWarningForeground",
  toneErrorBg: "toneErrorBg",
  toneErrorBorder: "toneErrorBorder",
  toneErrorForeground: "toneErrorForeground",
  focusRing: "focusRing",
  focusRingMuted: "focusRingMuted",
  radiusControl: "radiusControl",
  radiusPanel: "radiusPanel",
  radiusPopover: "radiusPopover",
  radiusPill: "radiusPill",
  controlHeightSm: "controlHeightSm",
  controlHeightMd: "controlHeightMd",
  controlHeightLg: "controlHeightLg",
  space1: "space1",
  space1_5: "space1_5",
  space2: "space2",
  space3: "space3",
  space4: "space4",
  space5: "space5",
  space6: "space6",
  space8: "space8",
  fontUi: "fontUi",
  fontCode: "fontCode",
  contentGutter: "contentGutter",
  contentMaxWidth: "contentMaxWidth",
  pageGutter: "pageGutter",
  pageMaxWidth: "pageMaxWidth",
  sidebarWidth: "sidebarWidth",
  sidebarCollapsedWidth: "sidebarCollapsedWidth",
  toolbarHeight: "toolbarHeight",
  inspectorWidth: "inspectorWidth",
  tableRowHeight: "tableRowHeight",
  tableHeaderHeight: "tableHeaderHeight",
  paneHeaderHeight: "paneHeaderHeight",
  tabHeight: "tabHeight",
  shadowControl: "shadowControl",
  shadowPanel: "shadowPanel",
  shadowRaised: "shadowRaised",
  shadowOverlay: "shadowOverlay",
} as const;

export type ConsoleTokenName = keyof typeof tokenNames;

/** Stable CSS variable names for Host-owned Theme Bundle overrides. */
export const tokenCssVariables = Object.fromEntries(
  Object.keys(tokenNames).map((name) => [name, `--lenso-token-${name}`])
) as Record<ConsoleTokenName, `--lenso-token-${string}`>;

/**
 * Legacy Host variable aliases retained for the global reset and page
 * contracts while those contracts move to named StyleX slots. Theme Bundle
 * overrides set both names so old and StyleX-authored surfaces stay in sync.
 */
export const legacyTokenCssVariables = {
  canvas: "--bg-canvas",
  window: "--bg-window",
  surface: "--bg-surface",
  surfaceRaised: "--bg-surface-raised",
  surfaceMuted: "--bg-surface-muted",
  panel: "--bg-panel",
  panelMuted: "--bg-panel-muted",
  panelHeader: "--bg-panel-header",
  rowHover: "--bg-row-hover",
  rowSelected: "--bg-row-selected",
  control: "--bg-control",
  controlHover: "--bg-control-hover",
  controlActive: "--bg-control-active",
  overlay: "--bg-overlay",
  sidebar: "--bg-sidebar",
  foreground: "--fg-primary",
  foregroundSecondary: "--fg-secondary",
  foregroundTertiary: "--fg-tertiary",
  foregroundQuaternary: "--fg-quaternary",
  foregroundOnAccent: "--fg-on-accent",
  foregroundInverse: "--fg-inverse",
  line: "--line",
  lineSubtle: "--line-subtle",
  lineStrong: "--line-strong",
  accent: "--accent",
  accentHover: "--accent-hover",
  accentMuted: "--accent-muted",
  accentForeground: "--accent-foreground",
  success: "--success",
  warning: "--warning",
  error: "--error",
  info: "--info",
  toneMutedBg: "--tone-muted-bg",
  toneMutedBorder: "--tone-muted-border",
  toneMutedForeground: "--tone-muted-fg",
  toneInfoBg: "--tone-info-bg",
  toneInfoBorder: "--tone-info-border",
  toneInfoForeground: "--tone-info-fg",
  toneSuccessBg: "--tone-success-bg",
  toneSuccessBorder: "--tone-success-border",
  toneSuccessForeground: "--tone-success-fg",
  toneWarningBg: "--tone-warning-bg",
  toneWarningBorder: "--tone-warning-border",
  toneWarningForeground: "--tone-warning-fg",
  toneErrorBg: "--tone-error-bg",
  toneErrorBorder: "--tone-error-border",
  toneErrorForeground: "--tone-error-fg",
  focusRing: "--focus-ring",
  focusRingMuted: "--focus-ring-muted",
  radiusControl: "--radius-control",
  radiusPanel: "--radius-panel",
  radiusPopover: "--radius-popover",
  radiusPill: "--radius-pill",
  controlHeightSm: "--control-height-sm",
  controlHeightMd: "--control-height-md",
  controlHeightLg: "--control-height-lg",
  space1: "--space-1",
  space1_5: "--space-1-5",
  space2: "--space-2",
  space3: "--space-3",
  space4: "--space-4",
  space5: "--space-5",
  space6: "--space-6",
  space8: "--space-8",
  fontUi: "--font-ui",
  fontCode: "--font-code",
  contentGutter: "--content-gutter",
  contentMaxWidth: "--content-max-width",
  pageGutter: "--console-page-gutter",
  pageMaxWidth: "--console-page-max-width",
  sidebarWidth: "--console-sidebar-width",
  sidebarCollapsedWidth: "--console-sidebar-collapsed-width",
  toolbarHeight: "--console-toolbar-height",
  inspectorWidth: "--console-inspector-width",
  tableRowHeight: "--console-table-row-height",
  tableHeaderHeight: "--console-table-header-height",
  paneHeaderHeight: "--console-pane-header-height",
  tabHeight: "--console-tab-height",
  shadowControl: "--elevation-control",
  shadowPanel: "--elevation-panel",
  shadowRaised: "--elevation-raised",
  shadowOverlay: "--elevation-overlay",
} as Record<ConsoleTokenName, `--${string}`>;
