import type { ConsoleLocale } from "@lenso/console-package-api";

const copy = {
  en: {
    nav: {
      home: "Home",
      system: "System",
      modules: "Modules",
      changes: "Changes",
      runtime: "Runtime",
      stories: "Stories",
      delivery: "Delivery",
      settings: "Settings",
    },
    production: "Production",
    search: "Search or run command",
    updated: "Updated 12s ago",
    workspace: "Workspace",
    operator: "Operator",
  },
  "zh-CN": {
    nav: {
      home: "首页",
      system: "系统",
      modules: "模块",
      changes: "变更",
      runtime: "运行时",
      stories: "业务故事",
      delivery: "交付",
      settings: "设置",
    },
    production: "生产环境",
    search: "搜索或运行命令",
    updated: "12 秒前更新",
    workspace: "工作区",
    operator: "操作员",
  },
} as const;

export function consoleCopy(locale: ConsoleLocale) {
  return copy[locale];
}

const product = {
  en: {
    common: {
      demo: "Demo projection",
      live: "Live",
      noData: "No evidence in this window.",
    },
    home: {
      title: "Operations",
      description:
        "Understand what changed, decide what needs action, and verify the result.",
      decisionQueue: "Decision queue",
      liveEvidence: "Live evidence",
      viewAll: "View all",
      streaming: "Streaming",
      runtime: "Runtime",
      activeChanges: "Active changes",
      awaitingApproval: "Awaiting approval",
      evidenceLag: "Evidence lag",
    },
    system: {
      title: "System Inventory",
      description:
        "Inventory, ownership boundaries, and the runtime evidence behind each capability.",
      capabilities: "Capabilities",
      capability: "Capability",
      kind: "Kind",
      owner: "Owner",
      state: "State",
      execution: "Execution source",
      boundary: "Ownership boundary",
      surfaces: "Console surfaces",
      evidence: "Runtime evidence",
    },
    modules: {
      title: "Modules",
      description:
        "Installed capabilities, loading sources, and Console surfaces registered with this host.",
      registry: "Registry",
      module: "Module",
      source: "Source",
      state: "State",
      surfaces: "Surfaces",
      manifest: "Manifest declaration",
      authority: "Authority",
    },
    changes: {
      title: "Changes",
      description:
        "Review bounded plans, approve consequential actions, and follow verification evidence.",
      tabs: ["Active", "Drafts", "Completed", "Recovered"],
      priority: "Priority order",
      filter: "Filter",
      intent: "Intent",
      plan: "Plan",
      blast: "Blast radius",
      approval: "Approval",
      verification: "Verification contract",
      recovery: "Recovery",
      approve: "Approve & apply",
    },
    runtime: {
      title: "Runtime",
      description:
        "Observe live services, operations, queues, and the evidence each transition emits.",
      tabs: ["Services", "Operations", "Outbox", "Events"],
      service: "Service",
      region: "Region",
      version: "Version",
      state: "State",
      timeline: "Execution timeline",
      authority: "Authority",
    },
    delivery: {
      title: "Delivery",
      description:
        "Prepare reviewed release handoffs and verify deployments without claiming production authority.",
      candidates: "Release candidates",
      authority: "Production authority: external",
      readiness: "Readiness gates",
      handoff: "Prepare handoff",
      noRelease: "No release evidence has been recorded.",
    },
    settings: {
      title: "Settings",
      description:
        "Personalize the Console without changing service-owned runtime state.",
      appearance: "Appearance",
      theme: "Theme",
      themeDescription: "Choose a theme or follow your operating system.",
      language: "Language",
      consoleLanguage: "Console language",
      languageDescription:
        "Applies to host navigation and extensions using the Console locale interface.",
      locale: "Locale",
      timeZone: "Time zone",
      timeZoneDescription:
        "Used to present timestamps without changing the source evidence.",
      followSystem: "System",
      dark: "Dark",
      light: "Light",
      console: "Console",
      command: "Command menu",
      commandDescription: "Open the command palette from anywhere.",
      sidebar: "Sidebar",
      sidebarDescription: "Collapse or expand the workspace navigation.",
    },
  },
  "zh-CN": {
    common: { demo: "演示投影", live: "实时", noData: "当前窗口暂无证据。" },
    home: {
      title: "运营",
      description: "理解发生了什么变化，决定哪些需要处理，并验证最终结果。",
      decisionQueue: "决策队列",
      liveEvidence: "实时证据",
      viewAll: "查看全部",
      streaming: "持续更新",
      runtime: "运行时",
      activeChanges: "活跃变更",
      awaitingApproval: "等待审批",
      evidenceLag: "证据延迟",
    },
    system: {
      title: "系统清单",
      description: "查看能力、所有权边界及支撑每项能力的运行时证据。",
      capabilities: "能力",
      capability: "能力",
      kind: "类型",
      owner: "所有者",
      state: "状态",
      execution: "执行来源",
      boundary: "所有权边界",
      surfaces: "Console 页面",
      evidence: "运行时证据",
    },
    modules: {
      title: "模块",
      description:
        "查看已安装能力、加载来源以及向当前宿主注册的 Console 页面。",
      registry: "注册表",
      module: "模块",
      source: "来源",
      state: "状态",
      surfaces: "页面",
      manifest: "Manifest 声明",
      authority: "权责边界",
    },
    changes: {
      title: "变更",
      description: "审查有边界的计划，批准关键操作，并跟踪验证证据。",
      tabs: ["活跃", "草稿", "已完成", "已恢复"],
      priority: "优先级排序",
      filter: "筛选",
      intent: "意图",
      plan: "计划",
      blast: "影响范围",
      approval: "审批",
      verification: "验证契约",
      recovery: "恢复",
      approve: "批准并应用",
    },
    runtime: {
      title: "运行时",
      description: "观察在线服务、操作、队列以及每次状态迁移产生的证据。",
      tabs: ["服务", "操作", "发件箱", "事件"],
      service: "服务",
      region: "区域",
      version: "版本",
      state: "状态",
      timeline: "执行时间线",
      authority: "权责边界",
    },
    delivery: {
      title: "交付",
      description: "准备经审查的发布交接并验证部署，但不宣称生产发布权限。",
      candidates: "候选版本",
      authority: "生产权限：外部",
      readiness: "就绪门禁",
      handoff: "准备交接",
      noRelease: "尚未记录发布证据。",
    },
    settings: {
      title: "设置",
      description: "个性化 Console，但不改变由服务持有的运行时状态。",
      appearance: "外观",
      theme: "主题",
      themeDescription: "选择主题，或跟随操作系统。",
      language: "语言",
      consoleLanguage: "Console 语言",
      languageDescription:
        "应用于宿主导航及使用 Console locale 接口的 extension。",
      locale: "区域设置",
      timeZone: "时区",
      timeZoneDescription: "用于显示时间戳，不改变来源证据。",
      followSystem: "跟随系统",
      dark: "深色",
      light: "浅色",
      console: "Console",
      command: "命令菜单",
      commandDescription: "在任何页面打开命令面板。",
      sidebar: "侧边栏",
      sidebarDescription: "折叠或展开工作区导航。",
    },
  },
} as const;

export function consoleProductCopy(locale: ConsoleLocale) {
  return product[locale];
}
