import type { ConsoleLocale } from "@lenso/console-ui";

const copy = {
  en: {
    nav: {
      home: "Home",
      services: "Services",
      system: "System",
      modules: "Modules",
      changes: "Changes",
      runtime: "Runtime",
      stories: "Stories",
      delivery: "Delivery",
      settings: "Settings",
    },
    production: "Production",
    search: "Search or run command",
    updated: "Updated 12s ago",
    workspace: "Workspace",
    operator: "Operator",
  },
  "zh-CN": {
    nav: {
      home: "首页",
      services: "服务",
      system: "系统",
      modules: "模块",
      changes: "变更",
      runtime: "运行时",
      stories: "业务故事",
      delivery: "交付",
      settings: "设置",
    },
    production: "生产环境",
    search: "搜索或运行命令",
    updated: "12 秒前更新",
    workspace: "工作区",
    operator: "操作员",
  },
} as const;

export function consoleCopy(locale: ConsoleLocale) {
  return copy[locale];
}

const product = {
  en: {
    common: {
      demo: "Demo projection",
      live: "Live",
      noData: "No evidence in this window.",
    },
    home: {
      title: "Operations",
      description:
        "Understand what changed, decide what needs action, and verify the result.",
      decisionQueue: "Decision queue",
      liveEvidence: "Live evidence",
      viewAll: "View all",
      streaming: "Streaming",
      runtime: "Runtime",
      activeChanges: "Active changes",
      awaitingApproval: "Awaiting approval",
      evidenceLag: "Evidence lag",
    },
    system: {
      title: "System Inventory",
      description:
        "Inventory, ownership boundaries, and the runtime evidence behind each capability.",
      capabilities: "Capabilities",
      services: "Services",
      capability: "Capability",
      kind: "Kind",
      owner: "Owner",
      state: "State",
      allKinds: "All kinds",
      allOwners: "All owners",
      healthyDegraded: "Healthy + degraded",
      module: "Module",
      service: "Service",
      healthy: "Healthy",
      degraded: "Degraded",
      noMatches: "No capabilities match these filters.",
      execution: "Execution source",
      boundary: "Ownership boundary",
      surfaces: "Console surfaces",
      evidence: "Runtime evidence",
    },
    modules: {
      title: "Surfaces",
      description:
        "Registration and navigation health for Console surfaces and their owning packages.",
      registry: "Navigation registrations",
      registered: "registered",
      moduleCount: "modules",
      module: "Module",
      source: "Source",
      state: "State",
      surfaces: "Surfaces",
      surface: "Surface",
      placement: "Placement",
      registration: "Registration",
      allSources: "All sources",
      allAreas: "All areas",
      allStates: "All states",
      registeredState: "Registered",
      manifest: "Manifest declaration",
      ownership: "Package resolution",
      identity: "Resolved identity",
      executionEvidence: "Execution evidence",
      protocol: "Protocol major",
      entry: "Entrypoint",
      entries: "Artifact entries",
      permissions: "Granted permissions",
      removalPreview: "Removal preview",
      removalSurfaceImpact: "Console surfaces removed",
      removalAuthority:
        "Preview only. App Composition remains the removal authority.",
      navigation: "Navigation placement",
      evidence: "Access gate",
      defaultFromArea: "Default from area",
      group: "Group",
      capabilityGranted: "Capability granted",
      routeRegistered: "Route registered",
      openSystem: "Open in System",
      noMatches: "No registrations match these filters.",
      noCapabilities: "No capability gate declared.",
      sourceLinked: "linked",
      sourceService: "service",
      sourceFirstParty: "first_party",
      sourceInstalled: "installed",
      sourceRuntimeBundle: "runtime_bundle",
      authority: "Authority",
    },
    changes: {
      title: "Changes",
      description:
        "Review bounded plans, approve consequential actions, and follow verification evidence.",
      active: "active",
      awaitingYou: "awaiting you",
      tabs: ["Active", "Drafts", "Completed", "Recovered"],
      filterAttention: "Needs attention",
      filterVerified: "Verified",
      noRecords: "No change records in this view.",
      priority: "Priority order",
      filter: "Filter",
      intent: "Intent",
      plan: "Plan",
      blast: "Blast radius",
      approval: "Approval",
      verification: "Verification contract",
      recovery: "Recovery",
      approve: "Approve & apply",
    },
    runtime: {
      title: "Operations",
      description:
        "Observe live operations, outbox delivery, and the evidence each transition emits.",
      tabs: ["Operations", "Outbox", "Events"],
      healthy: "healthy",
      observed: "observed",
      services: "services",
      modules: "modules",
      checks: "checks",
      service: "Service",
      region: "Region",
      version: "Version",
      state: "State",
      timeline: "Execution timeline",
      authority: "Authority",
      serviceOwns: "Service owns runtime state and effects.",
      consoleObserves: "Console observes, coordinates, and retains evidence.",
    },
    delivery: {
      title: "Releases",
      description:
        "Prepare reviewed release handoffs and verify deployments without claiming production authority.",
      candidates: "Release candidates",
      open: "open",
      authority: "Production authority: external",
      readiness: "Readiness gates",
      artifacts: "Artifacts",
      approvals: "Approvals",
      statusAge: "Status age",
      handoff: "Prepare handoff",
      handoffTitle: "Authority handoff",
      handoffDescription:
        "Console packages the reviewed plan, receipts, and verification contract.",
      authorityDescription:
        "A separate release authority decides and executes the production release.",
      gateRecorded: "Passed",
      gateNotRecorded: "Pending",
      planApproved: "Approved · Leo + Mina",
      contracts: "Contracts generated and clean",
      workspaceQuality: "Workspace quality gate",
      cargoInstall: "Fresh Cargo install",
      npmInstall: "Fresh npm install",
      publishedAcceptance: "Acceptance in published mode",
      reviewedPlan: "Reviewed release plan",
      readyForHandoff: "Ready for handoff",
      needsAttention: "Needs attention",
      draft: "Draft",
      verified: "Verified",
      noRelease: "No release status is available.",
    },
    settings: {
      title: "Settings",
      description:
        "Workspace policy, approvals, evidence retention, and Console preferences.",
      appearance: "Appearance",
      theme: "Theme",
      themeDescription: "Choose a theme or follow your operating system.",
      language: "Language",
      consoleLanguage: "Language",
      languageDescription: "Controls Console navigation and operator text.",
      locale: "Locale",
      timeZone: "Timezone",
      timeZoneDescription:
        "Used to present timestamps without changing the source evidence.",
      followSystem: "System",
      dark: "Dark",
      light: "Light",
      unsaved: "Unsaved changes",
      saved: "Saved",
      noChanges: "No changes",
      console: "Console",
      command: "Command menu",
      commandDescription: "Open the command palette from anywhere.",
      sidebar: "Sidebar",
      sidebarDescription: "Collapse or expand the workspace navigation.",
    },
  },
  "zh-CN": {
    common: { demo: "演示投影", live: "实时", noData: "当前窗口暂无证据。" },
    home: {
      title: "运营",
      description: "理解发生了什么变化，决定哪些需要处理，并验证最终结果。",
      decisionQueue: "决策队列",
      liveEvidence: "实时证据",
      viewAll: "查看全部",
      streaming: "持续更新",
      runtime: "运行时",
      activeChanges: "活跃变更",
      awaitingApproval: "等待审批",
      evidenceLag: "证据延迟",
    },
    system: {
      title: "系统清单",
      description: "查看能力、所有权边界及支撑每项能力的运行时证据。",
      capabilities: "能力",
      services: "服务",
      capability: "能力",
      kind: "类型",
      owner: "所有者",
      state: "状态",
      allKinds: "全部类型",
      allOwners: "全部所有者",
      healthyDegraded: "健康 + 降级",
      module: "模块",
      service: "服务",
      healthy: "健康",
      degraded: "降级",
      noMatches: "没有符合当前筛选条件的能力。",
      execution: "执行来源",
      boundary: "所有权边界",
      surfaces: "Console 页面",
      evidence: "运行时证据",
    },
    modules: {
      title: "界面",
      description: "查看 Console 界面、所属包以及它们的注册与导航健康状态。",
      registry: "导航注册",
      registered: "项已注册",
      moduleCount: "个模块",
      module: "模块",
      source: "来源",
      state: "状态",
      surfaces: "页面",
      surface: "页面",
      placement: "位置",
      registration: "注册状态",
      allSources: "全部来源",
      allAreas: "全部区域",
      allStates: "全部状态",
      registeredState: "已注册",
      manifest: "Manifest 声明",
      ownership: "包解析",
      identity: "解析后的身份",
      executionEvidence: "执行证据",
      protocol: "协议主版本",
      entry: "入口点",
      entries: "制品入口数",
      permissions: "已授予权限数",
      removalPreview: "移除预览",
      removalSurfaceImpact: "将移除的 Console 页面",
      removalAuthority: "这里只做预览；App Composition 仍是移除操作的权威。",
      navigation: "导航位置",
      evidence: "访问门禁",
      defaultFromArea: "按区域默认",
      group: "分组",
      capabilityGranted: "能力已授予",
      routeRegistered: "路由已注册",
      openSystem: "在系统中打开",
      noMatches: "没有符合当前筛选条件的注册项。",
      noCapabilities: "未声明能力门禁。",
      sourceLinked: "linked",
      sourceService: "service",
      sourceFirstParty: "first_party",
      sourceInstalled: "installed",
      sourceRuntimeBundle: "runtime_bundle",
      authority: "权责边界",
    },
    changes: {
      title: "变更",
      description: "审查有边界的计划，批准关键操作，并跟踪验证证据。",
      active: "活跃",
      awaitingYou: "等待你处理",
      tabs: ["活跃", "草稿", "已完成", "已恢复"],
      filterAttention: "需关注",
      filterVerified: "已验证",
      noRecords: "当前视图暂无变更记录。",
      priority: "优先级排序",
      filter: "筛选",
      intent: "意图",
      plan: "计划",
      blast: "影响范围",
      approval: "审批",
      verification: "验证契约",
      recovery: "恢复",
      approve: "批准并应用",
    },
    runtime: {
      title: "运行操作",
      description: "观察实时操作、发件箱投递以及每次状态迁移产生的证据。",
      tabs: ["操作", "发件箱", "事件"],
      healthy: "健康",
      observed: "已观察",
      services: "服务",
      modules: "模块",
      checks: "检查",
      service: "服务",
      region: "区域",
      version: "版本",
      state: "状态",
      timeline: "执行时间线",
      authority: "权责边界",
      serviceOwns: "Service 持有运行时状态并负责效果。",
      consoleObserves: "Console 负责观察、协调并保留证据。",
    },
    delivery: {
      title: "发布",
      description: "准备经审查的发布交接并验证部署，但不宣称生产发布权限。",
      candidates: "候选版本",
      open: "开放",
      authority: "生产权限：外部",
      readiness: "就绪门禁",
      artifacts: "制品",
      approvals: "审批",
      statusAge: "状态更新时间",
      handoff: "准备交接",
      handoffTitle: "权责交接",
      handoffDescription: "Console 打包经审查的计划、回执和验证契约。",
      authorityDescription: "独立的发布权威决定并执行生产发布。",
      gateRecorded: "已通过",
      gateNotRecorded: "待完成",
      planApproved: "已批准 · Leo + Mina",
      contracts: "契约已生成且干净",
      workspaceQuality: "工作区质量门禁",
      cargoInstall: "Cargo 全新安装",
      npmInstall: "npm 全新安装",
      publishedAcceptance: "已发布模式验收",
      reviewedPlan: "经审查的发布计划",
      readyForHandoff: "可交接",
      needsAttention: "需要关注",
      draft: "草稿",
      verified: "已验证",
      noRelease: "暂无发布状态。",
    },
    settings: {
      title: "设置",
      description: "个性化 Console，但不改变由服务持有的运行时状态。",
      appearance: "外观",
      theme: "主题",
      themeDescription: "选择主题，或跟随操作系统。",
      language: "语言",
      consoleLanguage: "Console 语言",
      languageDescription:
        "应用于宿主导航及使用 Console locale 接口的 extension。",
      locale: "区域设置",
      timeZone: "时区",
      timeZoneDescription: "用于显示时间戳，不改变来源证据。",
      followSystem: "跟随系统",
      dark: "深色",
      light: "浅色",
      unsaved: "有未保存更改",
      saved: "已保存",
      noChanges: "没有更改",
      console: "Console",
      command: "命令菜单",
      commandDescription: "在任何页面打开命令面板。",
      sidebar: "侧边栏",
      sidebarDescription: "折叠或展开工作区导航。",
    },
  },
} as const;

export function consoleProductCopy(locale: ConsoleLocale) {
  return product[locale];
}
