// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.management@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:2a5846adaa2ae2e9a847b5a64b044ec5f489a9b9afda513f52fa0a8c02b8fcac";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const MANAGEMENT_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const MANAGEMENT_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const MANAGEMENT_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const MANAGEMENT_CONTRACT: CapabilityReference<ManagementClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_management { () => { "{\"capability_id\":\"lenso.management@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"catalog\",\"invoke\",\"status\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_management_client {
    () => { "{\"capability_id\":\"lenso.management@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.management@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_management_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.management@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_management_client {
    () => { "{\"capability_id\":\"lenso.management@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.management@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const CATALOG_OPERATION: &str = "catalog";
pub const INVOKE_OPERATION: &str = "invoke";
pub const STATUS_OPERATION: &str = "status";

pub use lenso_contract_runtime::{RawJson, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Copy, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CatalogRequest {

}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CatalogResponse {
    #[serde(rename = "deployment")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub deployment: String,
    #[serde(rename = "entries")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub entries: Vec<Entry>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Entry {
    #[serde(rename = "capability")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub capability: String,
    #[serde(rename = "description")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub description: String,
    #[serde(rename = "effect")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub effect: Effect,
    #[serde(rename = "id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub id: String,
    #[serde(rename = "input_schema_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub input_schema_json: RawJson,
    #[serde(rename = "operation")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub operation: String,
    #[serde(rename = "requires_approval")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requires_approval: bool,
    #[serde(rename = "target_instance")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub target_instance: String,
    #[serde(rename = "version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub version: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum Effect {
    #[serde(rename = "read")]
    Read,
    #[serde(rename = "write")]
    Write,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CatalogError {
    PermissionDenied,
    Unavailable,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InvokeRequest {
    #[serde(rename = "entry_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub entry_id: String,
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: Option<String>,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: Option<String>,
    #[serde(rename = "input_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub input_json: RawJson,
    #[serde(rename = "version")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub version: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InvokeResponse {
    #[serde(rename = "operation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub operation_id: Option<String>,
    #[serde(rename = "receipt")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub receipt: Option<String>,
    #[serde(rename = "result_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub result_json: Option<String>,
    #[serde(rename = "state")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub state: InvocationState,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum InvocationState {
    #[serde(rename = "pending_approval")]
    PendingApproval,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "executing")]
    Executing,
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "cancelled")]
    Cancelled,
}

#[derive(Clone, Debug, PartialEq)]
pub enum InvokeError {
    Conflict,
    InvalidInput,
    NotFound,
    PermissionDenied,
    Unavailable,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct StatusRequest {
    #[serde(rename = "operation_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub operation_id: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum StatusError {
    Conflict,
    NotFound,
    PermissionDenied,
    Unavailable,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct ManagementCatalog;
impl RequestCapability for ManagementCatalog {
    type Request = CatalogRequest;
    type Response = CatalogResponse;
    type DomainError = CatalogError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CATALOG_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ManagementRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).catalog(context, request)
    }
}

#[derive(Debug)]
pub struct ManagementInvoke;
impl RequestCapability for ManagementInvoke {
    type Request = InvokeRequest;
    type Response = InvokeResponse;
    type DomainError = InvokeError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != INVOKE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ManagementRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).invoke(context, request)
    }
}

#[derive(Debug)]
pub struct ManagementStatus;
impl RequestCapability for ManagementStatus {
    type Request = StatusRequest;
    type Response = InvokeResponse;
    type DomainError = StatusError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != STATUS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ManagementRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).status(context, request)
    }
}

impl serde::Serialize for CatalogError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::Unavailable => serializer.serialize_str("unavailable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CatalogError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "permission_denied" => Ok(Self::PermissionDenied),
                "unavailable" => Ok(Self::Unavailable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for InvokeError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::InvalidInput => serializer.serialize_str("invalid_input"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::Unavailable => serializer.serialize_str("unavailable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for InvokeError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "invalid_input" => Ok(Self::InvalidInput),
                "not_found" => Ok(Self::NotFound),
                "permission_denied" => Ok(Self::PermissionDenied),
                "unavailable" => Ok(Self::Unavailable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for StatusError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Conflict => serializer.serialize_str("conflict"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::PermissionDenied => serializer.serialize_str("permission_denied"),
            Self::Unavailable => serializer.serialize_str("unavailable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for StatusError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "conflict" => Ok(Self::Conflict),
                "not_found" => Ok(Self::NotFound),
                "permission_denied" => Ok(Self::PermissionDenied),
                "unavailable" => Ok(Self::Unavailable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_catalog_request(value: &CatalogRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_catalog_request(wire: &str) -> Result<CatalogRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_catalog_response(value: &CatalogResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_catalog_response(wire: &str) -> Result<CatalogResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_catalog_error(value: &CatalogError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_catalog_error(wire: &str) -> Result<CatalogError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_invoke_request(value: &InvokeRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_invoke_request(wire: &str) -> Result<InvokeRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_invoke_response(value: &InvokeResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_invoke_response(wire: &str) -> Result<InvokeResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_invoke_error(value: &InvokeError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_invoke_error(wire: &str) -> Result<InvokeError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_status_request(value: &StatusRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_status_request(wire: &str) -> Result<StatusRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_status_response(value: &InvokeResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_status_response(wire: &str) -> Result<InvokeResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_status_error(value: &StatusError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_status_error(wire: &str) -> Result<StatusError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoManagementCatalogResult {
    fn __lenso_into_result(self) -> Result<Result<CatalogResponse, CatalogError>, RuntimeFailure>;
}
impl __LensoIntoManagementCatalogResult for Result<CatalogResponse, CatalogError> {
    fn __lenso_into_result(self) -> Result<Result<CatalogResponse, CatalogError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoManagementCatalogResult for Result<Result<CatalogResponse, CatalogError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CatalogResponse, CatalogError>, RuntimeFailure> { self }
}
impl __LensoIntoManagementCatalogResult for Result<CatalogResponse, lenso_plugin_authoring::PluginError<CatalogError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CatalogResponse, CatalogError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoManagementCatalogResult for Result<CatalogResponse, ManagementCatalogInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CatalogResponse, CatalogError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ManagementCatalogInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ManagementCatalogInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoManagementInvokeResult {
    fn __lenso_into_result(self) -> Result<Result<InvokeResponse, InvokeError>, RuntimeFailure>;
}
impl __LensoIntoManagementInvokeResult for Result<InvokeResponse, InvokeError> {
    fn __lenso_into_result(self) -> Result<Result<InvokeResponse, InvokeError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoManagementInvokeResult for Result<Result<InvokeResponse, InvokeError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<InvokeResponse, InvokeError>, RuntimeFailure> { self }
}
impl __LensoIntoManagementInvokeResult for Result<InvokeResponse, lenso_plugin_authoring::PluginError<InvokeError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<InvokeResponse, InvokeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoManagementInvokeResult for Result<InvokeResponse, ManagementInvokeInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<InvokeResponse, InvokeError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ManagementInvokeInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ManagementInvokeInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoManagementStatusResult {
    fn __lenso_into_result(self) -> Result<Result<InvokeResponse, StatusError>, RuntimeFailure>;
}
impl __LensoIntoManagementStatusResult for Result<InvokeResponse, StatusError> {
    fn __lenso_into_result(self) -> Result<Result<InvokeResponse, StatusError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoManagementStatusResult for Result<Result<InvokeResponse, StatusError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<InvokeResponse, StatusError>, RuntimeFailure> { self }
}
impl __LensoIntoManagementStatusResult for Result<InvokeResponse, lenso_plugin_authoring::PluginError<StatusError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<InvokeResponse, StatusError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoManagementStatusResult for Result<InvokeResponse, ManagementStatusInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<InvokeResponse, StatusError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ManagementStatusInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ManagementStatusInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait ManagementProvider: fmt::Debug + 'static {
    fn catalog(&self, context: InvocationContext, request: CatalogRequest) -> NativeRequestFuture<ManagementCatalog>;
    fn invoke(&self, context: InvocationContext, request: InvokeRequest) -> NativeRequestFuture<ManagementInvoke>;
    fn status(&self, context: InvocationContext, request: StatusRequest) -> NativeRequestFuture<ManagementStatus>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_management {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportManagement;
        impl $crate::ManagementProvider for $plugin {
        fn catalog(&self, context: __LensoNativeSupportManagement::InvocationContext, request: $crate::CatalogRequest) -> __LensoNativeSupportManagement::NativeRequestFuture<$crate::ManagementCatalog> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::catalog(&plugin, context, request).await;
                $crate::__LensoIntoManagementCatalogResult::__lenso_into_result(result)
            })
        }
        fn invoke(&self, context: __LensoNativeSupportManagement::InvocationContext, request: $crate::InvokeRequest) -> __LensoNativeSupportManagement::NativeRequestFuture<$crate::ManagementInvoke> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::invoke(&plugin, context, request).await;
                $crate::__LensoIntoManagementInvokeResult::__lenso_into_result(result)
            })
        }
        fn status(&self, context: __LensoNativeSupportManagement::InvocationContext, request: $crate::StatusRequest) -> __LensoNativeSupportManagement::NativeRequestFuture<$crate::ManagementStatus> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::status(&plugin, context, request).await;
                $crate::__LensoIntoManagementStatusResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_management {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportManagement;
        impl $crate::ManagementProvider for $object {
        fn catalog(&self, context: __LensoNativeSupportManagement::InvocationContext, request: $crate::CatalogRequest) -> __LensoNativeSupportManagement::NativeRequestFuture<$crate::ManagementCatalog> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::catalog(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoManagementCatalogResult::__lenso_into_result(result)
            })
        }
        fn invoke(&self, context: __LensoNativeSupportManagement::InvocationContext, request: $crate::InvokeRequest) -> __LensoNativeSupportManagement::NativeRequestFuture<$crate::ManagementInvoke> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::invoke(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoManagementInvokeResult::__lenso_into_result(result)
            })
        }
        fn status(&self, context: __LensoNativeSupportManagement::InvocationContext, request: $crate::StatusRequest) -> __LensoNativeSupportManagement::NativeRequestFuture<$crate::ManagementStatus> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::status(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoManagementStatusResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_management {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportManagement;
        impl $crate::ManagementProvider for $object {
        fn catalog(&self, context: __LensoNativeSupportManagement::InvocationContext, request: $crate::CatalogRequest) -> __LensoNativeSupportManagement::NativeRequestFuture<$crate::ManagementCatalog> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::ManagementProvider>::catalog(plugin.as_ref(), context, request).await
            })
        }
        fn invoke(&self, context: __LensoNativeSupportManagement::InvocationContext, request: $crate::InvokeRequest) -> __LensoNativeSupportManagement::NativeRequestFuture<$crate::ManagementInvoke> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::ManagementProvider>::invoke(plugin.as_ref(), context, request).await
            })
        }
        fn status(&self, context: __LensoNativeSupportManagement::InvocationContext, request: $crate::StatusRequest) -> __LensoNativeSupportManagement::NativeRequestFuture<$crate::ManagementStatus> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::ManagementProvider>::status(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct ManagementRequestEndpoint { provider: Rc<dyn ManagementProvider> }

#[derive(Debug)]
pub struct ManagementEndpoint<P: ManagementProvider> { provider: Rc<P>, request_endpoint: ManagementRequestEndpoint }
impl<P: ManagementProvider> ManagementEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn ManagementProvider> = provider.clone();
        Self { provider, request_endpoint: ManagementRequestEndpoint { provider: request_provider } }
    }
}

impl<P: ManagementProvider> NativeRequestEndpoint for ManagementEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CATALOG_OPERATION,
        INVOKE_OPERATION,
        STATUS_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CATALOG_OPERATION => {
                let Ok(request) = request.downcast::<CatalogRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).catalog(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            INVOKE_OPERATION => {
                let Ok(request) = request.downcast::<InvokeRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).invoke(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            STATUS_OPERATION => {
                let Ok(request) = request.downcast::<StatusRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).status(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_management {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::ManagementEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_management {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_management!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct ManagementClient {
    catalog: NativeRequestHandle<ManagementCatalog>,
    invoke: NativeRequestHandle<ManagementInvoke>,
    status: NativeRequestHandle<ManagementStatus>,
}
impl ManagementClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn catalog(&self, request: CatalogRequest) -> Result<CatalogResponse, ManagementCatalogInvocationError> {
        self.catalog.invoke(CATALOG_OPERATION, request).await
            .map_err(ManagementCatalogInvocationError::Runtime)?
            .map_err(ManagementCatalogInvocationError::Domain)
    }

    pub async fn catalog_with_context(&self, context: InvocationContext, request: CatalogRequest) -> Result<CatalogResponse, ManagementCatalogInvocationError> {
        self.catalog.invoke_with_context(CATALOG_OPERATION, context, request).await
            .map_err(ManagementCatalogInvocationError::Runtime)?
            .map_err(ManagementCatalogInvocationError::Domain)
    }

    pub async fn invoke(&self, request: InvokeRequest) -> Result<InvokeResponse, ManagementInvokeInvocationError> {
        self.invoke.invoke(INVOKE_OPERATION, request).await
            .map_err(ManagementInvokeInvocationError::Runtime)?
            .map_err(ManagementInvokeInvocationError::Domain)
    }

    pub async fn invoke_with_context(&self, context: InvocationContext, request: InvokeRequest) -> Result<InvokeResponse, ManagementInvokeInvocationError> {
        self.invoke.invoke_with_context(INVOKE_OPERATION, context, request).await
            .map_err(ManagementInvokeInvocationError::Runtime)?
            .map_err(ManagementInvokeInvocationError::Domain)
    }

    pub async fn status(&self, request: StatusRequest) -> Result<InvokeResponse, ManagementStatusInvocationError> {
        self.status.invoke(STATUS_OPERATION, request).await
            .map_err(ManagementStatusInvocationError::Runtime)?
            .map_err(ManagementStatusInvocationError::Domain)
    }

    pub async fn status_with_context(&self, context: InvocationContext, request: StatusRequest) -> Result<InvokeResponse, ManagementStatusInvocationError> {
        self.status.invoke_with_context(STATUS_OPERATION, context, request).await
            .map_err(ManagementStatusInvocationError::Runtime)?
            .map_err(ManagementStatusInvocationError::Domain)
    }
}

impl CapabilityClient for ManagementClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            catalog: dependencies.one::<ManagementCatalog>()?,
            invoke: dependencies.one::<ManagementInvoke>()?,
            status: dependencies.one::<ManagementStatus>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for ManagementClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    catalog: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ManagementCatalog>()?,
                    invoke: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ManagementInvoke>()?,
                    status: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<ManagementStatus>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ManagementCatalogInvocationError {
    Domain(CatalogError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ManagementInvokeInvocationError {
    Domain(InvokeError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum ManagementStatusInvocationError {
    Domain(StatusError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct ManagementGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> ManagementGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[CATALOG_OPERATION, INVOKE_OPERATION, STATUS_OPERATION], &[], &[])
            .map(|capability| Self { capability })
    }

    pub fn catalog(&self, request: &CatalogRequest) -> Result<CatalogResponse, lenso_guest_sdk::GuestError<CatalogError>> {
        self.capability.request(CATALOG_OPERATION, request)
    }

    pub fn invoke(&self, request: &InvokeRequest) -> Result<InvokeResponse, lenso_guest_sdk::GuestError<InvokeError>> {
        self.capability.request(INVOKE_OPERATION, request)
    }

    pub fn status(&self, request: &StatusRequest) -> Result<InvokeResponse, lenso_guest_sdk::GuestError<StatusError>> {
        self.capability.request(STATUS_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct ManagementJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for ManagementJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn descriptor_digest(&self) -> &'static str { DESCRIPTOR_DIGEST }

    fn request_operations(&self) -> &'static [&'static str] { &[CATALOG_OPERATION, INVOKE_OPERATION, STATUS_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[] }
    fn event_operations(&self) -> &'static [&'static str] { &[] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            CATALOG_OPERATION => {
                let value = request.downcast_ref::<CatalogRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            INVOKE_OPERATION => {
                let value = request.downcast_ref::<InvokeRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            STATUS_OPERATION => {
                let value = request.downcast_ref::<StatusRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            CATALOG_OPERATION => serde_json::from_value::<CatalogResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            INVOKE_OPERATION => serde_json::from_value::<InvokeResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            STATUS_OPERATION => serde_json::from_value::<InvokeResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            CATALOG_OPERATION => serde_json::from_value::<CatalogError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            INVOKE_OPERATION => serde_json::from_value::<InvokeError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            STATUS_OPERATION => serde_json::from_value::<StatusError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, _request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_stream_message(&self, operation: &str, _message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_message(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_domain_error(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_event(&self, operation: &str, _event: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::PluginDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            CATALOG_OPERATION => {
                let request = serde_json::from_value::<CatalogRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<ManagementCatalog>()?;
                    match handle.invoke_with_context(CATALOG_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            INVOKE_OPERATION => {
                let request = serde_json::from_value::<InvokeRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<ManagementInvoke>()?;
                    match handle.invoke_with_context(INVOKE_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            STATUS_OPERATION => {
                let request = serde_json::from_value::<StatusRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<ManagementStatus>()?;
                    match handle.invoke_with_context(STATUS_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, _dependency: lenso_kernel::PluginStreamDependencyHandle, operation: String, _request: serde_json::Value, _context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }

    fn publish_host_event(&self, _dependency: lenso_kernel::PluginEventDependencyHandle, operation: String, _event: serde_json::Value, _context: InvocationContext) -> futures::future::LocalBoxFuture<'static, Result<(), RuntimeFailure>> {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
