import * as stylex from "@stylexjs/stylex";

export const shellStyles = stylex.create({
  theme: {
    backgroundColor: "var(--color-surface-canvas)",
    color: "var(--color-content-primary)",
    fontFamily: "var(--font-sans)",
    minHeight: "100dvh",
  },
  shell: {
    backgroundColor: "var(--color-surface-canvas)",
    display: "grid",
    gridTemplateColumns: {
      default: "218px minmax(0, 1fr)",
      "@media (max-width: 720px)": "minmax(0, 1fr)",
    },
    gridTemplateRows: {
      default: "54px minmax(0, 1fr)",
      "@media (max-width: 720px)": "90px minmax(0, 1fr)",
    },
    height: "100dvh",
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  navigationRegion: {
    gridColumn: "1",
    gridRow: "2",
    minHeight: 0,
    minWidth: 0,
    inset: { default: null, "@media (max-width: 720px)": 0 },
    pointerEvents: { default: "auto", "@media (max-width: 720px)": "none" },
    position: { default: "relative", "@media (max-width: 720px)": "absolute" },
    zIndex: { default: null, "@media (max-width: 720px)": 20 },
  },
  navigationRegionOpen: {
    pointerEvents: { default: null, "@media (max-width: 720px)": "auto" },
  },
  header: {
    alignItems: {
      default: "center",
      "@media (max-width: 720px)": "flex-start",
    },
    backgroundColor: "var(--color-surface-canvas)",
    borderBottomColor: "var(--color-border-tertiary)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    gap: "4px",
    gridColumn: "1 / -1",
    gridRow: "1",
    minWidth: 0,
    paddingInline: { default: "16px", "@media (max-width: 720px)": "8px" },
    position: "relative",
    zIndex: 30,
  },
  mobileNavTrigger: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--color-surface-interactive-hover)",
    },
    borderRadius: "var(--radius-navigation)",
    borderWidth: 0,
    color: "var(--color-content-secondary)",
    cursor: "pointer",
    display: { default: "none", "@media (max-width: 720px)": "flex" },
    flex: "0 0 32px",
    height: "32px",
    justifyContent: "center",
    marginBlockStart: "7px",
    padding: 0,
  },
  workspaceAnchor: {
    flex: "none",
    minWidth: 0,
    position: "relative",
    marginBlockStart: { default: 0, "@media (max-width: 720px)": "7px" },
  },
  workspaceTrigger: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--color-surface-interactive-hover)",
    },
    borderRadius: "var(--radius-navigation)",
    borderWidth: 0,
    color: "var(--color-content-primary)",
    cursor: "pointer",
    display: "flex",
    gap: "6px",
    height: "32px",
    maxWidth: "min(240px, 38vw)",
    paddingInline: "7px 3px",
  },
  mark: {
    alignItems: "center",
    color: "var(--color-content-primary)",
    display: "flex",
    flex: "0 0 20px",
    fontSize: "20px",
    height: "20px",
    justifyContent: "center",
    lineHeight: 1,
  },
  workspaceName: {
    display: { default: "none", "@media (max-width: 720px)": "inline" },
    fontSize: "12px",
    fontWeight: 600,
    maxWidth: "100px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  workspaceMenu: {
    backgroundColor: "var(--color-surface-popover)",
    borderRadius: "10px",
    boxShadow:
      "0 var(--elevation-overlay-key-y) var(--elevation-overlay-key-blur) var(--elevation-overlay-key), 0 var(--elevation-overlay-ambient-y) var(--elevation-overlay-ambient-blur) var(--elevation-overlay-ambient)",
    insetBlockStart: "38px",
    insetInlineStart: 0,
    maxHeight: "min(70dvh, 420px)",
    overflowY: "auto",
    padding: "6px",
    position: "absolute",
    width: "min(260px, calc(100vw - 24px))",
    zIndex: 40,
  },
  menuCaption: {
    color: "var(--color-content-tertiary)",
    display: "block",
    fontSize: "11px",
    padding: "6px 9px 7px",
  },
  workspaceOption: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--color-menu-item-hover)",
      '[aria-current="page"]': "var(--color-menu-item-selected)",
    },
    borderRadius: "7px",
    borderWidth: 0,
    color: "var(--color-content-primary)",
    cursor: "pointer",
    display: "flex",
    gap: "10px",
    minHeight: "40px",
    padding: "7px 9px",
    textAlign: "start",
    width: "100%",
  },
  assistant: { display: "flex", flex: "none", minWidth: 0 },
  divider: {
    backgroundColor: "var(--color-border-tertiary)",
    flex: "0 0 1px",
    height: "22px",
    marginInline: "5px",
    display: { default: "block", "@media (max-width: 720px)": "none" },
  },
  tabs: {
    alignItems: "center",
    display: "flex",
    gap: "2px",
    minWidth: 0,
    overflowX: "auto",
    scrollbarWidth: "none",
    borderTopColor: "var(--color-border-tertiary)",
    borderTopStyle: { default: "none", "@media (max-width: 720px)": "solid" },
    borderTopWidth: "1px",
    height: { default: "auto", "@media (max-width: 720px)": "44px" },
    insetBlockStart: { default: null, "@media (max-width: 720px)": "46px" },
    insetInline: { default: null, "@media (max-width: 720px)": 0 },
    paddingInline: { default: 0, "@media (max-width: 720px)": "10px" },
    position: { default: "relative", "@media (max-width: 720px)": "absolute" },
  },
  tab: {
    alignItems: "center",
    backgroundColor: {
      default: "var(--color-navigation-tab-bg)",
      ":hover": "var(--color-navigation-tab-bg-hover)",
      '[aria-current="page"]': "var(--color-navigation-tab-bg-selected)",
    },
    borderRadius: "var(--radius-navigation)",
    borderWidth: 0,
    color: {
      default: "var(--color-navigation-tab-fg)",
      ":hover": "var(--color-navigation-tab-fg-hover)",
      '[aria-current="page"]': "var(--color-navigation-tab-fg-selected)",
    },
    cursor: "pointer",
    display: "flex",
    flex: "none",
    fontSize: "13.5px",
    height: "32px",
    paddingInline: "10px",
    whiteSpace: "nowrap",
    "@media (max-width: 720px)": {
      fontSize: "12px",
      height: "30px",
      paddingInline: "9px",
    },
  },
  currentTab: { cursor: "default" },
  contextSidebarRoot: {
    "--size-sidebar": "218px",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    pointerEvents: { default: "auto", "@media (max-width: 720px)": "none" },
    transform: {
      default: "none",
      "@media (max-width: 720px)": "translateX(-100%)",
    },
    visibility: { default: "visible", "@media (max-width: 720px)": "hidden" },
    width: {
      default: "218px",
      "@media (max-width: 720px)": "min(250px, 82vw)",
    },
  },
  contextSidebarRootOpen: {
    pointerEvents: { default: null, "@media (max-width: 720px)": "auto" },
    transform: { default: null, "@media (max-width: 720px)": "translateX(0)" },
    visibility: { default: null, "@media (max-width: 720px)": "visible" },
  },
  contextSidebarPanel: {
    backgroundColor: "var(--color-surface-sidebar)",
    borderInlineEndColor: "var(--color-border-tertiary)",
    borderInlineEndStyle: "solid",
    borderInlineEndWidth: "1px",
    height: "100%",
    paddingBlock: "12px 18px",
    width: "100%",
  },
  main: {
    backgroundColor: "var(--color-surface-canvas)",
    gridColumn: { default: "2", "@media (max-width: 720px)": "1" },
    gridRow: "2",
    minHeight: 0,
    minWidth: 0,
    overflow: "auto",
  },
  mobileBackdrop: {
    backgroundColor: "var(--color-surface-scrim)",
    borderWidth: 0,
    display: { default: "none", "@media (max-width: 720px)": "block" },
    gridColumn: "1",
    gridRow: "2",
    inset: 0,
    padding: 0,
    position: "absolute",
    width: "100%",
    zIndex: 10,
  },
  mobileOnly: {
    display: { default: "none", "@media (max-width: 720px)": "flex" },
  },
  settingsSearchEmpty: {
    color: "var(--color-content-tertiary)",
    fontSize: "12px",
    lineHeight: "18px",
    margin: "12px 8px",
  },
});
