import * as stylex from "@stylexjs/stylex";

export const shellStyles = stylex.create({
  theme: {
    "--page-layout-rail-surface": "var(--color-surface-level3)",
    backgroundColor: "var(--color-surface-sidebar)",
    color: "var(--color-content-primary)",
    fontFamily: "var(--font-sans)",
    minHeight: "100dvh",
  },
  shell: {
    backgroundColor: "var(--color-surface-sidebar)",
    display: "grid",
    gridTemplateColumns: {
      default: "244px minmax(0, 1fr)",
      "@media (max-width: 760px)": "48px minmax(0, 1fr)",
    },
    gridTemplateRows: "minmax(0, 1fr) 36px",
    height: "100dvh",
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  navigationRegion: {
    display: "flex",
    gridColumn: "1",
    gridRow: "1 / -1",
    height: "100dvh",
    minHeight: 0,
    minWidth: 0,
    width: {
      default: "244px",
      "@media (max-width: 760px)": "48px",
    },
  },
  primaryRailRoot: {
    "--size-sidebar": "48px",
    flex: "0 0 48px",
    height: "100dvh",
    minHeight: 0,
    width: "48px",
  },
  primaryRail: {
    alignItems: "center",
    backgroundColor: "var(--page-layout-rail-surface)",
    borderInlineEndColor: "var(--color-border-translucent)",
    borderInlineEndStyle: "solid",
    borderInlineEndWidth: "0.5px",
    display: "flex",
    flex: 1,
    flexDirection: "column",
    height: "100dvh",
    paddingBlock: "14px 12px",
    width: "48px",
  },
  railWorkspace: {
    alignItems: "center",
    backgroundColor: "var(--color-action-primary)",
    borderColor: "var(--color-border-translucent)",
    borderRadius: "9px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    color: "var(--color-action-primary-content)",
    cursor: "pointer",
    display: "flex",
    fontFamily: "var(--font-sans)",
    fontSize: "11px",
    fontWeight: 600,
    height: "28px",
    justifyContent: "center",
    lineHeight: "16px",
    padding: 0,
    width: "28px",
  },
  railAreas: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    marginBlockStart: "22px",
  },
  railButton: {
    borderRadius: "var(--radius-rounded)",
    color: "var(--color-content-tertiary)",
  },
  activeRailButton: {
    backgroundColor: {
      default: "var(--color-surface-selected)",
      ":hover": "var(--color-sidebar-item-hover)",
    },
    color: "var(--color-content-primary)",
  },
  railFooter: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    marginBlockStart: "auto",
  },
  railProfile: {
    alignItems: "center",
    backgroundColor: "var(--color-surface-interactive)",
    borderColor: "var(--color-border-secondary)",
    borderRadius: "50%",
    borderStyle: "solid",
    borderWidth: "0.5px",
    color: "var(--color-content-secondary)",
    cursor: "pointer",
    display: "flex",
    fontFamily: "var(--font-sans)",
    fontSize: "8px",
    fontWeight: 600,
    height: "26px",
    justifyContent: "center",
    padding: 0,
    width: "26px",
  },
  contextSidebarRoot: {
    "--size-sidebar": "196px",
    height: "100dvh",
    insetBlock: { default: null, "@media (max-width: 760px)": 0 },
    insetInlineStart: {
      default: null,
      "@media (max-width: 760px)": "48px",
    },
    minHeight: 0,
    minWidth: 0,
    overflow: { default: null, "@media (max-width: 760px)": "hidden" },
    pointerEvents: {
      default: null,
      "@media (max-width: 760px)": "none",
    },
    position: {
      default: "relative",
      "@media (max-width: 760px)": "absolute",
    },
    width: "196px",
    zIndex: { default: null, "@media (max-width: 760px)": 20 },
  },
  contextSidebarRootOpen: {
    pointerEvents: {
      default: null,
      "@media (max-width: 760px)": "auto",
    },
  },
  contextSidebarPanel: {
    borderInlineEndColor: {
      default: null,
      "@media (max-width: 760px)": "var(--color-border-translucent)",
    },
    borderInlineEndStyle: {
      default: null,
      "@media (max-width: 760px)": "solid",
    },
    borderInlineEndWidth: {
      default: null,
      "@media (max-width: 760px)": "0.5px",
    },
    display: "flex",
    height: "100%",
    opacity: {
      default: 1,
      "@media (max-width: 760px) and (prefers-reduced-motion: reduce)": 0,
    },
    pointerEvents: {
      default: null,
      "@media (max-width: 760px)": "none",
    },
    transform: {
      default: null,
      "@media (max-width: 760px)": "translateX(-100%)",
      "@media (max-width: 760px) and (prefers-reduced-motion: reduce)": "none",
    },
    transitionDuration: {
      default: null,
      "@media (max-width: 760px)": "200ms",
      "@media (max-width: 760px) and (prefers-reduced-motion: reduce)": "120ms",
    },
    transitionProperty: {
      default: null,
      "@media (max-width: 760px)": "opacity, transform",
    },
    transitionTimingFunction: {
      default: null,
      "@media (max-width: 760px)": "cubic-bezier(0.32, 0.72, 0, 1)",
    },
    width: "196px",
    willChange: {
      default: null,
      "@media (max-width: 760px)": "transform",
    },
  },
  contextSidebarPanelOpen: {
    opacity: {
      default: null,
      "@media (max-width: 760px) and (prefers-reduced-motion: reduce)": 1,
    },
    pointerEvents: {
      default: null,
      "@media (max-width: 760px)": "auto",
    },
    transform: {
      default: null,
      "@media (max-width: 760px)": "translateX(0)",
    },
  },
  desktopWorkspace: {
    display: { default: "flex", "@media (max-width: 760px)": "none" },
  },
  main: {
    backgroundColor: "var(--color-surface-canvas)",
    borderColor: "var(--color-border-tertiary)",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    gridColumn: "2",
    gridRow: "1",
    marginBlockStart: "8px",
    marginInlineEnd: "8px",
    minHeight: 0,
    minWidth: 0,
    overflow: "auto",
  },
  mobileBackdrop: {
    backgroundColor: "var(--color-surface-scrim)",
    borderWidth: 0,
    display: { default: "none", "@media (max-width: 760px)": "block" },
    insetBlock: 0,
    insetInline: "48px 0",
    padding: 0,
    position: "absolute",
    zIndex: 10,
  },
  mobileOnly: {
    display: { default: "none", "@media (max-width: 760px)": "flex" },
  },
  settingsSearchEmpty: {
    color: "var(--color-content-tertiary)",
    fontSize: "12px",
    lineHeight: "18px",
    margin: "12px 8px",
  },
  utilities: {
    alignItems: "center",
    display: "flex",
    gap: "2px",
    gridColumn: "2",
    gridRow: "2",
    justifyContent: "flex-end",
    paddingBlock: "4px",
    paddingInline: "10px",
  },
});
