import * as stylex from "@stylexjs/stylex";

export const shellStyles = stylex.create({
  content: {
    boxSizing: "border-box",
    minWidth: 0,
    overflowWrap: "anywhere",
    minHeight: "100dvh",
    paddingTop: 72,
    paddingBottom: 112,
    paddingInline: 24,
  },
  sidebarContent: {
    paddingLeft: { default: 256, "@media (max-width: 640px)": 24 },
  },
  clearLeftDock: { paddingLeft: 80 },
  clearRightDock: { paddingRight: 80 },
  clearLeftTabs: { paddingLeft: 248 },
  clearRightTabs: { paddingRight: 248 },
  clearTopTabs: { paddingTop: 136 },
  clearBottomTabs: { paddingBottom: 160 },
  tabs: {
    position: "fixed",
    display: "flex",
    gap: 12,
    maxWidth: "calc(100vw - 48px)",
    overflowX: "auto",
    pointerEvents: "auto",
  },
  inlineTabs: {
    position: "relative",
    flexWrap: "wrap",
    marginBottom: 16,
    maxWidth: "100%",
  },
  tabsTop: { top: 72, left: "50%", transform: "translateX(-50%)" },
  tabsBottom: { bottom: 72, left: "50%", transform: "translateX(-50%)" },
  tabsRight: {
    right: 72,
    width: 160,
    maxHeight: "calc(100dvh - 192px)",
    overflowY: "auto",
    top: "50%",
    transform: "translateY(-50%)",
    flexDirection: "column",
  },
  tabsLeft: {
    left: 72,
    width: 160,
    maxHeight: "calc(100dvh - 192px)",
    overflowY: "auto",
    top: "50%",
    transform: "translateY(-50%)",
    flexDirection: "column",
  },
  link: {
    display: "inline-flex",
    alignItems: "center",
    minHeight: { default: 36, "@media (pointer: coarse)": 44 },
    boxSizing: "border-box",
    color: "var(--foreground)",
    borderRadius: 8,
    paddingBlock: 8,
    paddingInline: 12,
    textDecoration: "none",
    ":focus-visible": {
      outlineWidth: 2,
      outlineStyle: "solid",
      outlineColor: "var(--focus)",
      outlineOffset: 2,
    },
  },
  activeLink: { backgroundColor: "var(--default)", fontWeight: 600 },
  sidebar: {
    position: "fixed",
    left: 16,
    top: 72,
    bottom: 24,
    width: 216,
    overflowY: "auto",
    backgroundColor: "var(--background)",
    pointerEvents: "auto",
    "@media (max-width: 640px)": { display: "none" },
  },
  list: {
    listStyleType: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  row: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: 8 },
  location: { fontSize: 13, overflowWrap: "anywhere", minWidth: 0 },
  directory: {
    boxSizing: "border-box",
    maxHeight: "65dvh",
    overflowY: "auto",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: 16,
    padding: 20,
  },
  controls: {
    display: "flex",
    flexWrap: "wrap",
    gap: 12,
    alignItems: "center",
  },
  search: {
    width: "100%",
    padding: 8,
    color: "var(--foreground)",
    backgroundColor: "var(--background)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 8,
  },
  tray: (position: "bottom" | "top" | "left" | "right") => ({
    position: "fixed",
    top: position === "top" ? 80 : position === "bottom" ? "auto" : "50%",
    bottom: position === "bottom" ? 80 : "auto",
    left: position === "left" ? 80 : position === "right" ? "auto" : "50%",
    right: position === "right" ? 80 : "auto",
    transform:
      position === "left" || position === "right"
        ? "translateY(-50%)"
        : "translateX(-50%)",
    width: "min(600px, calc(100vw - 120px))",
    maxWidth: "calc(100vw - 32px)",
  }),
  narrowTray: {
    "@media (max-width: 640px)": {
      top: "auto",
      bottom: 80,
      left: 16,
      right: 16,
      width: "auto",
      transform: "none",
    },
  },
});
