/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ChangesRouteImport } from './routes/changes'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as RuntimeRouteImport } from './routes/runtime'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SettingsAppearanceRouteImport } from './routes/settings_.appearance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesRoute = ChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeRoute = RuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/settings_/appearance',
  path: '/settings/appearance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/changes': typeof ChangesRoute
  '/delivery': typeof DeliveryRoute
  '/modules': typeof ModulesRoute
  '/runtime': typeof RuntimeRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/changes': typeof ChangesRoute
  '/delivery': typeof DeliveryRoute
  '/modules': typeof ModulesRoute
  '/runtime': typeof RuntimeRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/changes': typeof ChangesRoute
  '/delivery': typeof DeliveryRoute
  '/modules': typeof ModulesRoute
  '/runtime': typeof RuntimeRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/settings_/appearance': typeof SettingsAppearanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/changes'
    | '/delivery'
    | '/modules'
    | '/runtime'
    | '/settings'
    | '/system'
    | '/settings/appearance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/changes'
    | '/delivery'
    | '/modules'
    | '/runtime'
    | '/settings'
    | '/system'
    | '/settings/appearance'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/changes'
    | '/delivery'
    | '/modules'
    | '/runtime'
    | '/settings'
    | '/system'
    | '/settings_/appearance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ChangesRoute: typeof ChangesRoute
  DeliveryRoute: typeof DeliveryRoute
  ModulesRoute: typeof ModulesRoute
  RuntimeRoute: typeof RuntimeRoute
  SettingsRoute: typeof SettingsRoute
  SystemRoute: typeof SystemRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes': {
      id: '/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime': {
      id: '/runtime'
      path: '/runtime'
      fullPath: '/runtime'
      preLoaderRoute: typeof RuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/appearance': {
      id: '/settings_/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ChangesRoute: ChangesRoute,
  DeliveryRoute: DeliveryRoute,
  ModulesRoute: ModulesRoute,
  RuntimeRoute: RuntimeRoute,
  SettingsRoute: SettingsRoute,
  SystemRoute: SystemRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
