/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AgentChatIdRouteImport } from './routes/agent.$chatId'
import { Route as SettingsAgentRouteImport } from './routes/settings_.agent'
import { Route as ApiConsoleV1AgentSplatRouteImport } from './routes/api.console.v1.agent.$'
import { Route as ApiConsoleV1AgentControlToolPolicyRouteImport } from './routes/api.console.v1.agent.control.tool-policy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentChatIdRoute = AgentChatIdRouteImport.update({
  id: '/agent/$chatId',
  path: '/agent/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAgentRoute = SettingsAgentRouteImport.update({
  id: '/settings_/agent',
  path: '/settings/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsoleV1AgentSplatRoute = ApiConsoleV1AgentSplatRouteImport.update({
  id: '/api/console/v1/agent/$',
  path: '/api/console/v1/agent/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsoleV1AgentControlToolPolicyRoute =
  ApiConsoleV1AgentControlToolPolicyRouteImport.update({
    id: '/api/console/v1/agent/control/tool-policy',
    path: '/api/console/v1/agent/control/tool-policy',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/agent/$chatId': typeof AgentChatIdRoute
  '/settings/agent': typeof SettingsAgentRoute
  '/api/console/v1/agent/$': typeof ApiConsoleV1AgentSplatRoute
  '/api/console/v1/agent/control/tool-policy': typeof ApiConsoleV1AgentControlToolPolicyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/agent/$chatId': typeof AgentChatIdRoute
  '/settings/agent': typeof SettingsAgentRoute
  '/api/console/v1/agent/$': typeof ApiConsoleV1AgentSplatRoute
  '/api/console/v1/agent/control/tool-policy': typeof ApiConsoleV1AgentControlToolPolicyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/agent/$chatId': typeof AgentChatIdRoute
  '/settings_/agent': typeof SettingsAgentRoute
  '/api/console/v1/agent/$': typeof ApiConsoleV1AgentSplatRoute
  '/api/console/v1/agent/control/tool-policy': typeof ApiConsoleV1AgentControlToolPolicyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/agent/$chatId'
    | '/settings/agent'
    | '/api/console/v1/agent/$'
    | '/api/console/v1/agent/control/tool-policy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/agent/$chatId'
    | '/settings/agent'
    | '/api/console/v1/agent/$'
    | '/api/console/v1/agent/control/tool-policy'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/agent/$chatId'
    | '/settings_/agent'
    | '/api/console/v1/agent/$'
    | '/api/console/v1/agent/control/tool-policy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  AgentChatIdRoute: typeof AgentChatIdRoute
  SettingsAgentRoute: typeof SettingsAgentRoute
  ApiConsoleV1AgentSplatRoute: typeof ApiConsoleV1AgentSplatRoute
  ApiConsoleV1AgentControlToolPolicyRoute: typeof ApiConsoleV1AgentControlToolPolicyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$chatId': {
      id: '/agent/$chatId'
      path: '/agent/$chatId'
      fullPath: '/agent/$chatId'
      preLoaderRoute: typeof AgentChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/agent': {
      id: '/settings_/agent'
      path: '/settings/agent'
      fullPath: '/settings/agent'
      preLoaderRoute: typeof SettingsAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/console/v1/agent/$': {
      id: '/api/console/v1/agent/$'
      path: '/api/console/v1/agent/$'
      fullPath: '/api/console/v1/agent/$'
      preLoaderRoute: typeof ApiConsoleV1AgentSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/console/v1/agent/control/tool-policy': {
      id: '/api/console/v1/agent/control/tool-policy'
      path: '/api/console/v1/agent/control/tool-policy'
      fullPath: '/api/console/v1/agent/control/tool-policy'
      preLoaderRoute: typeof ApiConsoleV1AgentControlToolPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  AgentChatIdRoute: AgentChatIdRoute,
  SettingsAgentRoute: SettingsAgentRoute,
  ApiConsoleV1AgentSplatRoute: ApiConsoleV1AgentSplatRoute,
  ApiConsoleV1AgentControlToolPolicyRoute:
    ApiConsoleV1AgentControlToolPolicyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
