/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AgentChatIdRouteImport } from './routes/agent.$chatId'
import { Route as SettingsAgentRouteImport } from './routes/settings_.agent'
import { Route as SettingsAiRouteImport } from './routes/settings_.ai'
import { Route as SettingsAppearanceRouteImport } from './routes/settings_.appearance'
import { Route as AgentAgentIdChatIdRouteImport } from './routes/agent.$agentId.$chatId'
import { Route as SettingsAiAgentRouteImport } from './routes/settings_.ai_.agent'
import { Route as PluginsAgentIdPackageIdInstanceKeyRouteImport } from './routes/plugins_.$agentId.$packageId.$instanceKey'
import { Route as SettingsAgentSkillsNewRouteImport } from './routes/settings_.agent_.skills.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentChatIdRoute = AgentChatIdRouteImport.update({
  id: '/agent/$chatId',
  path: '/agent/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAgentRoute = SettingsAgentRouteImport.update({
  id: '/settings_/agent',
  path: '/settings/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAiRoute = SettingsAiRouteImport.update({
  id: '/settings_/ai',
  path: '/settings/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/settings_/appearance',
  path: '/settings/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAgentIdChatIdRoute = AgentAgentIdChatIdRouteImport.update({
  id: '/agent/$agentId/$chatId',
  path: '/agent/$agentId/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAiAgentRoute = SettingsAiAgentRouteImport.update({
  id: '/settings_/ai_/agent',
  path: '/settings/ai/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsAgentIdPackageIdInstanceKeyRoute =
  PluginsAgentIdPackageIdInstanceKeyRouteImport.update({
    id: '/plugins_/$agentId/$packageId/$instanceKey',
    path: '/plugins/$agentId/$packageId/$instanceKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsAgentSkillsNewRoute = SettingsAgentSkillsNewRouteImport.update({
  id: '/settings_/agent_/skills/new',
  path: '/settings/agent/skills/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/plugins': typeof PluginsRoute
  '/settings': typeof SettingsRoute
  '/agent/$chatId': typeof AgentChatIdRoute
  '/settings/agent': typeof SettingsAgentRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/agent/$agentId/$chatId': typeof AgentAgentIdChatIdRoute
  '/settings/ai/agent': typeof SettingsAiAgentRoute
  '/plugins/$agentId/$packageId/$instanceKey': typeof PluginsAgentIdPackageIdInstanceKeyRoute
  '/settings/agent/skills/new': typeof SettingsAgentSkillsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/plugins': typeof PluginsRoute
  '/settings': typeof SettingsRoute
  '/agent/$chatId': typeof AgentChatIdRoute
  '/settings/agent': typeof SettingsAgentRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/agent/$agentId/$chatId': typeof AgentAgentIdChatIdRoute
  '/settings/ai/agent': typeof SettingsAiAgentRoute
  '/plugins/$agentId/$packageId/$instanceKey': typeof PluginsAgentIdPackageIdInstanceKeyRoute
  '/settings/agent/skills/new': typeof SettingsAgentSkillsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/plugins': typeof PluginsRoute
  '/settings': typeof SettingsRoute
  '/agent/$chatId': typeof AgentChatIdRoute
  '/settings_/agent': typeof SettingsAgentRoute
  '/settings_/ai': typeof SettingsAiRoute
  '/settings_/appearance': typeof SettingsAppearanceRoute
  '/agent/$agentId/$chatId': typeof AgentAgentIdChatIdRoute
  '/settings_/ai_/agent': typeof SettingsAiAgentRoute
  '/plugins_/$agentId/$packageId/$instanceKey': typeof PluginsAgentIdPackageIdInstanceKeyRoute
  '/settings_/agent_/skills/new': typeof SettingsAgentSkillsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/plugins'
    | '/settings'
    | '/agent/$chatId'
    | '/settings/agent'
    | '/settings/ai'
    | '/settings/appearance'
    | '/agent/$agentId/$chatId'
    | '/settings/ai/agent'
    | '/plugins/$agentId/$packageId/$instanceKey'
    | '/settings/agent/skills/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/plugins'
    | '/settings'
    | '/agent/$chatId'
    | '/settings/agent'
    | '/settings/ai'
    | '/settings/appearance'
    | '/agent/$agentId/$chatId'
    | '/settings/ai/agent'
    | '/plugins/$agentId/$packageId/$instanceKey'
    | '/settings/agent/skills/new'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/plugins'
    | '/settings'
    | '/agent/$chatId'
    | '/settings_/agent'
    | '/settings_/ai'
    | '/settings_/appearance'
    | '/agent/$agentId/$chatId'
    | '/settings_/ai_/agent'
    | '/plugins_/$agentId/$packageId/$instanceKey'
    | '/settings_/agent_/skills/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  PluginsRoute: typeof PluginsRoute
  SettingsRoute: typeof SettingsRoute
  AgentChatIdRoute: typeof AgentChatIdRoute
  SettingsAgentRoute: typeof SettingsAgentRoute
  SettingsAiRoute: typeof SettingsAiRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  AgentAgentIdChatIdRoute: typeof AgentAgentIdChatIdRoute
  SettingsAiAgentRoute: typeof SettingsAiAgentRoute
  PluginsAgentIdPackageIdInstanceKeyRoute: typeof PluginsAgentIdPackageIdInstanceKeyRoute
  SettingsAgentSkillsNewRoute: typeof SettingsAgentSkillsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$chatId': {
      id: '/agent/$chatId'
      path: '/agent/$chatId'
      fullPath: '/agent/$chatId'
      preLoaderRoute: typeof AgentChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/agent': {
      id: '/settings_/agent'
      path: '/settings/agent'
      fullPath: '/settings/agent'
      preLoaderRoute: typeof SettingsAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/ai': {
      id: '/settings_/ai'
      path: '/settings/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof SettingsAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/appearance': {
      id: '/settings_/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$agentId/$chatId': {
      id: '/agent/$agentId/$chatId'
      path: '/agent/$agentId/$chatId'
      fullPath: '/agent/$agentId/$chatId'
      preLoaderRoute: typeof AgentAgentIdChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/ai_/agent': {
      id: '/settings_/ai_/agent'
      path: '/settings/ai/agent'
      fullPath: '/settings/ai/agent'
      preLoaderRoute: typeof SettingsAiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins_/$agentId/$packageId/$instanceKey': {
      id: '/plugins_/$agentId/$packageId/$instanceKey'
      path: '/plugins/$agentId/$packageId/$instanceKey'
      fullPath: '/plugins/$agentId/$packageId/$instanceKey'
      preLoaderRoute: typeof PluginsAgentIdPackageIdInstanceKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/agent_/skills/new': {
      id: '/settings_/agent_/skills/new'
      path: '/settings/agent/skills/new'
      fullPath: '/settings/agent/skills/new'
      preLoaderRoute: typeof SettingsAgentSkillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  PluginsRoute: PluginsRoute,
  SettingsRoute: SettingsRoute,
  AgentChatIdRoute: AgentChatIdRoute,
  SettingsAgentRoute: SettingsAgentRoute,
  SettingsAiRoute: SettingsAiRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  AgentAgentIdChatIdRoute: AgentAgentIdChatIdRoute,
  SettingsAiAgentRoute: SettingsAiAgentRoute,
  PluginsAgentIdPackageIdInstanceKeyRoute:
    PluginsAgentIdPackageIdInstanceKeyRoute,
  SettingsAgentSkillsNewRoute: SettingsAgentSkillsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
