// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, NativeStream, NativeStreamEndpoint, NativeStreamHandle, NativeStreamSession, PluginDependencies, RequestCapability, RuntimeFailure, StreamCapability, StreamEvent};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.observability.query@1";
pub const DESCRIPTOR_VERSION: &str = "1.1.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:41c36452d7dd29fc88c13f4f62eb9250c267963d1bb49fa0f9b9e31b90fed630";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const QUERY_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const QUERY_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const QUERY_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const QUERY_CONTRACT: CapabilityReference<QueryClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_query { () => { "{\"capability_id\":\"lenso.observability.query@1\",\"descriptor_version\":\"1.1.0\",\"operations\":[\"list_requests\",\"list_trace_logs\",\"read_ingestion_health\",\"read_trace\",\"watch_requests\"],\"operation_kinds\":{\"watch_requests\":\"stream\"},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_query_client {
    () => { "{\"capability_id\":\"lenso.observability.query@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.observability.query@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_query_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.observability.query@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_query_client {
    () => { "{\"capability_id\":\"lenso.observability.query@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.observability.query@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"many\"}") };
}

pub const LIST_REQUESTS_OPERATION: &str = "list_requests";
pub const LIST_TRACE_LOGS_OPERATION: &str = "list_trace_logs";
pub const READ_INGESTION_HEALTH_OPERATION: &str = "read_ingestion_health";
pub const READ_TRACE_OPERATION: &str = "read_trace";
pub const WATCH_REQUESTS_OPERATION: &str = "watch_requests";

pub use lenso_contract_runtime::{OptionalValue, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListRequestsRequest {
    #[serde(rename = "cursor")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub cursor: OptionalValue<String>,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "source_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListRequestsResponse {
    #[serde(rename = "next_cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_cursor: Option<String>,
    #[serde(rename = "receiver_epoch")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub receiver_epoch: String,
    #[serde(rename = "requests")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub requests: Vec<Request>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Request {
    #[serde(rename = "completeness")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completeness: RequestCompleteness,
    #[serde(rename = "duration_nano")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub duration_nano: String,
    #[serde(rename = "has_error")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub has_error: bool,
    #[serde(rename = "method")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub method: String,
    #[serde(rename = "route")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub route: String,
    #[serde(rename = "service_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub service_name: String,
    #[serde(rename = "started_at_unix_nano")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub started_at_unix_nano: String,
    #[serde(rename = "status_code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status_code: i64,
    #[serde(rename = "trace_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub trace_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum RequestCompleteness {
    #[serde(rename = "complete")]
    Complete,
    #[serde(rename = "partial")]
    Partial,
    #[serde(rename = "late")]
    Late,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListRequestsError {
    ExpiredCursor,
    InvalidQuery,
    NotFound,
    ResourceExhausted,
    Unavailable,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListTraceLogsRequest {
    #[serde(rename = "cursor")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub cursor: OptionalValue<String>,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "source_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_id: String,
    #[serde(rename = "span_id")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub span_id: OptionalValue<String>,
    #[serde(rename = "trace_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub trace_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListTraceLogsResponse {
    #[serde(rename = "logs")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub logs: Vec<ListTraceLogsResponseLogsItem>,
    #[serde(rename = "next_cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_cursor: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListTraceLogsResponseLogsItem {
    #[serde(rename = "attributes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attributes: Vec<ListTraceLogsResponseLogsItemAttributesItem>,
    #[serde(rename = "body")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub body: String,
    #[serde(rename = "severity")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub severity: String,
    #[serde(rename = "span_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub span_id: Option<String>,
    #[serde(rename = "timestamp_unix_nano")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub timestamp_unix_nano: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListTraceLogsResponseLogsItemAttributesItem {
    #[serde(rename = "key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub key: String,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListTraceLogsError {
    ExpiredCursor,
    InvalidQuery,
    NotFound,
    ResourceExhausted,
    Unavailable,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadIngestionHealthRequest {
    #[serde(rename = "source_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadIngestionHealthResponse {
    #[serde(rename = "accepted_logs")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub accepted_logs: String,
    #[serde(rename = "accepted_spans")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub accepted_spans: String,
    #[serde(rename = "decode_failures")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub decode_failures: String,
    #[serde(rename = "feed_lag")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub feed_lag: String,
    #[serde(rename = "queue_depth")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub queue_depth: i64,
    #[serde(rename = "queue_saturation")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub queue_saturation: String,
    #[serde(rename = "receiver_epoch")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub receiver_epoch: String,
    #[serde(rename = "redacted_attributes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub redacted_attributes: String,
    #[serde(rename = "rejected_records")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub rejected_records: String,
    #[serde(rename = "retention_bytes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub retention_bytes: String,
    #[serde(rename = "retention_days")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub retention_days: i64,
    #[serde(rename = "retention_deletions")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub retention_deletions: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadIngestionHealthError {
    ExpiredCursor,
    InvalidQuery,
    NotFound,
    ResourceExhausted,
    Unavailable,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadTraceRequest {
    #[serde(rename = "source_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_id: String,
    #[serde(rename = "trace_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub trace_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadTraceResponse {
    #[serde(rename = "completeness")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completeness: ReadTraceResponseCompleteness,
    #[serde(rename = "spans")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub spans: Vec<ReadTraceResponseSpansItem>,
    #[serde(rename = "trace_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub trace_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ReadTraceResponseCompleteness {
    #[serde(rename = "complete")]
    Complete,
    #[serde(rename = "partial")]
    Partial,
    #[serde(rename = "late")]
    Late,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadTraceResponseSpansItem {
    #[serde(rename = "attributes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attributes: Vec<ReadTraceResponseSpansItemAttributesItem>,
    #[serde(rename = "ended_at_unix_nano")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub ended_at_unix_nano: String,
    #[serde(rename = "events")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<ReadTraceResponseSpansItemEventsItem>>,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: ReadTraceResponseSpansItemKind,
    #[serde(rename = "links")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<ReadTraceResponseSpansItemLinksItem>>,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "parent_span_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub parent_span_id: Option<String>,
    #[serde(rename = "span_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub span_id: String,
    #[serde(rename = "started_at_unix_nano")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub started_at_unix_nano: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: ReadTraceResponseSpansItemStatus,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadTraceResponseSpansItemAttributesItem {
    #[serde(rename = "key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub key: String,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadTraceResponseSpansItemEventsItem {
    #[serde(rename = "attributes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attributes: Vec<ReadTraceResponseSpansItemEventsItemAttributesItem>,
    #[serde(rename = "name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub name: String,
    #[serde(rename = "timestamp_unix_nano")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub timestamp_unix_nano: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadTraceResponseSpansItemEventsItemAttributesItem {
    #[serde(rename = "key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub key: String,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ReadTraceResponseSpansItemKind {
    #[serde(rename = "unspecified")]
    Unspecified,
    #[serde(rename = "internal")]
    Internal,
    #[serde(rename = "server")]
    Server,
    #[serde(rename = "client")]
    Client,
    #[serde(rename = "producer")]
    Producer,
    #[serde(rename = "consumer")]
    Consumer,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadTraceResponseSpansItemLinksItem {
    #[serde(rename = "attributes")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attributes: Vec<ReadTraceResponseSpansItemLinksItemAttributesItem>,
    #[serde(rename = "span_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub span_id: String,
    #[serde(rename = "trace_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub trace_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadTraceResponseSpansItemLinksItemAttributesItem {
    #[serde(rename = "key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub key: String,
    #[serde(rename = "value")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub value: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum ReadTraceResponseSpansItemStatus {
    #[serde(rename = "unset")]
    Unset,
    #[serde(rename = "ok")]
    Ok,
    #[serde(rename = "error")]
    Error,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadTraceError {
    ExpiredCursor,
    InvalidQuery,
    NotFound,
    ResourceExhausted,
    Unavailable,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct WatchRequestsRequest {
    #[serde(rename = "source_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub source_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct WatchRequestsResponse {
    #[serde(rename = "completeness")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completeness: Option<String>,
    #[serde(rename = "dropped_count")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub dropped_count: String,
    #[serde(rename = "duration_nano")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub duration_nano: Option<String>,
    #[serde(rename = "has_error")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub has_error: Option<bool>,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: WatchRequestsResponseKind,
    #[serde(rename = "method")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub method: Option<String>,
    #[serde(rename = "route")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub route: Option<String>,
    #[serde(rename = "service_name")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub service_name: Option<String>,
    #[serde(rename = "started_at_unix_nano")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub started_at_unix_nano: Option<String>,
    #[serde(rename = "status_code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status_code: Option<i64>,
    #[serde(rename = "trace_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub trace_id: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum WatchRequestsResponseKind {
    #[serde(rename = "request")]
    Request,
    #[serde(rename = "lag")]
    Lag,
}

#[derive(Clone, Debug, PartialEq)]
pub enum WatchRequestsError {
    ExpiredCursor,
    InvalidQuery,
    NotFound,
    ResourceExhausted,
    Unavailable,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct QueryListRequests;
impl RequestCapability for QueryListRequests {
    type Request = ListRequestsRequest;
    type Response = ListRequestsResponse;
    type DomainError = ListRequestsError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_REQUESTS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<QueryRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list_requests(context, request)
    }
}

#[derive(Debug)]
pub struct QueryListTraceLogs;
impl RequestCapability for QueryListTraceLogs {
    type Request = ListTraceLogsRequest;
    type Response = ListTraceLogsResponse;
    type DomainError = ListTraceLogsError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_TRACE_LOGS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<QueryRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list_trace_logs(context, request)
    }
}

#[derive(Debug)]
pub struct QueryReadIngestionHealth;
impl RequestCapability for QueryReadIngestionHealth {
    type Request = ReadIngestionHealthRequest;
    type Response = ReadIngestionHealthResponse;
    type DomainError = ReadIngestionHealthError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_INGESTION_HEALTH_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<QueryRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read_ingestion_health(context, request)
    }
}

#[derive(Debug)]
pub struct QueryReadTrace;
impl RequestCapability for QueryReadTrace {
    type Request = ReadTraceRequest;
    type Response = ReadTraceResponse;
    type DomainError = ReadTraceError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_TRACE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<QueryRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read_trace(context, request)
    }
}

#[derive(Debug)]
pub struct QueryWatchRequests;
pub type QueryWatchRequestsEvent = StreamEvent<WatchRequestsResponse, WatchRequestsError>;
impl StreamCapability for QueryWatchRequests {
    type OpenRequest = WatchRequestsRequest;
    type Message = WatchRequestsResponse;
    type DomainError = WatchRequestsError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;
}

impl serde::Serialize for ListRequestsError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ExpiredCursor => serializer.serialize_str("expired_cursor"),
            Self::InvalidQuery => serializer.serialize_str("invalid_query"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::ResourceExhausted => serializer.serialize_str("resource_exhausted"),
            Self::Unavailable => serializer.serialize_str("unavailable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListRequestsError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "expired_cursor" => Ok(Self::ExpiredCursor),
                "invalid_query" => Ok(Self::InvalidQuery),
                "not_found" => Ok(Self::NotFound),
                "resource_exhausted" => Ok(Self::ResourceExhausted),
                "unavailable" => Ok(Self::Unavailable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ListTraceLogsError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ExpiredCursor => serializer.serialize_str("expired_cursor"),
            Self::InvalidQuery => serializer.serialize_str("invalid_query"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::ResourceExhausted => serializer.serialize_str("resource_exhausted"),
            Self::Unavailable => serializer.serialize_str("unavailable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListTraceLogsError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "expired_cursor" => Ok(Self::ExpiredCursor),
                "invalid_query" => Ok(Self::InvalidQuery),
                "not_found" => Ok(Self::NotFound),
                "resource_exhausted" => Ok(Self::ResourceExhausted),
                "unavailable" => Ok(Self::Unavailable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReadIngestionHealthError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ExpiredCursor => serializer.serialize_str("expired_cursor"),
            Self::InvalidQuery => serializer.serialize_str("invalid_query"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::ResourceExhausted => serializer.serialize_str("resource_exhausted"),
            Self::Unavailable => serializer.serialize_str("unavailable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadIngestionHealthError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "expired_cursor" => Ok(Self::ExpiredCursor),
                "invalid_query" => Ok(Self::InvalidQuery),
                "not_found" => Ok(Self::NotFound),
                "resource_exhausted" => Ok(Self::ResourceExhausted),
                "unavailable" => Ok(Self::Unavailable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReadTraceError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ExpiredCursor => serializer.serialize_str("expired_cursor"),
            Self::InvalidQuery => serializer.serialize_str("invalid_query"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::ResourceExhausted => serializer.serialize_str("resource_exhausted"),
            Self::Unavailable => serializer.serialize_str("unavailable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadTraceError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "expired_cursor" => Ok(Self::ExpiredCursor),
                "invalid_query" => Ok(Self::InvalidQuery),
                "not_found" => Ok(Self::NotFound),
                "resource_exhausted" => Ok(Self::ResourceExhausted),
                "unavailable" => Ok(Self::Unavailable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for WatchRequestsError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ExpiredCursor => serializer.serialize_str("expired_cursor"),
            Self::InvalidQuery => serializer.serialize_str("invalid_query"),
            Self::NotFound => serializer.serialize_str("not_found"),
            Self::ResourceExhausted => serializer.serialize_str("resource_exhausted"),
            Self::Unavailable => serializer.serialize_str("unavailable"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for WatchRequestsError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "expired_cursor" => Ok(Self::ExpiredCursor),
                "invalid_query" => Ok(Self::InvalidQuery),
                "not_found" => Ok(Self::NotFound),
                "resource_exhausted" => Ok(Self::ResourceExhausted),
                "unavailable" => Ok(Self::Unavailable),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_list_requests_request(value: &ListRequestsRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_requests_request(wire: &str) -> Result<ListRequestsRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_requests_response(value: &ListRequestsResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_requests_response(wire: &str) -> Result<ListRequestsResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_requests_error(value: &ListRequestsError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_requests_error(wire: &str) -> Result<ListRequestsError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_list_trace_logs_request(value: &ListTraceLogsRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_trace_logs_request(wire: &str) -> Result<ListTraceLogsRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_trace_logs_response(value: &ListTraceLogsResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_trace_logs_response(wire: &str) -> Result<ListTraceLogsResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_trace_logs_error(value: &ListTraceLogsError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_trace_logs_error(wire: &str) -> Result<ListTraceLogsError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_read_ingestion_health_request(value: &ReadIngestionHealthRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_ingestion_health_request(wire: &str) -> Result<ReadIngestionHealthRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_ingestion_health_response(value: &ReadIngestionHealthResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_ingestion_health_response(wire: &str) -> Result<ReadIngestionHealthResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_ingestion_health_error(value: &ReadIngestionHealthError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_ingestion_health_error(wire: &str) -> Result<ReadIngestionHealthError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_read_trace_request(value: &ReadTraceRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_trace_request(wire: &str) -> Result<ReadTraceRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_trace_response(value: &ReadTraceResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_trace_response(wire: &str) -> Result<ReadTraceResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_trace_error(value: &ReadTraceError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_trace_error(wire: &str) -> Result<ReadTraceError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_watch_requests_request(value: &WatchRequestsRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_watch_requests_request(wire: &str) -> Result<WatchRequestsRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_watch_requests_response(value: &WatchRequestsResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_watch_requests_response(wire: &str) -> Result<WatchRequestsResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_watch_requests_error(value: &WatchRequestsError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_watch_requests_error(wire: &str) -> Result<WatchRequestsError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoQueryListRequestsResult {
    fn __lenso_into_result(self) -> Result<Result<ListRequestsResponse, ListRequestsError>, RuntimeFailure>;
}
impl __LensoIntoQueryListRequestsResult for Result<ListRequestsResponse, ListRequestsError> {
    fn __lenso_into_result(self) -> Result<Result<ListRequestsResponse, ListRequestsError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoQueryListRequestsResult for Result<Result<ListRequestsResponse, ListRequestsError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListRequestsResponse, ListRequestsError>, RuntimeFailure> { self }
}
impl __LensoIntoQueryListRequestsResult for Result<ListRequestsResponse, lenso_plugin_authoring::PluginError<ListRequestsError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListRequestsResponse, ListRequestsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoQueryListRequestsResult for Result<ListRequestsResponse, QueryListRequestsInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListRequestsResponse, ListRequestsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(QueryListRequestsInvocationError::Domain(error)) => Ok(Err(error)),
            Err(QueryListRequestsInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoQueryListTraceLogsResult {
    fn __lenso_into_result(self) -> Result<Result<ListTraceLogsResponse, ListTraceLogsError>, RuntimeFailure>;
}
impl __LensoIntoQueryListTraceLogsResult for Result<ListTraceLogsResponse, ListTraceLogsError> {
    fn __lenso_into_result(self) -> Result<Result<ListTraceLogsResponse, ListTraceLogsError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoQueryListTraceLogsResult for Result<Result<ListTraceLogsResponse, ListTraceLogsError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListTraceLogsResponse, ListTraceLogsError>, RuntimeFailure> { self }
}
impl __LensoIntoQueryListTraceLogsResult for Result<ListTraceLogsResponse, lenso_plugin_authoring::PluginError<ListTraceLogsError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListTraceLogsResponse, ListTraceLogsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoQueryListTraceLogsResult for Result<ListTraceLogsResponse, QueryListTraceLogsInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListTraceLogsResponse, ListTraceLogsError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(QueryListTraceLogsInvocationError::Domain(error)) => Ok(Err(error)),
            Err(QueryListTraceLogsInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoQueryReadIngestionHealthResult {
    fn __lenso_into_result(self) -> Result<Result<ReadIngestionHealthResponse, ReadIngestionHealthError>, RuntimeFailure>;
}
impl __LensoIntoQueryReadIngestionHealthResult for Result<ReadIngestionHealthResponse, ReadIngestionHealthError> {
    fn __lenso_into_result(self) -> Result<Result<ReadIngestionHealthResponse, ReadIngestionHealthError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoQueryReadIngestionHealthResult for Result<Result<ReadIngestionHealthResponse, ReadIngestionHealthError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReadIngestionHealthResponse, ReadIngestionHealthError>, RuntimeFailure> { self }
}
impl __LensoIntoQueryReadIngestionHealthResult for Result<ReadIngestionHealthResponse, lenso_plugin_authoring::PluginError<ReadIngestionHealthError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReadIngestionHealthResponse, ReadIngestionHealthError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoQueryReadIngestionHealthResult for Result<ReadIngestionHealthResponse, QueryReadIngestionHealthInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReadIngestionHealthResponse, ReadIngestionHealthError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(QueryReadIngestionHealthInvocationError::Domain(error)) => Ok(Err(error)),
            Err(QueryReadIngestionHealthInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoQueryReadTraceResult {
    fn __lenso_into_result(self) -> Result<Result<ReadTraceResponse, ReadTraceError>, RuntimeFailure>;
}
impl __LensoIntoQueryReadTraceResult for Result<ReadTraceResponse, ReadTraceError> {
    fn __lenso_into_result(self) -> Result<Result<ReadTraceResponse, ReadTraceError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoQueryReadTraceResult for Result<Result<ReadTraceResponse, ReadTraceError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReadTraceResponse, ReadTraceError>, RuntimeFailure> { self }
}
impl __LensoIntoQueryReadTraceResult for Result<ReadTraceResponse, lenso_plugin_authoring::PluginError<ReadTraceError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReadTraceResponse, ReadTraceError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoQueryReadTraceResult for Result<ReadTraceResponse, QueryReadTraceInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReadTraceResponse, ReadTraceError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(QueryReadTraceInvocationError::Domain(error)) => Ok(Err(error)),
            Err(QueryReadTraceInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoQueryWatchRequestsStreamResult {
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, QueryWatchRequestsInvocationError>;
}
impl<S> __LensoIntoQueryWatchRequestsStreamResult for Result<S, WatchRequestsError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, QueryWatchRequestsInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
            .map_err(QueryWatchRequestsInvocationError::Domain)
    }
}
impl<S> __LensoIntoQueryWatchRequestsStreamResult for Result<S, lenso_plugin_authoring::PluginError<WatchRequestsError, RuntimeFailure>>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, QueryWatchRequestsInvocationError> {
        match self {
            Ok(stream) => Ok(Box::new(stream) as Box<dyn NativeStreamSession>),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Err(QueryWatchRequestsInvocationError::Domain(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(QueryWatchRequestsInvocationError::Runtime(error)),
        }
    }
}
impl<S> __LensoIntoQueryWatchRequestsStreamResult for Result<S, QueryWatchRequestsInvocationError>
where
    S: NativeStreamSession + 'static,
{
    fn __lenso_into_result(self) -> Result<Box<dyn NativeStreamSession>, QueryWatchRequestsInvocationError> {
        self.map(|stream| Box::new(stream) as Box<dyn NativeStreamSession>)
    }
}

pub trait QueryProvider: fmt::Debug + 'static {
    fn list_requests(&self, context: InvocationContext, request: ListRequestsRequest) -> NativeRequestFuture<QueryListRequests>;
    fn list_trace_logs(&self, context: InvocationContext, request: ListTraceLogsRequest) -> NativeRequestFuture<QueryListTraceLogs>;
    fn read_ingestion_health(&self, context: InvocationContext, request: ReadIngestionHealthRequest) -> NativeRequestFuture<QueryReadIngestionHealth>;
    fn read_trace(&self, context: InvocationContext, request: ReadTraceRequest) -> NativeRequestFuture<QueryReadTrace>;
    fn watch_requests(&self, context: InvocationContext, request: WatchRequestsRequest) -> LocalBoxFuture<'static, Result<Box<dyn NativeStreamSession>, QueryWatchRequestsInvocationError>>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_query {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportQuery;
        impl $crate::QueryProvider for $plugin {
        fn list_requests(&self, context: __LensoNativeSupportQuery::InvocationContext, request: $crate::ListRequestsRequest) -> __LensoNativeSupportQuery::NativeRequestFuture<$crate::QueryListRequests> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list_requests(&plugin, context, request).await;
                $crate::__LensoIntoQueryListRequestsResult::__lenso_into_result(result)
            })
        }
        fn list_trace_logs(&self, context: __LensoNativeSupportQuery::InvocationContext, request: $crate::ListTraceLogsRequest) -> __LensoNativeSupportQuery::NativeRequestFuture<$crate::QueryListTraceLogs> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list_trace_logs(&plugin, context, request).await;
                $crate::__LensoIntoQueryListTraceLogsResult::__lenso_into_result(result)
            })
        }
        fn read_ingestion_health(&self, context: __LensoNativeSupportQuery::InvocationContext, request: $crate::ReadIngestionHealthRequest) -> __LensoNativeSupportQuery::NativeRequestFuture<$crate::QueryReadIngestionHealth> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::read_ingestion_health(&plugin, context, request).await;
                $crate::__LensoIntoQueryReadIngestionHealthResult::__lenso_into_result(result)
            })
        }
        fn read_trace(&self, context: __LensoNativeSupportQuery::InvocationContext, request: $crate::ReadTraceRequest) -> __LensoNativeSupportQuery::NativeRequestFuture<$crate::QueryReadTrace> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::read_trace(&plugin, context, request).await;
                $crate::__LensoIntoQueryReadTraceResult::__lenso_into_result(result)
            })
        }
        fn watch_requests(&self, context: __LensoNativeSupportQuery::InvocationContext, request: $crate::WatchRequestsRequest) -> __LensoNativeSupportQuery::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportQuery::NativeStreamSession>, $crate::QueryWatchRequestsInvocationError>> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::watch_requests(&plugin, context, request).await;
                $crate::__LensoIntoQueryWatchRequestsStreamResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_query {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportQuery;
        impl $crate::QueryProvider for $object {
        fn list_requests(&self, context: __LensoNativeSupportQuery::InvocationContext, request: $crate::ListRequestsRequest) -> __LensoNativeSupportQuery::NativeRequestFuture<$crate::QueryListRequests> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::list_requests(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoQueryListRequestsResult::__lenso_into_result(result)
            })
        }
        fn list_trace_logs(&self, context: __LensoNativeSupportQuery::InvocationContext, request: $crate::ListTraceLogsRequest) -> __LensoNativeSupportQuery::NativeRequestFuture<$crate::QueryListTraceLogs> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::list_trace_logs(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoQueryListTraceLogsResult::__lenso_into_result(result)
            })
        }
        fn read_ingestion_health(&self, context: __LensoNativeSupportQuery::InvocationContext, request: $crate::ReadIngestionHealthRequest) -> __LensoNativeSupportQuery::NativeRequestFuture<$crate::QueryReadIngestionHealth> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::read_ingestion_health(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoQueryReadIngestionHealthResult::__lenso_into_result(result)
            })
        }
        fn read_trace(&self, context: __LensoNativeSupportQuery::InvocationContext, request: $crate::ReadTraceRequest) -> __LensoNativeSupportQuery::NativeRequestFuture<$crate::QueryReadTrace> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::read_trace(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoQueryReadTraceResult::__lenso_into_result(result)
            })
        }
        fn watch_requests(&self, context: __LensoNativeSupportQuery::InvocationContext, request: $crate::WatchRequestsRequest) -> __LensoNativeSupportQuery::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportQuery::NativeStreamSession>, $crate::QueryWatchRequestsInvocationError>> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get().map_err($crate::QueryWatchRequestsInvocationError::Runtime)?;
                let result = <$plugin>::watch_requests(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoQueryWatchRequestsStreamResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_query {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportQuery;
        impl $crate::QueryProvider for $object {
        fn list_requests(&self, context: __LensoNativeSupportQuery::InvocationContext, request: $crate::ListRequestsRequest) -> __LensoNativeSupportQuery::NativeRequestFuture<$crate::QueryListRequests> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::QueryProvider>::list_requests(plugin.as_ref(), context, request).await
            })
        }
        fn list_trace_logs(&self, context: __LensoNativeSupportQuery::InvocationContext, request: $crate::ListTraceLogsRequest) -> __LensoNativeSupportQuery::NativeRequestFuture<$crate::QueryListTraceLogs> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::QueryProvider>::list_trace_logs(plugin.as_ref(), context, request).await
            })
        }
        fn read_ingestion_health(&self, context: __LensoNativeSupportQuery::InvocationContext, request: $crate::ReadIngestionHealthRequest) -> __LensoNativeSupportQuery::NativeRequestFuture<$crate::QueryReadIngestionHealth> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::QueryProvider>::read_ingestion_health(plugin.as_ref(), context, request).await
            })
        }
        fn read_trace(&self, context: __LensoNativeSupportQuery::InvocationContext, request: $crate::ReadTraceRequest) -> __LensoNativeSupportQuery::NativeRequestFuture<$crate::QueryReadTrace> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::QueryProvider>::read_trace(plugin.as_ref(), context, request).await
            })
        }
        fn watch_requests(&self, context: __LensoNativeSupportQuery::InvocationContext, request: $crate::WatchRequestsRequest) -> __LensoNativeSupportQuery::LocalBoxFuture<'static, Result<Box<dyn __LensoNativeSupportQuery::NativeStreamSession>, $crate::QueryWatchRequestsInvocationError>> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get().map_err($crate::QueryWatchRequestsInvocationError::Runtime)?;
                <$plugin as $crate::QueryProvider>::watch_requests(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct QueryRequestEndpoint { provider: Rc<dyn QueryProvider> }

#[derive(Debug)]
pub struct QueryEndpoint<P: QueryProvider> { provider: Rc<P>, request_endpoint: QueryRequestEndpoint }
impl<P: QueryProvider> QueryEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn QueryProvider> = provider.clone();
        Self { provider, request_endpoint: QueryRequestEndpoint { provider: request_provider } }
    }
}

impl<P: QueryProvider> NativeRequestEndpoint for QueryEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        LIST_REQUESTS_OPERATION,
        LIST_TRACE_LOGS_OPERATION,
        READ_INGESTION_HEALTH_OPERATION,
        READ_TRACE_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            LIST_REQUESTS_OPERATION => {
                let Ok(request) = request.downcast::<ListRequestsRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list_requests(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            LIST_TRACE_LOGS_OPERATION => {
                let Ok(request) = request.downcast::<ListTraceLogsRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list_trace_logs(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            READ_INGESTION_HEALTH_OPERATION => {
                let Ok(request) = request.downcast::<ReadIngestionHealthRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read_ingestion_health(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            READ_TRACE_OPERATION => {
                let Ok(request) = request.downcast::<ReadTraceRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read_trace(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

impl<P: QueryProvider> NativeStreamEndpoint for QueryEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        WATCH_REQUESTS_OPERATION,
    ] }
    fn open(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn NativeStreamSession>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            WATCH_REQUESTS_OPERATION => {
                let Ok(request) = request.downcast::<WatchRequestsRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let provider = Rc::clone(&self.provider);
                Box::pin(async move {
                    match provider.watch_requests(context, *request).await {
                        Ok(value) => Ok(Ok(value as Box<dyn NativeStreamSession>)),
                        Err(QueryWatchRequestsInvocationError::Domain(error)) => Ok(Err(Box::new(error) as Box<dyn std::any::Any>)),
                        Err(QueryWatchRequestsInvocationError::Runtime(error)) => Err(error),
                    }
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_query {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::QueryEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeStreamEndpoint>],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_query {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_query!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct QueryClient {
    list_requests: NativeRequestHandle<QueryListRequests>,
    list_trace_logs: NativeRequestHandle<QueryListTraceLogs>,
    read_ingestion_health: NativeRequestHandle<QueryReadIngestionHealth>,
    read_trace: NativeRequestHandle<QueryReadTrace>,
    watch_requests: NativeStreamHandle<QueryWatchRequests>,
}
impl QueryClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn list_requests(&self, request: ListRequestsRequest) -> Result<ListRequestsResponse, QueryListRequestsInvocationError> {
        self.list_requests.invoke(LIST_REQUESTS_OPERATION, request).await
            .map_err(QueryListRequestsInvocationError::Runtime)?
            .map_err(QueryListRequestsInvocationError::Domain)
    }

    pub async fn list_requests_with_context(&self, context: InvocationContext, request: ListRequestsRequest) -> Result<ListRequestsResponse, QueryListRequestsInvocationError> {
        self.list_requests.invoke_with_context(LIST_REQUESTS_OPERATION, context, request).await
            .map_err(QueryListRequestsInvocationError::Runtime)?
            .map_err(QueryListRequestsInvocationError::Domain)
    }

    pub async fn list_trace_logs(&self, request: ListTraceLogsRequest) -> Result<ListTraceLogsResponse, QueryListTraceLogsInvocationError> {
        self.list_trace_logs.invoke(LIST_TRACE_LOGS_OPERATION, request).await
            .map_err(QueryListTraceLogsInvocationError::Runtime)?
            .map_err(QueryListTraceLogsInvocationError::Domain)
    }

    pub async fn list_trace_logs_with_context(&self, context: InvocationContext, request: ListTraceLogsRequest) -> Result<ListTraceLogsResponse, QueryListTraceLogsInvocationError> {
        self.list_trace_logs.invoke_with_context(LIST_TRACE_LOGS_OPERATION, context, request).await
            .map_err(QueryListTraceLogsInvocationError::Runtime)?
            .map_err(QueryListTraceLogsInvocationError::Domain)
    }

    pub async fn read_ingestion_health(&self, request: ReadIngestionHealthRequest) -> Result<ReadIngestionHealthResponse, QueryReadIngestionHealthInvocationError> {
        self.read_ingestion_health.invoke(READ_INGESTION_HEALTH_OPERATION, request).await
            .map_err(QueryReadIngestionHealthInvocationError::Runtime)?
            .map_err(QueryReadIngestionHealthInvocationError::Domain)
    }

    pub async fn read_ingestion_health_with_context(&self, context: InvocationContext, request: ReadIngestionHealthRequest) -> Result<ReadIngestionHealthResponse, QueryReadIngestionHealthInvocationError> {
        self.read_ingestion_health.invoke_with_context(READ_INGESTION_HEALTH_OPERATION, context, request).await
            .map_err(QueryReadIngestionHealthInvocationError::Runtime)?
            .map_err(QueryReadIngestionHealthInvocationError::Domain)
    }

    pub async fn read_trace(&self, request: ReadTraceRequest) -> Result<ReadTraceResponse, QueryReadTraceInvocationError> {
        self.read_trace.invoke(READ_TRACE_OPERATION, request).await
            .map_err(QueryReadTraceInvocationError::Runtime)?
            .map_err(QueryReadTraceInvocationError::Domain)
    }

    pub async fn read_trace_with_context(&self, context: InvocationContext, request: ReadTraceRequest) -> Result<ReadTraceResponse, QueryReadTraceInvocationError> {
        self.read_trace.invoke_with_context(READ_TRACE_OPERATION, context, request).await
            .map_err(QueryReadTraceInvocationError::Runtime)?
            .map_err(QueryReadTraceInvocationError::Domain)
    }

    pub async fn watch_requests(&self, request: WatchRequestsRequest) -> Result<NativeStream<QueryWatchRequests>, QueryWatchRequestsInvocationError> {
        self.watch_requests.open(WATCH_REQUESTS_OPERATION, request).await
            .map_err(QueryWatchRequestsInvocationError::Runtime)?
            .map_err(QueryWatchRequestsInvocationError::Domain)
    }

    pub async fn watch_requests_with_context(&self, context: InvocationContext, request: WatchRequestsRequest) -> Result<NativeStream<QueryWatchRequests>, QueryWatchRequestsInvocationError> {
        self.watch_requests.open_with_context(WATCH_REQUESTS_OPERATION, context, request).await
            .map_err(QueryWatchRequestsInvocationError::Runtime)?
            .map_err(QueryWatchRequestsInvocationError::Domain)
    }
}

impl CapabilityClient for QueryClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            list_requests: dependencies.one::<QueryListRequests>()?,
            list_trace_logs: dependencies.one::<QueryListTraceLogs>()?,
            read_ingestion_health: dependencies.one::<QueryReadIngestionHealth>()?,
            read_trace: dependencies.one::<QueryReadTrace>()?,
            watch_requests: dependencies.one_stream::<QueryWatchRequests>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for QueryClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    list_requests: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<QueryListRequests>()?,
                    list_trace_logs: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<QueryListTraceLogs>()?,
                    read_ingestion_health: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<QueryReadIngestionHealth>()?,
                    read_trace: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<QueryReadTrace>()?,
                    watch_requests: binding.stream_handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<QueryWatchRequests>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum QueryListRequestsInvocationError {
    Domain(ListRequestsError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum QueryListTraceLogsInvocationError {
    Domain(ListTraceLogsError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum QueryReadIngestionHealthInvocationError {
    Domain(ReadIngestionHealthError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum QueryReadTraceInvocationError {
    Domain(ReadTraceError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum QueryWatchRequestsInvocationError {
    Domain(WatchRequestsError),
    Runtime(RuntimeFailure),
}
