[workspace]
resolver = "2"
members = [
  "crates/lenso-management-core",
  "crates/lenso-management-authority",
  "crates/lenso-management-http",
]

[patch.crates-io]
lenso = { git = "https://github.com/LioRael/lenso", rev = "c0464691b6ae1c80b5606065dd4073e8b7d6a59e" }
lenso-native-adapter = { git = "https://github.com/LioRael/lenso", rev = "c0464691b6ae1c80b5606065dd4073e8b7d6a59e" }
lenso-native-adapter-macros = { git = "https://github.com/LioRael/lenso", rev = "c0464691b6ae1c80b5606065dd4073e8b7d6a59e" }
lenso-kernel = { git = "https://github.com/LioRael/lenso", rev = "c0464691b6ae1c80b5606065dd4073e8b7d6a59e" }
lenso-app-plan = { git = "https://github.com/LioRael/lenso", rev = "c0464691b6ae1c80b5606065dd4073e8b7d6a59e" }
lenso-plugin-authoring = { git = "https://github.com/LioRael/lenso", rev = "c0464691b6ae1c80b5606065dd4073e8b7d6a59e" }
lenso-runtime-codec = { git = "https://github.com/LioRael/lenso", rev = "c0464691b6ae1c80b5606065dd4073e8b7d6a59e" }
lenso-contract-authoring = { git = "https://github.com/LioRael/lenso", rev = "c0464691b6ae1c80b5606065dd4073e8b7d6a59e" }
lenso-contract-authoring-macros = { git = "https://github.com/LioRael/lenso", rev = "c0464691b6ae1c80b5606065dd4073e8b7d6a59e" }
lenso-contract-codegen = { git = "https://github.com/LioRael/lenso", rev = "c0464691b6ae1c80b5606065dd4073e8b7d6a59e" }
lenso-contract-runtime = { git = "https://github.com/LioRael/lenso", rev = "c0464691b6ae1c80b5606065dd4073e8b7d6a59e" }
